### DISCUSSION TITLE
Cilium CNI - Proxy mode ebpf

### DISCUSSION THREAD

**Discussion by clickersmudge** [kubermatic/kubermatic#11304] [Q&A] [answered]
Hi,
We read your article about Cillium CNI benefits (https://www.kubermatic.com/blog/cilium-cni-integration-in-kubermatic-kubernetes-platform/).

When creating KubeOne cluster we use this setting.
```
apiVersion: kubeone.k8c.io/v1beta2
kind: KubeOneCluster
versions:
  kubernetes: '1.24.7'
clusterNetwork:
  kubeProxy:
    skipInstallation: true
  cni:
    cilium:
      enableHubble: true
      kubeProxyReplacement: "strict"

cloudProvider:
  hetzner: {}
  external: true
addons:
  enable: true
  path: "./addons"
  addons:
    - name: "cluster-autoscaler"
    - name: "default-storage-class"
    - name: "unattended-upgrades"
```

However, when creating a cluster in KKP we do not see the "ebpf" option.
![image](https://user-images.githubusercontent.com/113194014/200336849-8e93bf2e-3519-4ee6-8a8b-69e394dad544.png)
Only "iptables".

On user clustercCreated by KKP we see " kube-proxy-l26m2" pod:
```
kube-system            kube-proxy-l26m2                            1/1     Running   0          17m
```

Should it be like that?
