### DISCUSSION TITLE
Securing System Services

### DISCUSSION THREAD

**Discussion by clickersmudge** [kubermatic/kubermatic#12889] [Q&A]
Hi,
We have a problem with IAP. 

## We configured Dex (values.yaml)
```
# Depending on your chosen login method, you need to configure either an OAuth provider like
  # Google or GitHub, or configure a set of static passwords. Check the `charts/oauth/values.yaml`
  # for an overview over all available connectors.
dex:
  connectors:
  - type: github
    id: github
    name: GitHub
    config:
      clientID: example
      clientSecret: example
      redirectURI: https://kubermatic.example.com/dex/callback
      orgs:
      - name: example-org
```

## We configured  IAP (iap.yaml)
```
iap:
  oidc_issuer_url: https://kubermatic.example.com/dex
  replicas: 1
  deployments:
    mla-master-alertmanager:
      name: mla-master-alertmanager
      client_id: mla-master-alertmanager
      client_secret: example
      encryption_key: example
      config:
        scope: "groups openid email"
        email_domains:
          - '*'
        github_org: example-org
        github_team: master-alertmanager
        skip_auth_regex:
          - '/-/healthy'
      upstream_service: alertmanager.monitoring.svc.cluster.local
      upstream_port: 9093
      ingress:
        host: "alertmanager.kubermatic.example.com"
```

Logging in using GithHub works on KKP.

## Problem
For example, when we log into Alertmanager using GitHub, it does not respect the parameters
```
github_org: example-org
github_team: master-alertmanager
```

We think we will set everything according to the documentation
https://docs.kubermatic.com/kubermatic/v2.24/architecture/concept/kkp-concepts/kkp-security/securing-system-services/#oauth2-proxy-iap
```
 # see https://github.com/oauth2-proxy/oauth2-proxy/blob/master/docs/configuration/configuration.md
      # this example configures that only users belong to a special GitHub
      # organization can access the service behind the proxy (Prometheus in this case)
      config:
        scope: "groups openid email"
        github_org: mygithuborg
        github_team: mygroup
```

When we log in to GitHub, even though we are not assigned to a team in GitHub, it logs us correctly and we see a Alertmanager panel that we should not have access to.
Can you help?
