### ISSUE TITLE
Etcd Backup Destinations accept Bucket Names which are invalid for restore

### ISSUE THREAD

**Issue by toothstone** [kubermatic/kubermatic#10075]
### What happened?

We configured our KKP Backup Destinations using the pattern `Bucket Name: <bucket>/<some>/<prefix>/<per>/<instance>`. KKP accepts those and writes backups to the desired destination, but trying to restore from them gives an error:
`failed to reconcile etcd restore "nnvtk9g7q7": could not access backup object 6hnmcf4bdm-default-backups-2022-06-13t05-42-46: Bucket name contains invalid characters`

### Expected behavior

KKP does not allow the creation of Backup Destinations with invalid `Bucket Name`s (see e.g. https://stackoverflow.com/questions/50480924/regex-for-s3-bucket-name).

### How to reproduce the issue?

- Create a Backup Destination, with slashes in the `Bucket Name`

### How is your environment configured?

- KKP version: 2.19.5
- Shared or separate master/seed clusters?: Shared

### Provide your KKP manifest here (if applicable)

<details>
Excerpt from our seeds config:

```yaml
  Etcd Backup Restore:
    Default Destination:  backups
    Destinations:                                                                                                                                    
      backup:
        Bucket Name:  backup/k8s-clusters/region/kkp
        Credentials:                                                                                                                                 
          Name:       backup-credentials
          Namespace:  kube-system
        Endpoint:     <S3 service domain>
```

</details>

### What cloud provider are you running on?

Anexia
