### ISSUE TITLE
Validate LoadBalancer support for Hetzner

### ISSUE THREAD

**Issue by xrstf** [kubermatic/kubermatic#10116]
### What happened?

I created a usercluster on Hetzner (using KKP dev) and installed nginx. I properly annotated the LB Service with the Helm values:

```yaml
nginx:
  controller:
    service:
      annotations:
        helm.sh/resource-policy: keep
        load-balancer.hetzner.cloud/location: nbg1
```

The LB was successfully reconciled and the hcloud-ccm is happy, with no errors being logged. However, the LB is defunct, as it cannot reach the nodes:

![screenshot-2022-06-17-122511](https://user-images.githubusercontent.com/127499/174299680-13b8513a-80d6-49ff-bb6f-e843a999f225.png)

I then tried the exact same setup using our Captain, which is on KKP 2.20.3, where it worked without any issues. It seems that something broke since KKP 2.20, but running a dummy test in https://github.com/kubermatic/kubermatic/pull/10112 resulted in a success, so either there is something different in the e2e tests than on dev, or the problem is somewhere else.

### Expected behavior

I expected the LoadBalancer to work.

### How to reproduce the issue?

See above.

### How is your environment configured?

- KKP version: master branch
- Shared or separate master/seed clusters?: shared
