### ISSUE TITLE
[Proposal] etcd-statefulset backup strategy

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#1013]
Replace the etcd-operator with a StatefulSet.

Following things need to be covered:
- If a existing etcd-operator managed etcd exists, the new cluster needs to be populated by a snapshot created from the existing cluster
- A service needs to exist to automatically create backups for the new etcd-cluster
  Possible would be a k8s CronJob which triggers a backup for a etcd-cluster (Backups need to be persisted on a PVC)

Attached is an example etcd-StatefulSet

[etcd-statefulset.zip](https://github.com/kubermatic/kubermatic/files/1982790/etcd-statefulset.zip)

**Comment by mrIncompetent** [comment]
### Backups:

I though about a backup-daemon which exposes the following endpoints:
- `POST /v1/cluster/xxxxxxx/backup-jobs` -> Used for creating a `BackupJob`
- `GET /v1/cluster/xxxxxxx/backup-jobs` -> List existing `[]BackupJob` 
- `GET /v1/cluster/xxxxxxx/backup-jobs/0` -> Returns the specified `BackupJob`
- `GET /v1/cluster/xxxxxxx/backup-jobs/0/snapshop` -> Returns the snapshot file `Binary`

#### BackupJob
A `BackupJob` describes a one-time job to create a snapshop from the specified etcd.
The `BackupJob` will be handled ansynchronously from backup-daemon.
```yaml
metadata:
  name: cluster-xxxxx-251
  creationTimestamp: 2018-05-12T12:00:00Z
  finalizers:
  - delete-snapshot
spec:
  targetCluster: http:etcd.cluster-xxxxx.svc.default:2379
status:
  finished: 2018-05-12T12:00:05Z
  size: 250mb
  duration: 5s
```

Via flag on the backup-daemon we can configure the maximum number of backup revisions to keep. Old backups should be deleted.

For automatic backup we could create a k8s CronJob which gets all clusters and creates a backup-job on the backup-daemon
