### ISSUE TITLE
The installer is inconsistent concerning input variables

### ISSUE THREAD

**Issue by stroebitzer** [kubermatic/kubermatic#10199]
### What happened?

The installer is inconsistent concerning input variables

This does work
```
kubermatic-installer --charts-directory ~/master/kkp/charts deploy \
    --config ~/master/kkp/kubermatic.yaml \
    --helm-values ~/master/kkp/values.yaml
```

This does not work
```
kubermatic-installer deploy \
    --charts-directory ~/master/kkp/charts \
    --config ~/master/kkp/kubermatic.yaml \
    --helm-values ~/master/kkp/values.yaml
```

### Expected behavior

It does not matter in which order I apply the input variables

### How to reproduce the issue?

Run above command

### How is your environment configured?

- KKP version: 2.20.2
- Shared or separate master/seed clusters?: seperate clusters

### Provide your KKP manifest here (if applicable)

```yaml
apiVersion: kubermatic.k8c.io/v1
kind: KubermaticConfiguration
metadata:
  name: kubermatic
  namespace: kubermatic
spec:

  ingress:
    # Domain is the base domain where the dashboard shall be available. Even with
    # a disabled Ingress, this must always be a valid hostname.
    # this domain must match what you configured as dex.ingress.host
    # in the values.yaml
    domain: SAFETY_FIRST
    certificateIssuer:
      # APIGroup is the group for the resource being referenced.
      # If APIGroup is not specified, the specified Kind must be in the core API group.
      # For any other third-party types, APIGroup is required.
      apiGroup: null
      # Kind is the type of resource being referenced
      kind: ClusterIssuer
      # Name is the name of resource being referenced
      # For generating a certificate signed by a trusted root authority replace
      # with "letsencrypt-prod".
      name: "letsencrypt-staging"
    className: nginx

  # These secret keys configure the way components communicate with Dex.
  auth:
    clientID: kubermatic
    issuerClientID: kubermaticIssuer
    # When using letsencrypt-prod replace with "false"
    skipTokenIssuerTLSVerify: true
    tokenIssuer: https://SAFETY_FIRST/dex

    # This must match the secret configured for the kubermaticIssuer client from
    # the dex clients in values.yaml.
    # Needed if the "enableOIDCKubeconfig: true" option is used in KubermaticSetting
    issuerClientSecret: SAFETY_FIRST

    # these need to be randomly generated. Those can be generated on the
    # shell using:
    # cat /dev/urandom | tr -dc A-Za-z0-9 | head -c32
    issuerCookieKey: SAFETY_FIRST
    serviceAccountKey: SAFETY_FIRST

```

### What cloud provider are you running on?

GCP

### What operating system are you running in your user cluster?

Ubuntu 20.04
