### ISSUE TITLE
Setup and test a vsphere k8s cluster on Debian

### ISSUE THREAD

**Issue by kdomanski** [kubermatic/kubermatic#1020]

**Comment by kdomanski** [comment]
Running. kubeconfig:
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRFNE1EVXdPVEV6TXpNME0xb1hEVEk0TURVd05qRXpNek0wTTFvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTDJXCmNZa1Z5L3gvNmJXNzQ5eW94a3JFcldXbnl6cnJkNStWclZpUUZibU80ZWV1OHMwaEd0RjFDM1E5emVUUE1LNVoKODFzUjBsUDllMnc3NnhvTkl1aUYwaHJMcXd5ODFIM0JDRTBTd3VyWVEvejZoa0RweG9jSGlQTklMMXZVY05CVwpya0N0Nm0rcXRwR01SeHBDZFZDblhmYmxwdHROSmxBYThpbm1xQ3BKTXh6Ym1qcU8vMHFMU0tGV3k0QVU3UmhrCmx6elNseGVKb01tVyt6Zi80c1dWZ1dBRnA0cFkyYVdHczR4Q2x1R1U1aHV3S3BOTEZxK3FrUlU5MitqQnYzSGkKY2IzYjV3STlkNnA1UVZEaFcxcVVXQU9aMFcrNUNyQjJJYS9zYTFWRE1xR0NRMHNEQnhFdVVqVVJFTFVrMC9YNApEd082ZTU5QWxzVVZXcnk0SCtVQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFBc2FLSjZld3ZVTUFhZXBuRGhsYk4rVTVDVXgKWXl1OGs5c2JJUjlLOFY1eTdzSDhYamZrWW44a2l4bDRQNVRYdzBScDRodTMreHRNbWtQWSt3ZW9rUmNtVDBDago0YVkwM3lvWnY1QUZMNjRIV21hLzhVKy9zYU9MOHc2NW9HNVVYN2dVelI1SkpPNWpvdC9mQVdTYnlIdlUreU5GCjkwNkVQRkt2UDBCS0JoY1FCUFo0Mkh3MDNBOGpWM2MzSW94dWRXZzdLVWtmS1paTEZReXE2WFJaNEw3VHBmd2oKYWN5TllLRlFWRklvZFdhM0xUMXJRY1M0cFNleVFYR0RQMUQxUXBVZHBVQjlLa0FYYW1wNVgzT0hUQUNBelNwdQppampBcHFRalJ2VldObS8vdFp6MUljR1p5M0VvcVNIcnkxSk5scUR1b1plTEQ5RjFZZ2Q4cjBiclB2Yz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://10.0.2.151:6443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: kubernetes-admin
  name: kubernetes-admin@kubernetes
current-context: kubernetes-admin@kubernetes
kind: Config
preferences: {}
users:
- name: kubernetes-admin
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM4akNDQWRxZ0F3SUJBZ0lJWlVwZVFwMVBBalV3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB4T0RBMU1Ea3hNek16TkROYUZ3MHhPVEExTURreE16TXpORFphTURReApGekFWQmdOVkJBb1REbk41YzNSbGJUcHRZWE4wWlhKek1Sa3dGd1lEVlFRREV4QnJkV0psY201bGRHVnpMV0ZrCmJXbHVNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXhzcTdBR0tVTFNvQVNwTkIKbTN3NUFXM01yS25NMWlqS1BvcUNKV09EY1JJaHVEaVRWOTIyWnVvQjY3UHBUeVlZRkRiaThadzNEaUI4R3hrWgpwOGJoOWp5N3pKMEJQeExCYUNNT2J4MmJGYmMzdjFISUdibXZXNVJtSVVtV2wyZ0JpZmcyaFk1UTV6ODUxU2xhCnlOcWhCSzlCNjVYNkE0WUUzUExZMzU2ODRPVUF4UlQ2OEh5WnJNV1k5RXdhTmRqMkRkUHhjNkpYRHYxMjBlZGEKS3Y2VDhvc2lDNlltWlkwV3lvaFNsUGNRdGxDU1MrWExiSldnNGF1bnQ1aHBNVktPYU4vZHF2QmEzRkxXemp5SApvOHZoejRDSzBvUEpLQnpkd0QyMWk0UWVPRlByLzc1Y2Rtd0pCWU9QcTY2Y1pBaGozUzlZTHBLckI2OVI1OXc4CjZTNDYvd0lEQVFBQm95Y3dKVEFPQmdOVkhROEJBZjhFQkFNQ0JhQXdFd1lEVlIwbEJBd3dDZ1lJS3dZQkJRVUgKQXdJd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFBemY0dzJFRmdGSW5zWFVldDhYb1U4TGlFSVZhcE1KNVpsVgphWGJVUHV5RGlWOUtmVFo1N0Q4MTBvWmdOekxnNENzNFF0TWhCcmhUY2kvbnRmUGZsVHVNYTc5VkI1Tk91d2tQCkhrWnQvTTBKL0lNT1BvWFFPZTlBN2V2TDZpdlI4UnB0YUQzaktMYy9vRnJzNFl2c2FkaEZCYkRvYlpxdXpDbEgKYmkzVlorN2g0WkwyQXhxSEF2bVF4Y3FZL0xYU3JiVGttMjh5M2cyS0x5UTRISVpwWndoQWJxYWtWODFwMlUyVgp4S1R3ZFVTNTBlTVcvSHFHeFFhdjYvWkl3MmF5VFN0V0lmYnFhZnRMMFJNNXZWRkVDd29sOFZCWnZjaHNjNFdOClNvZE9PcVJmQmlmRlh2RkJBTEYrNE1TdDRYbUpLYklrVVJhQmIxekk0Qmc1bzFnMnFTMD0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcFFJQkFBS0NBUUVBeHNxN0FHS1VMU29BU3BOQm0zdzVBVzNNcktuTTFpaktQb3FDSldPRGNSSWh1RGlUClY5MjJadW9CNjdQcFR5WVlGRGJpOFp3M0RpQjhHeGtacDhiaDlqeTd6SjBCUHhMQmFDTU9ieDJiRmJjM3YxSEkKR2Jtdlc1Um1JVW1XbDJnQmlmZzJoWTVRNXo4NTFTbGF5TnFoQks5QjY1WDZBNFlFM1BMWTM1Njg0T1VBeFJUNgo4SHlack1XWTlFd2FOZGoyRGRQeGM2SlhEdjEyMGVkYUt2NlQ4b3NpQzZZbVpZMFd5b2hTbFBjUXRsQ1NTK1hMCmJKV2c0YXVudDVocE1WS09hTi9kcXZCYTNGTFd6anlIbzh2aHo0Q0swb1BKS0J6ZHdEMjFpNFFlT0ZQci83NWMKZG13SkJZT1BxNjZjWkFoajNTOVlMcEtyQjY5UjU5dzg2UzQ2L3dJREFRQUJBb0lCQUZFU0JuZGV2SDA2dnNtcgpDanVGeXAyNWtKbnQyWnFSSWdHbGJQUWdoRTlOakxEYmFjT1FxTDJKdTJUTGgxOSs4cHp6MFZPbFdKS0xUdkdpCkorTlRhWDJKUVRGdDZqODF2K2hmTzVpM0l6TVUrRWd1NndNS3hlZjhPalpqRTJZRnhYTGw1aDVMYnRVUDVONzQKc1l4dUZQS2JJckFZQnREL0MrYXJweVJ6VVNZSnBjQVcraFJXbjNVUFFMSWE3RXlCWXp5U3BRdmNIaDFVZzJUcApXYVg0WjhuWm5VUjVxdDc3Zk9YMi9TZng5Y0NseWVDd0MxeWtwZkp1cXpUckw5Z1BNRDI1cjFFb1hVK3dDdUh6CjNRVTlhcUJ2ZVhoTnhaNHl3Wkc4R2FkbEJ6OUF5L1NzYm1CRjBkV1UxVzh4N1UvNGF3cnptWDl5U01UTWFVYmUKS0c4SDJZRUNnWUVBenovbWtrc0hrZENBaXBwRFRrem5vcXdKZVppempoVTBUREN0bldmNFhIbmhDN0FtMTNyMApwa2JoT0FqMERES0tPajk0cm5rN0JIbDV0K081K3ZYUXhLSFBoZW5TendIYzJrNjBwZ2dLeTBIZkpiVzZVL3RDCmJDRnlTdzlCZUlWdjQ1L1d4cDlLVFdld0xuZ3gzRDhjazAvT01wT3hyYXJwWC9oaHRVZkFIYjhDZ1lFQTlZMkcKMEt4c1p3LysyV2lxQTl6SC9QVUZRUWlaeEo5MHhrWUlYL2JCbm5iMG9tUkgvK3J0WVpzbVE3SXduUVpRQ1hhZgpOUS92Z3BCY1ZYNzJlWGNwRndtSFVKZGQxT0RIZVNrQXFnMlpIQU9weVZlYTZ0aGpWSGYrOW5vK0N5UGl5UmgrCmxsSjE0S0lHTVV5MEhqYkhHYzNFdUFtOWs1a0NkZEVhQVkrWHNzRUNnWUVBZ3dNZEtidStkRUgvRUI5R2p2ZjAKc2hQWkJZSXZkNUVWOTFnS1dHZ0NTOHRNSlV4Y3NYanJzVFU3YUdYWWlPRm1HajVIZHR2eUgvaitwZTJTZ3Yvagowbm1McTFiTnljaWVxVzU1cWorSk8wWlAzeEhMVVEyVHhyRTZCQk1IeXoxbkp0akROOW80YVVnenlweDJ3SWt3CjhqclAyWThlRWUvcUNaNEZma2gyUFJjQ2dZRUE2b2FyMXE1NE1zOWlOei94OGhKeXFEVlZPVkgvbTM0NHlBNm4KZlJCdXlPMFFwZkZsbXhaRWQwNzU4dnBEMkJYcFo4QjJPdlhuYWlwN0plVkhmNmZDQlJEQ3ZzUnppQmpRSy9adgpmZnZTMnFEZEQwS3U0ZEtldkZTSG5kNFBXQkNFVUZFbXhtZ24wYzZ1WDNQRkxINWhGMUlpcXl3U2R1QlRLemYxCndMdm14WUVDZ1lFQWd6WEVpd0hFTmF6WE9OWUp5aGJTdHBCRkp4WHhINzM0V2tjb3hHZExLUXNyS0M3UGpEYXcKaHpVUXAyK1NBcWNYUnZKdEZZeDJEN3l0bE1yZG42TXNaaWl0elRwUVZsVnFxd09RQVBsTGxGcWdLMW1XMVVOWgp2UmJNTmRRN3lCZzlKei9McTJLcVR1Z3ZoVVNkNjdTTlIvNXA5MHNvRFV4S3E4TVhZbjJEeU1FPQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
```
