### ISSUE TITLE
Grafana Single Sign On

### ISSUE THREAD

**Issue by stroebitzer** [kubermatic/kubermatic#10270]
### What happened?

I would like to use SSO via DEX on Grafana. 

This does not work out. After trying several configuration probablities I have given up.

With the current settings I can login to Grafana via Google Credentials but `Unauthorized` pop ups appear on clicking on a Dashboard. The behaviour seems to be flaky - sometimes I see a Dashboard for ~ 30 seconds.

### Expected behavior

Users of Grafana do not have to login via Grafana.

### How to reproduce the issue?

iap config in `values.yaml`
```yaml
iap:
  oidc_issuer_url: https://<DOMAIN>/dex
  deployments:
    grafana:
      name: grafana
      client_id: grafana
      client_secret: <SECRET>
      encryption_key: <SECRET>
      config: 
        scope: "groups openid email"
        email_domains:
          - '*'
        skip_auth_regex:
          - '/api/health'
        pass_user_headers: true
      upstream_service: grafana.monitoring.svc.cluster.local
      upstream_port: 3000
      ingress:
        host: "grafana.<DOMAIN>"
        annotations: {}
```

mla config ing `values.yaml`

```yaml
prometheus:
  host: prometheus.<DOMAIN>
  storageSize: '250Gi'
  tsdb:
    retentionTime: '30d'
  ruleFiles:
  - /etc/prometheus/rules/general-*.yaml
  - /etc/prometheus/rules/kubermatic-master-*.yaml
  - /etc/prometheus/rules/managed-*.yaml

alertmanager:
  host: alertmanager.<DOMAIN>

grafana:
  provisioning:
    datasources:
      prometheusServices:
        - prometheus
      lokiServices:
        - loki
    configuration:
      auto_assign_org_role: Editor
      viewers_can_edit: true
      root_url: https://grafana.<DOMAIN>
```

dex.client config in `values.yaml`

```yaml
  - id: grafana
    name: Grafana
    secret: <SECRET>
    RedirectURIs:
    - https://grafana.<DOMAIN>/oauth/callback  
```

### How is your environment configured?

- KKP version: 2.20.4
- Shared or separate master/seed clusters?: shared

### Provide your KKP manifest here (if applicable)

```yaml
apiVersion: kubermatic.k8c.io/v1
kind: KubermaticConfiguration
metadata:
  name: kubermatic
  namespace: kubermatic
spec:

  ingress:
    # Domain is the base domain where the dashboard shall be available. Even with
    # a disabled Ingress, this must always be a valid hostname.
    # this domain must match what you configured as dex.ingress.host
    # in the values.yaml
    domain: <DOMAIN>
    certificateIssuer:
      # APIGroup is the group for the resource being referenced.
      # If APIGroup is not specified, the specified Kind must be in the core API group.
      # For any other third-party types, APIGroup is required.
      apiGroup: null
      # Kind is the type of resource being referenced
      kind: ClusterIssuer
      # Name is the name of resource being referenced
      # For generating a certificate signed by a trusted root authority replace
      # with "letsencrypt-prod".
      name: "letsencrypt-prod"
    className: nginx

  # These secret keys configure the way components communicate with Dex.
  auth:
    clientID: kubermatic
    issuerClientID: kubermaticIssuer
    # When using letsencrypt-prod replace with "false"
    skipTokenIssuerTLSVerify: false
    tokenIssuer: https://<DOMAIN>/dex

    # This must match the secret configured for the kubermaticIssuer client from
    # the dex clients in values.yaml.
    # Needed if the "enableOIDCKubeconfig: true" option is used in KubermaticSetting
    issuerClientSecret: <SECRET>
    # these need to be randomly generated. Those can be generated on the
    # shell using:
    # cat /dev/urandom | tr -dc A-Za-z0-9 | head -c32
    issuerCookieKey: <SECRET>
    serviceAccountKey: <SECRET>

  versions:
    versions:
      - v1.20.13
      - v1.20.14
      - v1.21.8
      - v1.22.5
      - v1.22.10
      - v1.22.11
    default: '1.21.8'

  userCluster:
    addons:
      dockerRepository: gcr.io/student-02-kkp-admin-training/kkp-addons
      dockerTagSuffix: "v0.0.1"
  api:
    accessibleAddons:
      - cluster-autoscaler
      - my-addon    
  
```

The dex log loooks like this:

```
time="2022-07-06T10:30:16Z" level=info msg="config static client: Kubermatic"
time="2022-07-06T10:30:16Z" level=info msg="config static client: Kubermatic OIDC Issuer"
time="2022-07-06T10:30:16Z" level=info msg="config static client: Grafana"
time="2022-07-06T10:30:16Z" level=info msg="config connector: google"
time="2022-07-06T10:30:16Z" level=info msg="config connector: local passwords enabled"
time="2022-07-06T10:30:16Z" level=info msg="config response types accepted: [code token id_token]"
time="2022-07-06T10:30:16Z" level=info msg="config skipping approval screen"
time="2022-07-06T10:30:16Z" level=info msg="config signing keys expire after: 6h0m0s"
time="2022-07-06T10:30:16Z" level=info msg="config id tokens valid for: 24h0m0s"
time="2022-07-06T10:30:16Z" level=info msg="config refresh tokens rotation enabled: true"
time="2022-07-06T10:30:16Z" level=info msg="listening (telemetry) on 0.0.0.0:5558"
time="2022-07-06T10:30:16Z" level=info msg="listening (http) on 0.0.0.0:5556"
time="2022-07-06T10:31:01Z" level=info msg="login successful: connector \"google\", username=\"student-02 kkp-admin-training\", preferred_username=\"\", email=\"student-02.kkp-admin-training@loodse.training\", groups=[]"
```

### What cloud provider are you running on?

GCE

### What operating system are you running in your user cluster?

Ubuntu 20.04
