### ISSUE TITLE
Test dual-stack on Azure - Test Release 2.21

### ISSUE THREAD

**Issue by rastislavs** [kubermatic/kubermatic#10519]
Test dual-stack user clusters on the Azure cloud provider platform.
- refer to https://kubernetes.io/docs/concepts/services-networking/dual-stack/ for dual-stack feature description
- refer to https://kubernetes.io/docs/tasks/network/validate-dual-stack/ for validation options

The testing should be performed for both Canal and Cilium CNI and with both Konnectivity enabled and disabled.
The tests should be performed on all available operating systems.

## Testing Procedure
1. Deploy a dual-stack user cluster on the Azure cloud provider (either select "IPv4 and IPv6 (Dual Stack)" in KKP UI when creating a new cluster, or set cluster's `spec.clusterNetwork.ipFamily` to `IPv4+IPv6` when using the KKP API)
2. Make sure all pods are up
3. Make sure logs of pods can be retrieved via `kubecl logs`
4. Make sure pod metrics can be retrieved via `kubectl top pods`
5. Validate that worker nodes have both IPv4 and IPv6 IP addresses (`kubectl describe nodes`)
6. Validate that all pods have both IPv4 and IPv6 IP addresses (`kubectl describe pod`), and pod-to-pod communication works for both IP families
7. Create a dual-stack `ClusterIP` service targeting e.g. an nginx wbeserver pod and validate it has both IPv4 and IPv6 `ClusterIP` addresses allocated. Pods within cluster should be able to reach the backend via both IPv4 and IPv6 ClusterIP.
8. Create a dual-stack `NodePort` service targeting e.g. an nginx wbeserver pod, and validate that the backend can be reached from outside of the cluster via `<node-ip>:<nodeport>` for both IPv4 and IPv6 node IP.
9. Test that pods can reach the Internet via both IPv4 and IPv6 - you can use/inspect [this manifest](https://github.com/kubermatic/kubermatic/blob/master/pkg/test/dualstack/egress-validator-daemonset.yaml) for that

## Limitations
- Due to the limitations of the cloud-provider, the following dual-stack features do not work ATM:
  - dual-stack services of type LoadBalancer are not yet supported, so this cannot be validated.
- Some operating systems may not be well supported, in that case please document them in this issue. Ubuntu should always work.
- CentOS + Cilium is a not supported combination in general ATM

## Acceptance Criteria
The testing procedure is successful for all test cases at least for one operating system. Unsupported operating systems should be listed in this issue to generate the support matrix docs later.

**Comment by embik** [comment]
Pretty sure I found a bug, seems to be reproducible:

1. Create a dualstack Kubernetes 1.24 cluster on Azure with Ubuntu as OS and without public IPs (konnectivity is enabled; CNI is canal; proxy mode is ipvs - this is all defaults). Everything works fine after the cluster bootstrapped.
2. Create a LoadBalancer service (by default those become single stack, so no ipv6 involved). Wait for everything to start and reconcile. For example:
<details>
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: echoserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver
  namespace: echoserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echoserver
  template:
    metadata:
      labels:
        app: echoserver
    spec:
      containers:
      - image: gcr.io/google-containers/echoserver:1.8
        imagePullPolicy: Always
        name: echoserver
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: echoserver
  namespace: echoserver
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: echoserver
```
</details>
3. Observe pods losing connection to the Kubernetes API via the in-cluster service. For example the `calico-kube-controllers` Pod starts to log error like this:

```
2022-08-10 09:40:24.786 [ERROR][1] client.go 272: Error getting cluster information config ClusterInformation="default" error=Get "https://10.240.16.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default": context deadline exceeded
2022-08-10 09:40:24.786 [ERROR][1] main.go 242: Failed to verify datastore error=Get "https://10.240.16.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default": context deadline exceeded
```

Also no new pods can be created, they are stuck in `Creating` with the following event:

```
Warning  FailedCreatePodSandBox  16s   kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "cb32d48e0d3d61ffcc6ad608b5d0037ec7850bf2e1650fe4ec4d15afe1abe069": error getting ClusterInformation: Get "https://10.240.16.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default": net/http: TLS handshake timeout
```

Looks like load balancer services kill the apiserver connectivity for some reason.
