### ISSUE TITLE
Test dual-stack on kubeadm/BYO setup - Test Release 2.21

### ISSUE THREAD

**Issue by rastislavs** [kubermatic/kubermatic#10524]
Test dual-stack user clusters on the kubeadm/BYO cloud provider platform.
- refer to https://kubernetes.io/docs/concepts/services-networking/dual-stack/ for dual-stack feature description
- refer to https://kubernetes.io/docs/tasks/network/validate-dual-stack/ for validation options

The testing should be performed for both Canal and Cilium CNI and with both Konnectivity enabled and disabled.
The tests should be performed on all available operating systems.

## Testing Procedure
1. Deploy a kubeadm/BYO dual-stack user cluster in KKP
2. Prepare a VM with dual-stack connectivity to join the cluster (can be AWS EC2 instance in one of the existing `dualstack` subnets)
3. Install container runtime and kubeadm on the node (see https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/)
4. Join the KKP user cluster from the node:

  - do `kubeadm token --kubeconfig <your-kubeconfig> create --print-join-command`
  - from the output, generate yaml file with JoinConfiguration such as:
```
apiVersion: kubeadm.k8s.io/v1beta3
kind: JoinConfiguration
discovery:
  bootstrapToken:
    # change auth info below to match the actual api server endpoint, token and CA certificate hash for your cluster
    apiServerEndpoint: fghk7gd5tx.europe-west3-c.dev.kubermatic.io:30038
    token: "9xwn14.ktdfg3s3fqyj0dr9"
    caCertHashes:
    - "sha256:b36ebfbcf51e019e6c763dd95bbc307ee4e96e9534d3133a65cf185c0dd74551"
nodeRegistration:
  kubeletExtraArgs:
    # change the node-ip below to match your desired IPv4 and IPv6 addresses of the node
    node-ip: 10.0.6.114,2a05:d014:937:4500:a324:767b:38da:2bff
```
  - run sudo kubeadm join --config kubeadm-join-config.yaml

5. Make sure all pods are up
6. Make sure logs of pods can be retrieved via `kubecl logs`
7. Make sure pod metrics can be retrieved via `kubectl top pods`
8. Validate that worker node havs both IPv4 and IPv6 IP addresses (`kubectl describe nodes`)
9. Validate that all pods have both IPv4 and IPv6 IP addresses (`kubectl describe pod`), and pod-to-pod communication works for both IP families
10. Create a dual-stack `ClusterIP` service targeting e.g. an nginx wbeserver pod and validate it has both IPv4 and IPv6 `ClusterIP` addresses allocated. Pods within cluster should be able to reach the backend via both IPv4 and IPv6 ClusterIP.
11. Create a dual-stack `NodePort` service targeting e.g. an nginx wbeserver pod, and validate that the backend can be reached from outside of the cluster via `<node-ip>:<nodeport>` for both IPv4 and IPv6 node IP.
12. Test that pods can reach the Internet via both IPv4 and IPv6 - you can use/inspect [this manifest](https://github.com/kubermatic/kubermatic/blob/master/pkg/test/dualstack/egress-validator-daemonset.yaml) for that

## Limitations
- Due to the limitations of the cloud-provider, the following dual-stack features do not work ATM:
  - dual-stack services of type LoadBalancer are not yet supported, so this cannot be validated.
- Some operating systems may not be well supported, in that case please document them in this issue. Ubuntu should always work.
- CentOS + Cilium is a not supported combination in general ATM

## Acceptance Criteria
The testing procedure is successful for all test cases at least for one operating system. Unsupported operating systems should be listed in this issue to generate the support matrix docs later.
