### ISSUE TITLE
Test custom audit log sidecar configuration - Test Release 2.21

### ISSUE THREAD

**Issue by embik** [kubermatic/kubermatic#10599]
KKP 2.21 adds the ability to configure the fluentbit sidecar we use when enabling audit logging, e.g. to further filter audit logs or send them to an upstream location (e.g. a corporate security logging service).

Documentation for the feature can be found [here](https://docs.kubermatic.com/kubermatic/master/tutorials_howtos/audit_logging/#custom-output-configuration).

## Test Procedure

1. Create a cluster with enabled audit logging (can also pick an audit logging preset like "minimal").
2. Follow the [documentation](https://docs.kubermatic.com/kubermatic/master/tutorials_howtos/audit_logging/#custom-output-configuration) and configure a couple of filters, for example enriching the audit logs with the cluster ID:

```yaml
# snippet, needs to be added to spec.auditLogging.sidecar and <CLUSTER ID> needs to be replaced with the actual ID
filters:
  - Name: record_modifier
    Match: *
    Record: cluster <CLUSTER ID>
```
3. Tail `audit-logs` sidecar in kube-apiserver Pods and make sure the new information is added correctly to logs being written to standard out (should have two fields, "log" and "cluster", after this).
4. Set up a central fluentd service somewhere in the KKP seed, roughly following the suggestions made in the KKP docs, that is set up as a forward logging sink. The [fluentbit docs](https://docs.fluentbit.io/manual/pipeline/outputs/forward). have extensive information on how to configure both sides to make it work. fluentd could probably just write to standard out for testing purposes.
5. Point fluentbit configuration to that centralised fluentd service via an output plugin.
6. Verify that audit logs from one or multiple clusters that are configured accordingly show up on fluentd.

Feel free to further play around with settings here.

## Acceptance Criteria

Audit logs are properly forwarded and/or modified according to configuration changes made.

**Comment by hbernardo** [comment]
The only issue I found is that, by default, all egress from deployment "apiserver" (which runs the fluentbit sidecar container) are denied by Network Policy (NetworkPolicy `default-deny-all-egress` automatically deployed to the cluster namespaces). E.g.:
```bash
> kubectl get NetworkPolicy default-deny-all-egress -n cluster-zgvlnscggn
NAME                      POD-SELECTOR    AGE
default-deny-all-egress   app=apiserver   18m
```
So, by default, the "Output" feature was not working (i.e. wasn't able to connect to my fluentd app running in the same cluster/namespace). 
It took me time to realize that I would need to create a specific egress NetworkPolicy to allow it:
```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: fluentd-allow
  namespace: cluster-zgvlnscggn
spec:
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: fluentd
  podSelector:
    matchLabels:
      app: apiserver
  policyTypes:
  - Egress
```
Maybe this should be documented.
