### ISSUE TITLE
Support for disabling Kubernetes dashboard - Test Release 2.21

### ISSUE THREAD

**Issue by ahmedwaleedmalik** [kubermatic/kubermatic#10610]
# Instructions

- Create a cluster on any cloud provider
- Ensure that Kubernetes dashboard is accessible and running
- Now disable Kubernetes dashboard from the cluster spec
```yaml
kind: Cluster
metadata:
  name: xhxfffvls5
spec:
...
  containerRuntime: containerd
  enableOperatingSystemManager: false
  enableUserSSHKeyAgent: true
  humanReadableName: musing-heisenberg
  kubernetesDashboard:
    enabled: false
...
```
- Ensure that all of its resources are removed.
- Now create a cluster with Kubernetes dashboard disabled
- Enable it after cluster creation
- Ensure that it works as expected

# References

- https://github.com/kubermatic/kubermatic/issues/9510
- https://github.com/kubermatic/kubermatic/pull/9511
