### ISSUE TITLE
Azure LB times out if target port equals(?) service port

### ISSUE THREAD

**Issue by embik** [kubermatic/kubermatic#10647]
### What happened?

I tried setting up nginx-ingress-controller on an Azure cluster and was not able to access it via the LoadBalancer service IP. After a lot of head scratching, I found that the problem appears to be the ports section on the `Service` object. Here's a snippet:

```yaml
ports:
  - appProtocol: http
     name: http
     nodePort: 31273
     port: 80
     protocol: TCP
     targetPort: http
```

As you can see, the port equals the target port (`http` is mapped to port 80 on the Pod). When that is the case, it seems that the service is not available via the Azure LB (curl just does not come back, so no output to share). 

### Expected behavior

It is possible to access a service of type `LoadBalancer` via its Azure LB IP.

### How to reproduce the issue?

Create an Azure cluster. Both `basic` and `standard` LB SKUs seem to have this problem. For networking I did not change anything from the defaults, so it's running Canal v3.23 and `ipvs` proxy mode.

I prepared two versions of an echoserver deployment, one that works, one that doesn't:

This works:

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: echoserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver
  namespace: echoserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echoserver
  template:
    metadata:
      labels:
        app: echoserver
    spec:
      containers:
      - image: gcr.io/google-containers/echoserver:1.8
        imagePullPolicy: Always
        name: echoserver
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: echoserver
  namespace: echoserver
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: echoserver
```

Here's the response to the LB IP:

```sh
$ curl 20.31.90.xx

Hostname: echoserver-5f477b7c6-fm7rb
[...]
```

**This does not:** 

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: echoserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver
  namespace: echoserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echoserver
  template:
    metadata:
      labels:
        app: echoserver
    spec:
      containers:
      - image: gcr.io/google-containers/echoserver:1.8
        imagePullPolicy: Always
        name: echoserver
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: echoserver
  namespace: echoserver
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: echoserver
```

This results in no response / a timeout:

```sh
$ curl --connect-timeout 5 20.31.90.xx
curl: (28) Connection timeout after 5005 ms
```

### How is your environment configured?

- KKP version: `master`
- Shared or separate master/seed clusters?: shared

### Provide your KKP manifest here (if applicable)

<details>

See reproduce section.

</details>

### What cloud provider are you running on?

Azure

### What operating system are you running in your user cluster?

Ubuntu 20.04

### Additional information

I haven't tried this with other OSes yet, looking into it.
