### ISSUE TITLE
Dual-stack on Hetzner with OSM: nodes missing IPv6 addresses

### ISSUE THREAD

**Issue by rastislavs** [kubermatic/kubermatic#10640]
### What happened?
In a dual-stack user cluster deployed in Hetzner with OSM enabled, nodes are missing their IPv6 addresses on the main network interface. This prevents CNI to start in dual-stack mode. The allocated IPv6 addresses are however successfully published to k8s node objects by hetzner CCM, they are just not configured properly on the nodes.

Comparison with a working (non-OSM-based) dual-stack clusters shows that in working case, static IPv6 interface config is done by cloud-config in the `/etc/netplan/50-cloud-init.yaml` file, which is missing in OSM case:

```
network:
    version: 2
    ethernets:
        eth0:
            addresses:
            - 2a01:4f8:c012:49c9::1/64
            dhcp4: true
            gateway6: fe80::1
            match:
                macaddress: 96:00:01:73:6e:13
            nameservers:
                addresses:
                - 2a01:4ff:ff00::add:2
                - 2a01:4ff:ff00::add:1
            set-name: eth0
```
**Root cause:**
From the cloud-init logs, it shows that cloud-init is running twice while configuring the network internally which is leading to overwriting of correctly configured interfaces.In compare to non-osm case, here it is taking longer time.
### Expected behavior
Each node in a dual-stack cluster should have both IPv4 and IPv6 address assigned on its main network interface.

### How to reproduce the issue?

Deploy a user-cluster in Hetzner with OSM enabled.

### How is your environment configured?

- KKP version: master

### What cloud provider are you running on?
Hetzner

### What operating system are you running in your user cluster?
Ubuntu 20.04
