### ISSUE TITLE
Create reference for Application CRDs for docs

### ISSUE THREAD

**Issue by SimonTheLeg** [kubermatic/kubermatic#10684]
For our documentation it makes sense to create a Reference for the ApplicationDefinition and -Installation.

So far I have tried to create this using our doc-codegen (https://github.com/kubermatic/kubermatic/blob/d8311a629fe5ed15ffe932a9f8c53b584ce2db14/codegen/example-yaml/main.go#L1) our that we use in other places (e.g. Seed cluster)

However when it does not seem to properly work, when you supply a slice with more than one object.

For example when supplying this

```go
func createExampleApplicationDefinition() *appskubermaticv1.ApplicationDefinition {
	appDef := &appskubermaticv1.ApplicationDefinition{
		TypeMeta: metav1.TypeMeta{
			APIVersion: appskubermaticv1.SchemeGroupVersion.String(),
			Kind:       appskubermaticv1.ApplicationDefinitionKindName,
		},
		ObjectMeta: metav1.ObjectMeta{
			Name: "<<appdef-name>>",
		},
		Spec: appskubermaticv1.ApplicationDefinitionSpec{
			Description: "",
			Method:      appskubermaticv1.HelmTemplateMethod,
			Versions: []appskubermaticv1.ApplicationVersion{
				{
					Version: "v1.2.0-helm",
					Template: appskubermaticv1.ApplicationTemplate{
						Source: appskubermaticv1.ApplicationSource{
							Helm: &appskubermaticv1.HelmSource{
								URL:          "https://charts.example.com",
								ChartName:    "my-app",
								ChartVersion: "v13.9.0",
								Credentials:  &appskubermaticv1.HelmCredentials{},
							},
						},
					},
				},
				{
					Version: "v1.2.0-git",
					Template: appskubermaticv1.ApplicationTemplate{
						Source: appskubermaticv1.ApplicationSource{
							Git: &appskubermaticv1.GitSource{
								Remote: "https://git.example.com/repo || git@example.com/repo",
							},
						},
					},
				},
			},
		},
	}

	return appDef
}
```

It just generates the annotations for the first item of the slice, but not for the second one:

```yaml
apiVersion: apps.kubermatic.k8c.io/v1
kind: ApplicationDefinitions
metadata:
  name: <<appdef-name>>
spec:
  # Description of the application. what is its purpose
  description: ""
  # Method used to install the application
  method: helm
  # Available versions for this application
  versions:
    - # Template defines how application is installed (source provenance, Method...)
      template:
        # Defined how the source of the application (e.g Helm chart) is retrieved
        source:
          # Install Application from a Helm repository
          helm:
            # Name of the Chart
            chartName: my-app
            # Version of the Chart
            chartVersion: v13.9.0
            # Credentials hold the ref to the secret with helm credentials
            credentials: {}
            # URl of the helm repository.
            # It can be an HTTP(s) repository (e.g. https://localhost/myrepo) or on OCI repository (e.g. oci://localhost:5000/myrepo).
            url: https://charts.example.com
      # Version of the application (e.g. v1.2.3)
      version: v1.2.0-helm
    - template:
        source:
          git:
            ref: {}
            remote: https://git.example.com/repo || git@example.com/repo
      version: v1.2.0-git
```

Within this ticket it is free to either look into the bug in codegen or explore other options to generate a reference out of a CRD
