### ISSUE TITLE
Namespace-specific allowed selector conflicts with clusterDefaultNodeSelector (Admission Plugin: PodNodeSelector)

### ISSUE THREAD

**Issue by dermorz** [kubermatic/kubermatic#10698]
### What happened?

After creating a cluster with the [Admission Plugin: PodNodeSelector][] enabled and defining a configuration with a `clusterDefaultNodeSelector` and a namespace-specific allowed selector, I cannot create a pod with this whitelisted nodeSelector, but get a conflict:
`Error from server (Forbidden): error when creating "manifests.yml": pods "nginx" is forbidden: pod node label selector conflicts with its namespace node label selector`

[Admission Plugin: PodNodeSelector]: https://docs.kubermatic.com/kubermatic/master/tutorials-howtos/admission-plugins/#podnodeselector-configuration

### Expected behavior

With the Admission Plugin configured as shown below, I should be able create a pod with a matching nodeSelector that gets scheduled correctly on a node with the matching label. 
![image](https://user-images.githubusercontent.com/682686/183589942-fe1a0628-1545-4723-ac77-6c0cba7d3bc5.png)

### How to reproduce the issue?

1. Create a cluster with the Admission Plugin configuration above.
2. Label at least one of the cluster nodes with `env=prod`.
3. Apply this pod manifest:
    ```yaml
    apiVersion: v1
    kind: Pod
    metadata:
      name: "nginx"
      namespace: production
      labels:
        app: "nginx"
    spec:
      containers:
      - name: myapp
        image: "nginx:latest"
      restartPolicy: Always
      nodeSelector:
        env: prod
    ```
4. `Error from server (Forbidden): error when creating "manifests.yml": pods "nginx" is forbidden: pod node label selector conflicts with its namespace node label selector`

### How is your environment configured?

- KKP version: `v2.21.0-alpha.1`

### Additional information

The explicit `nodeSelector` in the pod spec should not even be necessary because the it should be injected by the admission controller. (See #10697) These 2 issues seem to be closely related and might have he same root cause. The``clusterDefaultNodeSelector` seems to be working correctly, but not setting/whitelisting nodeSelectors for specific namespaces.

**Comment by hdurand0710** [comment]
It's working fine for me.

Maybe you missed the step to annotate the `production` namespace, as I don't see it documented in the `How to reproduce the issue` section.

The `production` namespace has to be annotated with:
`scheduler.alpha.kubernetes.io/node-selector: env=prod`

I apply this deployment:

```
apiVersion: apps/v1
kind: Deployment
metadata:
    name: my-nginx-deploy
    labels:
        app: nginx
spec:
    replicas: 3
    selector:
        matchLabels:
            app: nginx
    template:
        metadata:
            labels:
                app: nginx
        spec:
            containers:
            - name: test-nginx
              image: nginx:alpine
              ports:
              - containerPort: 80
```

to this namespace:

```
k get ns ln-prod -o yaml
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    scheduler.alpha.kubernetes.io/node-selector: env=lnprod
  creationTimestamp: "2022-08-16T12:43:26Z"
  labels:
    kubernetes.io/metadata.name: ln-prod
  name: ln-prod
  resourceVersion: "18663"
  uid: 7fdb2cbc-b6cd-4d33-991e-1e9614eb7c1f
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
```

The nginx pods are created with 
```
   nodeSelector:
      env: lnprod
```
and the pods correctly scheduled on the 1 node that has the label `env=lnprod`
