### ISSUE TITLE
NodeSelector is not injected into Pods in defined Namespace (Admission Plugin: PodNodeSelector)

### ISSUE THREAD

**Issue by dermorz** [kubermatic/kubermatic#10697]
### What happened?

After creating a cluster with the [Admission Plugin: PodNodeSelector][] enabled and defining a simple configuration to inject a NodeSelector to all pods of a specified Namespace, I noticed that a created pod could be scheduled on nodes without the defined label.

[Admission Plugin: PodNodeSelector]: https://docs.kubermatic.com/kubermatic/master/tutorials-howtos/admission-plugins/#podnodeselector-configuration

### Expected behavior

On a cluster with the following Admission Plugin configuration, Pods in the namespace `development` are only scheduled on nodes labeled `env=dev`.

![image](https://user-images.githubusercontent.com/682686/183581681-289eb5e5-79f4-4f14-a1ec-aa87650a1f21.png)

### How to reproduce the issue?

1. Create a cluster with the Admission Plugin configuration above.
2. Create the namespace `development` on this cluster.
3. Create a pod in this namespace:
    ```yaml
    apiVersion: v1
    kind: Pod
    metadata:
      name: "nginx"
      namespace: development
      labels:
        app: "nginx"
    spec:
      containers:
      - name: myapp
        image: "nginx:latest"
      restartPolicy: Always
    ```
4. The pod gets scheduled on an available node without the label `env=dev`

### How is your environment configured?

- KKP version: `v2.21.0-alpha.1`

### What cloud provider are you running on?

KubeVirt, but it's reproducible with others.
