### ISSUE TITLE
EAR enabled with invalid encryption key gets stuck in Pending state

### ISSUE THREAD

**Issue by PratikDeoghare** [kubermatic/kubermatic#10829]
If we enable EAR with an invalid value for encryption key say "password" then it gets in Pending state. 

In Pending state any changes are rejected. 

We should check for this invalid key earlier to avoid this situation. 

To reproduce: 

`kubectl  --type merge --patch-file patch.yaml` 

patch.yaml
```
spec:
  encryptionConfiguration:
    enabled: true
    resources:
      - secrets
    secretbox:
      keys:
        - name: encryption-key-2022-01
          value: password
```
