### ISSUE TITLE
`kubermatic-standard` preset is not working

### ISSUE THREAD

**Issue by hdurand0710** [kubermatic/kubermatic#10911]
### What happened?
When selecting the `kubermatic-standard` preset, it's not applied to the `VirtualMachineInstance`.

The reason is even described in our documentation:
https://docs.kubermatic.com/kubermatic/master/architecture/supported-providers/kubevirt/kubevirt/#virtual-machines-templates

Our `kubermatic-standard` VirtualMachineInstancePreset is:
```
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstancePreset
metadata:
  name: kubermatic-standard
  namespace: ln
spec:
  domain:
    devices: {}
    resources:
      limits:
        cpu: "2"
        memory: 8Gi
      requests:
        cpu: "2"
        memory: 8Gi
  selector:
    matchLabels:
      kubevirt.io/flavor: kubermatic-standard
```

Unfortunately, the `domain.resource` is not merged.
The VMI is not annotated with the `virtualmachinepreset.kubevirt.io/kubermatic-standard: kubevirt.io/v1` , which is true, the preset in not applied.

This preset is then useless and even misleading.

### Expected behavior
We can apply a `kubermatic-standard` VirtualMachineInstancePreset.

### How is your environment configured?

- KKP version: 2.21.0
- Shared or separate master/seed clusters?: same

### Provide your KKP manifest here (if applicable)

<details>

```yaml
# paste manifest here
```

</details>

### What cloud provider are you running on?

KubeVirt

### What operating system are you running in your user cluster?

same for all
