### ISSUE TITLE
Prometheus Alerts for Storage are outdated

### ISSUE THREAD

**Issue by toschneck** [kubermatic/kubermatic#10965]
I recently compared our current alerts with the alerts managed by the community of https://github.com/kubernetes-monitoring/kubernetes-mixin and it seams they changed the used metrics and alerts quite a bit. They also added a alerts if PVCs are stuck in some pending state what could be helpful for ops. 

Current rules:
https://github.com/kubermatic/kubermatic/blob/87074a55c404f220777abd9e302887316d5aa2f5/charts/monitoring/prometheus/rules/general-kube-kubelet.yaml#L29
```yaml
      - alert: KubePersistentVolumeUsageCritical
        annotations:
          message: The PersistentVolume claimed by {{ $labels.persistentvolumeclaim }} in namespace {{ $labels.namespace }} is only {{ printf "%0.0f" $value }}% free.
          runbook_url: https://docs.kubermatic.com/kubermatic/master/cheat-sheets/alerting-runbook/#alert-kubepersistentvolumeusagecritical
        expr: |
          100 * kubelet_volume_stats_available_bytes{job="kubelet"}
            /
          kubelet_volume_stats_capacity_bytes{job="kubelet"}
            < 3
        for: 1m
        labels:
          severity: critical
          service: kubelet
          resource: "{{ $labels.namespace }}/{{ $labels.persistentvolumeclaim }}"
      - alert: KubePersistentVolumeFullInFourDays
        annotations:
          message: Based on recent sampling, the PersistentVolume claimed by {{ $labels.persistentvolumeclaim }} in namespace {{ $labels.namespace }} is expected to fill up within four days. Currently {{ $value }} bytes are available.
          runbook_url: https://docs.kubermatic.com/kubermatic/master/cheat-sheets/alerting-runbook/#alert-kubepersistentvolumefullinfourdays
        expr: |
          (
            kubelet_volume_stats_used_bytes{job="kubelet"}
              /
            kubelet_volume_stats_capacity_bytes{job="kubelet"}
          ) > 0.85
          and
          predict_linear(kubelet_volume_stats_available_bytes{job="kubelet"}[6h], 4 * 24 * 3600) < 0
        for: 5m
        labels:
          severity: critical
          service: kubelet
          resource: "{{ $labels.namespace }}/{{ $labels.persistentvolumeclaim }}"
```

Jsonnet ruleset of kubernetes-mixin:
https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/master/alerts/storage_alerts.libsonnet

After I looked up at , the following rendered alerting rules, seams to work (adjusted from 3% left to 5%)

```yaml
- "name": "kubernetes-storage"
  "rules":
    - "alert": "KubePersistentVolumeFillingUp"
      "annotations":
        "description": "The PersistentVolume claimed by {{ $labels.persistentvolumeclaim }} in Namespace {{ $labels.namespace }} is only {{ $value | humanizePercentage }} free."
        "runbook_url": "https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubepersistentvolumefillingup"
        "summary": "PersistentVolume is filling up."
      "expr": |
        (
          kubelet_volume_stats_available_bytes{job="kubelet"}
            /
          kubelet_volume_stats_capacity_bytes{job="kubelet"}
        ) < 0.05
        and
        kubelet_volume_stats_used_bytes{job="kubelet"} > 0
        unless on(namespace, persistentvolumeclaim)
        kube_persistentvolumeclaim_access_mode{ access_mode="ReadOnlyMany"} == 1
        unless on(namespace, persistentvolumeclaim)
        kube_persistentvolumeclaim_labels{label_excluded_from_alerts="true"} == 1
      "for": "1m"
      "labels":
        "severity": "critical"
    - "alert": "KubePersistentVolumeFillingUp"
      "annotations":
        "description": "Based on recent sampling, the PersistentVolume claimed by {{ $labels.persistentvolumeclaim }} in Namespace {{ $labels.namespace }} is expected to fill up within four days. Currently {{ $value | humanizePercentage }} is available."
        "runbook_url": "https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubepersistentvolumefillingup"
        "summary": "PersistentVolume is filling up."
      "expr": |
        (
          kubelet_volume_stats_available_bytes{job="kubelet"}
            /
          kubelet_volume_stats_capacity_bytes{job="kubelet"}
        ) < 0.15
        and
        kubelet_volume_stats_used_bytes{job="kubelet"} > 0
        and
        predict_linear(kubelet_volume_stats_available_bytes{job="kubelet"}[6h], 4 * 24 * 3600) < 0
        unless on(namespace, persistentvolumeclaim)
        kube_persistentvolumeclaim_access_mode{ access_mode="ReadOnlyMany"} == 1
        unless on(namespace, persistentvolumeclaim)
        kube_persistentvolumeclaim_labels{label_excluded_from_alerts="true"} == 1
      "for": "1h"
      "labels":
        "severity": "warning"
    - "alert": "KubePersistentVolumeInodesFillingUp"
      "annotations":
        "description": "The PersistentVolume claimed by {{ $labels.persistentvolumeclaim }} in Namespace {{ $labels.namespace }} only has {{ $value | humanizePercentage }} free inodes."
        "runbook_url": "https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubepersistentvolumeinodesfillingup"
        "summary": "PersistentVolumeInodes are filling up."
      "expr": |
        (
          kubelet_volume_stats_inodes_free{job="kubelet"}
            /
          kubelet_volume_stats_inodes{job="kubelet"}
        ) < 0.03
        and
        kubelet_volume_stats_inodes_used{job="kubelet"} > 0
        unless on(namespace, persistentvolumeclaim)
        kube_persistentvolumeclaim_access_mode{ access_mode="ReadOnlyMany"} == 1
        unless on(namespace, persistentvolumeclaim)
        kube_persistentvolumeclaim_labels{label_excluded_from_alerts="true"} == 1
      "for": "1m"
      "labels":
        "severity": "critical"
    - "alert": "KubePersistentVolumeInodesFillingUp"
      "annotations":
        "description": "Based on recent sampling, the PersistentVolume claimed by {{ $labels.persistentvolumeclaim }} in Namespace {{ $labels.namespace }} is expected to run out of inodes within four days. Currently {{ $value | humanizePercentage }} of its inodes are free."
        "runbook_url": "https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubepersistentvolumeinodesfillingup"
        "summary": "PersistentVolumeInodes are filling up."
      "expr": |
        (
          kubelet_volume_stats_inodes_free{job="kubelet"}
            /
          kubelet_volume_stats_inodes{job="kubelet"}
        ) < 0.15
        and
        kubelet_volume_stats_inodes_used{job="kubelet"} > 0
        and
        predict_linear(kubelet_volume_stats_inodes_free{job="kubelet"}[6h], 4 * 24 * 3600) < 0
        unless on(namespace, persistentvolumeclaim)
        kube_persistentvolumeclaim_access_mode{ access_mode="ReadOnlyMany"} == 1
        unless on(namespace, persistentvolumeclaim)
        kube_persistentvolumeclaim_labels{label_excluded_from_alerts="true"} == 1
      "for": "1h"
      "labels":
        "severity": "warning"
    - "alert": "KubePersistentVolumeErrors"
      "annotations":
        "description": "The persistent volume {{ $labels.persistentvolume }} has status {{ $labels.phase }}."
        "runbook_url": "https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubepersistentvolumeerrors"
        "summary": "PersistentVolume is having issues with provisioning."
      "expr": |
        kube_persistentvolume_status_phase{phase=~"Failed|Pending",job="kube-state-metrics"} > 0
      "for": "5m"
      "labels":
        "severity": "critical"
```

Potential we should also add 2 steps of alerts:
1. Warning at 7%
2. Critical at  5%
