### ISSUE TITLE
usercluster-controller should not depend on optional field in status

### ISSUE THREAD

**Issue by judge-red** [kubermatic/kubermatic#11018]
### What happened?

usercluster-controller fails with `-owner-email must be set` if `.status.userEmail` is not provided.

Here's the full log output from start to crash:
```
$ k -n cluster-foobar logs usercluster-controller-f7bf694b4-rb4km
Defaulted container "usercluster-controller" out of: usercluster-controller, copy-http-prober (init)
{"level":"info","time":"2022-09-21T10:20:01.386Z","logger":"http-prober","caller":"http-prober/main.go:127","msg":"Probing","attempt":1,"max-attempts":100,"target":"https://apiserver-external.cluster-foobar.svc.cluster.local./healthz"}
{"level":"info","time":"2022-09-21T10:20:01.400Z","logger":"http-prober","caller":"http-prober/main.go:116","msg":"Hostname resolved","hostname":"apiserver-external.cluster-foobar.svc.cluster.local.","address":"10.101.73.175:443"}
{"level":"info","time":"2022-09-21T10:20:01.409Z","logger":"http-prober","caller":"http-prober/main.go:140","msg":"Endpoint is available"}
{"level":"info","time":"2022-09-21T10:20:01.614Z","caller":"cli/hello.go:36","msg":"Starting Kubermatic User-Cluster Controller-Manager (Enterprise Edition)...","version":"v2.20.6"}
{"level":"fatal","time":"2022-09-21T10:20:01.614Z","caller":"user-cluster-controller-manager/main.go:160","msg":"-owner-email must be set"}
```

### Expected behavior

1) if this email is really required, then `.status.userEmail` should be required in the Cluster CRD.
2) no `.status` field should be required, i.e. there should be an email field somewhere in `.spec` or such

### How to reproduce the issue?

Create a Cluster manually (i.e. not through the wizard) and don't set `.status.userEmail`

### How is your environment configured?

- KKP version: 2.20.6
- Shared or separate master/seed clusters?: shared

### Provide your KKP manifest here (if applicable)

I don't think it matters, so I'll skip this. But maybe the Cluster manifest is helpful, so I'll provide that instead.

<details>

```yaml
apiVersion: kubermatic.k8c.io/v1
kind: Cluster
metadata:
  labels:
    project-id: zg8sh8vz78
  name: foobar
spec:
  cloud:
    dc: openstack-switch-ZH
    openstack:
      credentialsReference:
        name: credential-openstack-hkqrvtbnhk
        namespace: kubermatic
      floatingIPPool: public
      # network: kubernetes-hkqrvtbnhk
      network: ""
      nodePortsAllowedIPRange: 0.0.0.0/0
      routerID: ""
      securityGroups: ""
      subnetID: ""
    providerName: openstack
  clusterNetwork:
    dnsDomain: cluster.local
    konnectivityEnabled: true
    nodeLocalDNSCacheEnabled: true
    pods:
      cidrBlocks:
      - 172.25.0.0/16
    proxyMode: ipvs
    services:
      cidrBlocks:
      - 10.240.16.0/20
  cniPlugin:
    type: canal
    version: v3.22
  containerRuntime: containerd
  enableUserSSHKeyAgent: true
  exposeStrategy: LoadBalancer
  features:
    apiserverNetworkPolicy: true
    ccmClusterName: true
    externalCloudProvider: true
  humanReadableName: expose-strategy-test
  opaIntegration:
    webhookTimeoutSeconds: 10
  pause: false
  version: 1.23.6
```

</details>

(The purpose of creating a Cluster manually was to test out the `LoadBalancer` expose strategy with a single cluster, hence also the naming.)

### What cloud provider are you running on?

OpenStack

### What operating system are you running in your user cluster?

Flatcar
