### ISSUE TITLE
KubeVirt: resource Quota filtering wrongly filters out some VirutalMachineInstancePresets.

### ISSUE THREAD

**Issue by hdurand0710** [kubermatic/kubermatic#11044]
### What happened?
The `dedicated-cpu` Preset in filtered out by the quota filtering mechanism. It should not.

Error log :
`2022-09-23T08:24:16.810+0200	error	provider/kubevirt.go:309	skipping VMIPreset:dedicated-cpu, fetching presetResourceDetails failed:should not specify both spec.domain.cpu and spec.domain.resources.[requests/limits].cpu in VMIPreset`

### Expected behavior

It should not be filtered out.

### How is your environment configured?

- KKP version:
- Shared or separate master/seed clusters?:

### VirtualMachineInstancePreset manifest

<details>

```yaml
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstancePreset
metadata:
  name: dedicated-cpu
  namespace: default
spec:
  domain:
    ioThreadsPolicy: auto
    cpu:
      dedicatedCpuPlacement: true
      isolateEmulatorThread: true
    devices: {}
    resources:
      requests:
        cpu: 4
        memory: 16Gi
  selector:
    matchLabels:
      kubevirt.io/flavor: dedicated-cpu

```

</details>

### What cloud provider are you running on?

KubeVirt

### What operating system are you running in your user cluster?

not important.
