### ISSUE TITLE
Failed to reconcile cluster: failed to add finalizers

### ISSUE THREAD

**Issue by talhalatiforakzai** [kubermatic/kubermatic#11064]
### What happened?

When I create a user cluster, the user cluster is provisioned with `failed to add finalizers` events, however upon inspecting the cluster I see that the finalizers are added to the cluster, this happens on almost all the cloud providers I use to provision the clusters, is there some way that this race condition can be avoided, or this is expected behavior. 

```
failed to reconcile cluster: failed to add finalizers [kubermatic.k8c.io/cleanup-etcdbackupconfigs] to Cluster /g8l52cvjbb: Operation cannot be fulfilled on clusters.kubermatic.k8c.io "g8l52cvjbb": the object has been modified; please apply your changes to the latest version and try again

failed to ensure cluster namespace: failed to set "kubermatic.k8c.io/cleanup-namespace" finalizer: failed to add finalizers [kubermatic.k8c.io/cleanup-namespace] to Cluster /g8l52cvjbb: Operation cannot be fulfilled on clusters.kubermatic.k8c.io "g8l52cvjbb": the object has been modified; please apply your changes to the latest version and try again
```
```
apiVersion: kubermatic.k8c.io/v1
kind: Cluster
metadata:
  annotations:
    kubermatic.k8c.io/migrated-aws-node-termination-handler-addon: 'yes'
    presetName: kubermatic-com
  creationTimestamp: '2022-09-26T08:42:37Z'
  finalizers:
    - kubermatic.k8c.io/alertmanager
    - kubermatic.k8c.io/cleanup-credentials-secrets
    - kubermatic.k8c.io/cleanup-etcdbackupconfigs
    - kubermatic.k8c.io/cleanup-gcp-firewall-icmp
    - kubermatic.k8c.io/cleanup-gcp-firewall-nodeport
    - kubermatic.k8c.io/cleanup-gcp-firewall-self
    - kubermatic.k8c.io/cleanup-gcp-routes
    - kubermatic.k8c.io/cleanup-kubermatic-constraints
    - kubermatic.k8c.io/cleanup-namespace
    - kubermatic.k8c.io/cleanup-usersshkeys-cluster-ids
    - kubermatic.k8c.io/delete-nodes
    - kubermatic.k8c.io/mla
```
--

### Expected behavior

User cluster provisioned with no events related to the finalizers. 

### How to reproduce the issue?

created a user cluster on any AWS/GCP.

### How is your environment configured?

- KKP version: 2.21.0
- Shared or separate master/seed clusters?: Shared master/seed cluster

### What cloud provider are you running on?

AWS,GCP

### What operating system are you running in your user cluster?

Ubuntu 20.04
