### ISSUE TITLE
Allow for range / prefix exclusions in IPAMPool

### ISSUE THREAD

**Issue by rastislavs** [kubermatic/kubermatic#11260]
### Description of the feature you would like to add / User story

As a KKP cluster administrator,
I would like to configure range/prefix exclusions in IPAMPools,
in order to exclude particular IPs/subnets of IPAMPool (e.g. dedicated for special services) from IPAM allocations.

### Solution details
Extend the existing IPAMPool API to allow specifying `excludeRanges` for `type: range` pools and `excludePrefixes` for `type: prefix` pools, e.g.:

```yaml
apiVersion: kubermatic.k8c.io/v1
kind: IPAMPool
metadata:
  name: metallb
spec:
  datacenters:
    azure-westeurope:
      type: range
      poolCidr: "192.168.1.0/26"
      excludeRanges:
      - 192.168.1.100-192.168.1.110
      - 192.168.1.255
      allocationRange: 8
    aws-eu-central-1a:
      type: prefix
      poolCidr: "192.168.1.0/26"
      allocationPrefix: 30
      excludePrefixes:
      # NOTE: must be the same length as allocationPrefix
      - 192.168.1.100/30
      - 192.168.1.255/30
```
