### ISSUE TITLE
Duplicate entries of LoadBalancerSourceRanges in front-loadbalancer

### ISSUE THREAD

**Issue by sachintiptur** [kubermatic/kubermatic#11307]
### What happened?
Duplicate entries of IPs are being appended to LoadBalancerSourceRanges of front-loadbalancer service.

### Expected behavior
Only unique entries should be present.

### How to reproduce the issue?
Create a user cluster with LoadBalancer expose strategy.

### How is your environment configured?

- KKP version: v.2.21
- Shared or separate master/seed clusters?:

### Provide your KKP manifest here (if applicable)

<details>

```yaml
# snip of cluster yaml
exposeStrategy: LoadBalancer
  apiServerAllowedIPRanges:
    cidrBlocks:
    - 192.168.1.0/32
 
```

</details>

### What cloud provider are you running on?
AWS
