### ISSUE TITLE
Seed CRD requires some fields that are not actually required (and were not required in the old CRD)

### ISSUE THREAD

**Issue by judge-red** [kubermatic/kubermatic#11593]
### What happened?

During the big migration, the Seed CRD started to require some fields that are not actually required (i.e. their values can be set to empty strings/lists/etc.) and were not required before the migration.

### Expected behavior

Only require fields that are actually required

### How to reproduce the issue?

In `.spec.datacenters.$DC` (copy-pasting from our `seed.yaml`):
```
                    # The attributes below are required...but their values are not. Weird.
                    availabilityZone: ""
                    dnsServers: []
                    nodeSizeRequirements:
                        minimumMemory: 0
                        minimumVCPUs: 0
```

Leaving any of these away will result in an error. But as you can see, they don't really need to be specified - this way the defaults (where required) will be used. I specifically had to add these dummies, when migrating. First I set them to the actually values, but since KKP will automatically figure out correct values or has sane defaults, I disliked hardcoding it like that. Then I found out they can just be set to "empty"/null-like values.

### How is your environment configured?

- KKP version: 2.20.11
- Shared or separate master/seed clusters?: shared + seed

### Provide your KKP manifest here (if applicable)

N/A

### What cloud provider are you running on?

OpenStack

### What operating system are you running in your user cluster?

N/A
