### ISSUE TITLE
Test Node Eviction Controller - Test Release 2.22

### ISSUE THREAD

**Issue by hdurand0710** [kubermatic/kubermatic#11736]

**Comment by hdurand0710** [comment]
Refer  : kubermatic/kubermatic#11588

---

**Comment by embik** [comment]
Note:

> Drain of the infra KubeVirt Node

This is ambiguous, the mechanism is triggered by cordoning a node. Draining cordons the node as well, but it also tries to evict pods, which won't work because PDBs block that.

**Comment by embik** [comment]
This seems to be working fine. Some notes:

- As a Kubernetes admin, I was expecting the eviction API calls (I triggered them manually via [kubectl-evict](https://github.com/ueokande/kubectl-evict) instead of draining the node) to succeed, but they failed as they are being blocked by a PDB.
- The node eviction controller however picks those pods I attempted to evict up and processes them, which was surprising for someone not being used to KubeVirt.

However, things seemed to work fine:
- A new Machine got created after the virt-launcher pod got evicted
- It joined the user cluster under a new node identity
- workloads got rescheduled within the user cluster

Just want to test with PVC workloads but so far, everything looks good.

**Comment by mfranczy** [comment]
> The node eviction controller however picks those pods I attempted to evict up and processes them, which was surprising for someone not being used to KubeVirt.

We are going to add a better explanation to doc that in the future cluster admins are not surprised by that.

**Comment by embik** [comment]
so I think I just found an issue with node-eviction: I created a PVC on my user cluster and a simple pod mounting it (I'll share the manifests in this thread). I made sure the pod got scheduled and was running. Then I evicted the node's virt-launcher Pod from KubeVirt. The pod got terminated properly, but re-creating the pod after the node went away fails with:

```
Warning  FailedAttachVolume  3m40s  attachdetach-controller  Multi-Attach error for volume "pvc-04bf24ee-a755-4bee-bbcb-559aca75d862" Volume is already exclusively attached to one node and can't be attached to another
```

and indeed, when looking at volumeattachments, this one still exists:

```
NAME                                                                   ATTACHER          PV                                         NODE                                        ATTACHED   AGE
csi-6b42e564b2e31809881c86d5385e7711d0c094bb60039095d14178daabc6ecc0   csi.kubevirt.io   pvc-04bf24ee-a755-4bee-bbcb-559aca75d862   zhtjh9blrt-worker-w8z64w-5f679f4c95-68tvr   true       10m
```

the node mentioned here no longer exists. And if I look at this resource, it has a deletion timestamp but this is its status:

```
status:
    attachError:
      message: 'rpc error: code = Unknown desc = Operation cannot be fulfilled on
        virtualmachineinstance.kubevirt.io "zhtjh9blrt-worker-w8z64w-5f679f4c95-68tvr":
        Unable to add volume [pvc-04bf24ee-a755-4bee-bbcb-559aca75d862] because it
        already exists'
      time: "2023-02-09T13:17:19Z"
    attached: true
    detachError:
      message: 'rpc error: code = NotFound desc = failed to find VM with domain.firmware.uuid
        6d9a9661-0871-5893-9d13-60a352d74d6e'
      time: "2023-02-09T13:27:11Z"
 ```
 
 <details>
 
 My manifests to create this problem:
 
 ```yaml
 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
  - name: app
    image: centos
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: pvc
```
