### ISSUE TITLE
Migration: Virtual Machines Templating - Test Release 2.22

### ISSUE THREAD

**Issue by hdurand0710** [kubermatic/kubermatic#11734]

**Comment by hdurand0710** [comment]
Refer to https://docs.kubermatic.com/kubermatic/main/architecture/supported-providers/kubevirt/kubevirt/#migration-from-kkp-221-to-kkp-222

---

Flavor is deprecated in favour of `Instancetype` and `Preference`

## 1 Migration from 2.21 to 2.22
- Create a KKP 2.21 KubeVirt cluster, with 1 MD with some `VM Flavor`  (VirtualMachineInstancePresets) at step 4 `Initial Nodes`
- Check that the cluster is healthy.
- Update to KKP 2.22 without any change to the MD.
- Everything should work as before, no restart/update of the KubeVirt VM should happen.
- Now update the MD spec following the migration guide in the documentation (replacing with InstanceType/Preference)
   - you can use Virtualmachineclusterinstancetypes (cluster-wide)/Virtualmachineinstancetypes (namespaced)
   - you can use Virtualmachineclusterpreference (cluster-wide) / VirtualmachinePreference (namespaced)
- A new KubeVirt VM should be spawned
- Check that the new VM has the following spec:

```yaml
  instancetype:
    kind: VirtualMachineInstancetype
    name: standard-2
  preference:
    kind: VirtualMachinePreference
    name: sockets-advantage
```
if you did select : 
- standard-2 as instancetype
- sockets-advantage as Preference

- Check that the new Node becomes Ready
