### ISSUE TITLE
Test TopologySpreadConstraints - Test Release 2.22

### ISSUE THREAD

**Issue by hdurand0710** [kubermatic/kubermatic#11741]

**Comment by hdurand0710** [comment]
Refer : ubermatic/dashboard/pull/5296

---

## Test Default TopologySpreadConstraints
- Create a KubeVirt cluster without specifying any option dealing with `TolopogySpreadConstraints`.

A default one should be create in the VM (and virt-launcher pods):
```yaml
topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            md: ik7dkmchnb-worker-n5rxmd
        maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
```

## Test custom TopologySpreadConstraints

**Comment by embik** [comment]
Can confirm the default topology spread and that pods were scheduled to different nodes:

```yaml
    topologySpreadConstraints:
    - labelSelector:
        matchLabels:
          md: bzf2rwb9z8-worker-znrgsj
      maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: ScheduleAnyway
 ```
