### ISSUE TITLE
Proxy support - Test Release 2.22

### ISSUE THREAD

**Issue by ahmedwaleedmalik** [kubermatic/kubermatic#11764]
## Instructions
1. Configure proxy configuration at seed level https://docs.kubermatic.com/kubermatic/main/references/crds/#proxysettings
2. Create a cluster for that DC
3. Ensure that this configuration gets propagated to the machines
4. Verify configuration in the generated OperatingSystemConfigs and bootstrap/provisioning secrets
5. SSH into the machine to verify that requests are being proxied. Not sure what's the best way to test this though.

## References
- https://github.com/kubermatic/operating-system-manager/issues/247
- https://github.com/kubermatic/operating-system-manager/issues/234

**Comment by embik** [comment]
Hey @ahmedwaleedmalik, can you please add instructions to this testing ticket so someone can verify it? Thanks!

**Comment by ahmedwaleedmalik** [comment]
@embik updated. I'm not really sure what's the easiest way to test the last step but a little bit of googling can help the tester in there, it's not really KKP specific.

**Comment by embik** [comment]
Thanks, makes sense to me.

**Comment by shatoboar** [comment]
There seems to be an issue when testing this:
When creating a Datacenter with the following options
```yaml   
aws-eu-central-1b:
   country: DE
      location: EU (Frankfurt2)
      node: 
         httpProxy: http://test.proxy:8080
      spec:
        aws:
          region: eu-central-1
```
It continually writes to the `/etc/environments` file. It results in the file looking like the picture attached below, and the node not connecting.

![etc-environment](https://user-images.githubusercontent.com/57257492/220668630-baedbbe2-a2c2-4924-8a96-e1ae3e1b128a.jpg)
