### ISSUE TITLE
test ApplicationDefinition defaulting of defaultDeployOptions - Release 2.22

### ISSUE THREAD

**Issue by vgramer** [kubermatic/kubermatic#11819]
# Test Atomic= true implies wait=true and tiemout =5m
## How to test 
create an applicationDefintion with atomic: true:

```yaml
apiVersion: apps.kubermatic.k8c.io/v1
kind: ApplicationDefinition
metadata:
  name: apache
spec:
  description: "test"
  method: helm
  versions: []
  defaultDeployOptions:
    helm:
      atomic: true
```
## expecting the result
This should be defaulted as:
```yaml
apiVersion: apps.kubermatic.k8c.io/v1
kind: ApplicationDefinition
metadata:
  name: test
spec:
  description: "test"
  method: helm
  versions: []
  defaultDeployOptions:
    helm:
      atomic: true
      wait: true
      timeout: "5m"
```
# Test wait= true implies  timeout =5m
## How to test 
create an applicationDefintion with wait: true:
```yaml
apiVersion: apps.kubermatic.k8c.io/v1
kind: ApplicationDefinition
metadata:
  name: test
spec:
  description: "test"
  method: helm
  versions: []
  defaultDeployOptions:
    helm:
      wait: true
```
## expecting the result
```yaml
apiVersion: apps.kubermatic.k8c.io/v1
kind: ApplicationDefinition
metadata:
  name: apache
spec:
  description: "test"
  method: helm
  versions: []
  defaultDeployOptions:
    helm:
      wait: true
      timeout: "5m"
```
