### ISSUE TITLE
Test Applications Upgrade - Test Release 2.22

### ISSUE THREAD

**Issue by vgramer** [kubermatic/kubermatic#11816]
On KKP 2.21 installation, do the following:

1. Add an ApplicationDefinition on master cluster:
   ```yaml
    apiVersion: apps.kubermatic.k8c.io/v1
    kind: ApplicationDefinition
    metadata:
      name: apache
    spec:
      defaultValues:
        commonLabels:
          owner: somebody
      description: Apache HTTP Server is an open-source HTTP server for modern operating systems
      method: helm
      versions:
        - template:
            source:
              helm:
                chartName: apache
                chartVersion: 9.2.11
                url: https://charts.bitnami.com/bitnami
          version: 9.2.11
        - template:
            source:
              helm:
                chartName: apache
                chartVersion: 9.2.9
                url: https://charts.bitnami.com/bitnami
          version: 9.2.9
   ```
1. Create a cluster template with an application
1. Upgrade KKP
1. Create a cluster from the cluster template and check application is installed in the user-cluster
