### ISSUE TITLE
test applicationInstallation failure counter is reset on spec change - Release 2.22

### ISSUE THREAD

**Issue by vgramer** [kubermatic/kubermatic#11823]
# Test that failure counter  is reset if application spec change before the reaching the max number of retries (which is 5)
## How to test
1. create an Application with atomic = true
   ```yaml
    apiVersion: apps.kubermatic.k8c.io/v1
    kind: ApplicationDefinition
    metadata:
      name: test
    spec:
      description: "test"
      method: helm
      versions: [....]
      defaultDeployOptions:
        helm:
          atomic: true
          wait: true
          timeout: "1m"
   ```
2. create an applicationInstallation that will failed installation (eg. you can override container's image with an image that does not exist)

3. check that  failure counter is increased (`ApplicationsInstallation.Status.Failures`)
4. change the spec (e.g. edit a values)

## Expected result
1. failure counter is reset to 0
2. failure counter is still increased if install failed.

# Test that failure counter  is reset if application spec change after the reaching the max number of retries (which is 5)
## How to test
1. create an Application with atomic = true
   ```yaml
    apiVersion: apps.kubermatic.k8c.io/v1
    kind: ApplicationDefinition
    metadata:
      name: test
    spec:
      description: "test"
      method: helm
      versions: [....]
      defaultDeployOptions:
        helm:
          atomic: true
          wait: true
          timeout: "1m"
   ```
2. create an applicationInstallation that will failed installation (eg. you can override container's image with an image that does not exist)
3. wait that  failure counter (`ApplicationsInstallation.Status.Failures`) reaches the max number of retries
4. change the spec (e.g. edit a values)

## Expected result
1. failure counter is reset to 0
2. failure counter is still increase if install failed.
