### ISSUE TITLE
test ApplicationDefinition: defaultDeployOptions  are working- Release 2.22

### ISSUE THREAD

**Issue by vgramer** [kubermatic/kubermatic#11820]
# Test atomic =true revert installation on failure
## How to test
1. create an Application with atomic = true
   ```yaml
    apiVersion: apps.kubermatic.k8c.io/v1
    kind: ApplicationDefinition
    metadata:
      name: test
    spec:
      description: "test"
      method: helm
      versions: [....]
      defaultDeployOptions:
        helm:
          atomic: true
          wait: true
          timeout: "1m"
   ```
2. create an applicationInstallation that will failed installation (eg. you can override container's image with an image that does not exist)

## Expected result

- Installation is reverted. (workloads are deleted if it was the first install, or revert to the previous version if app was already installed)
- status is updated with the failure reason
- failure counter is increased  (`ApplicationsInstallation.Status.Failures`)
- when `ApplicationsInstallation.Status.Failures` reaches the max max number of retries:
- * the condition `Ready` is set with `{status: "False", reason: "InstallationFailedRetriesExceeded", message: "Max number of retries was exceeded. Last error: <err_msg>"}` 

# Test atomic= false, wait =true  
## how to test
1. create an Application with atomic= false, wait =true  
   ```yaml
    apiVersion: apps.kubermatic.k8c.io/v1
    kind: ApplicationDefinition
    metadata:
      name: test
    spec:
      description: "test"
      method: helm
      versions: [....]
      defaultDeployOptions:
        helm:
          wait: true
          timeout: "1m"
   ```
2. create an applicationInstallation that will failed installation (eg. you can override container's image with an image that does not exist)

## Expected result
- Installation is not reverted
- status is updated with the failure reason
- failure counter is increased  (`ApplicationsInstallation.Status.Failures`)
- when `ApplicationsInstallation.Status.Failures` reaches the max max number of retries:
- * the condition `Ready` is set with `{status: "False", reason: "InstallationFailedRetriesExceeded", message: "Max number of retries was exceeded. Last error: <err_msg>"}`
