### ISSUE TITLE
test ApplicationInstallation defaulting of deployOptions - Release 2.22

### ISSUE THREAD

**Issue by vgramer** [kubermatic/kubermatic#11822]
# Test Atomic= true implies wait=true and timeout =5m
## How to test 
create an applicationInstallation  atomic: true:

```yaml
apiVersion: apps.kubermatic.k8c.io/v1
kind: ApplicationInstallation
metadata:
  name: my-apache
  namespace: default
spec:
  deployOptions:
    helm:
      atomic: true
  namespace:
    name: foo
  applicationRef:
    name: apache
    version: 9.2.9
```
## expecting the result
This should be defaulted as:
```yaml
apiVersion: apps.kubermatic.k8c.io/v1
kind: ApplicationInstallation
metadata:
  name: my-apache
  namespace: default
spec:
  deployOptions:
    helm:
      atomic: true
      wait: true
      timeout: "5m"
  namespace:
    name: foo
  applicationRef:
    name: apache
    version: 9.2.9
```
# Test wait= true implies  timeout =5m
## How to test 
create an applicationInstallation with wait: true:
```yaml
apiVersion: apps.kubermatic.k8c.io/v1
kind: ApplicationInstallation
metadata:
  name: my-apache
  namespace: default
spec:
  deployOptions:
    helm:
      wait: true
  namespace:
    name: foo
  applicationRef:
    name: apache
    version: 9.2.9
```
## expecting the result
```yaml
apiVersion: apps.kubermatic.k8c.io/v1
kind: ApplicationInstallation
metadata:
  name: my-apache
  namespace: default
spec:
  deployOptions:
    helm:
      wait: true
      timeout: "5m"
  namespace:
    name: foo
  applicationRef:
    name: apache
    version: 9.2.9
```

**Comment by rastislavs** [comment]
Defaulting works as expected.

Just a minor note - `spec.values` seems do be mandatory, so at least empty non-null values needs to be provided in the `ApplicationInstallation` spec, e.g.:

```yaml
apiVersion: apps.kubermatic.k8c.io/v1
kind: ApplicationInstallation
metadata:
  name: my-apache
  namespace: default
spec:
  values: {}
...
```

(the error that could be seen otherwise: `The ApplicationInstallation "my-apache" is invalid: spec.values: Invalid value: "null": spec.values in body must be of type object: "null"`)
