### ISSUE TITLE
application helm source http with authentication: error 401 unauthorized

### ISSUE THREAD

**Issue by hdurand0710** [kubermatic/kubermatic#11875]
### What happened?

Defined an applicationdefinition
```
apiVersion: apps.kubermatic.k8c.io/v1
kind: ApplicationDefinition
metadata:
  name: ln-cm2
spec:
  description: Deploys a cm2
  method: helm
  versions:
  - template:
      source:
        git:
          credentials:
            method: ssh-key
            password:
              key: pass
              name: ln-git-for-app
            sshKey:
              key: sshKey
              name: ln-git-for-app-ssh
            token:
              key: token
              name: ln-git-for-app
            username:
              key: user
              name: ln-git-for-app
          path: examplechart
          ref:
            branch: main
          remote: ssh://git@github.com/hdurand0710/test-application2.git  
    version: 1.0.0
  - template:
      source:
        helm:
          chartName: examplechart
          chartVersion: 0.1.0
          url: https://demo.goharbor.io/chartrepo/heleneprivate
          credentials:
            password:
              key: pass
              name: ln-helm-for-app      
            username:
              key: user
              name: ln-helm-for-app
    version: 1.0.1
```

with a private repo on Harbor.

Then add this application into a user cluster.
I get an error:
`failed to download application source: can not download index file: failed to fetch https://demo.goharbor.io/chartrepo/heleneprivate/index.yaml : 401 Unauthorized . Please check your configuration or contact your KKP Administrator.`

Double checked the credentials with @vgramer, everything looks good.

### Expected behavior

There should not be any error and we should be able to install the chart.

### How is your environment configured?

- KKP version: QA 2.22
- Shared or separate master/seed clusters?:

### What cloud provider are you running on?

KubeVirt
