### ISSUE TITLE
ApplicationInstallation: default values to empy object

### ISSUE THREAD

**Issue by vgramer** [kubermatic/kubermatic#11881]
if a user creates an ApplicationInstallation without `.spec.values`, he got an error:

```
echo 'apiVersion: apps.kubermatic.k8c.io/v1
kind: ApplicationInstallation
metadata:
  name: my-apache
  namespace: default
spec:
  namespace:
    name: foo
    create: true
    labels:
      foo: bar
  applicationRef:
    name: apache
    version: 9.2.9' | k apply -f -
The ApplicationInstallation "my-apache" is invalid: spec.values: Invalid value: "null": spec.values in body must be of type object: "null"
```

We should default `.spec.values` to `{}` to avoid this error
