### ISSUE TITLE
Add PVC source

### ISSUE THREAD

**Issue by mfranczy** [kubermatic/kubermatic#11986]
A new PVC source configuration in the seed should have the following structure:
```
images:
  pvc:
    namespace: <namespace>
    operatingSystems:
      centos:
         <<version>>: <<url>>
```

The PVC format should have a name <operating-system>-<version> like centos-7.4 etc.

Acceptance criteria:
* Appropriate RBAC and network policy for the `pvc.namespace` are reconciled in the cloud provider KubeVirt
* API returns a new pvc source in the same endpoint as http images (category added)
* MC works with a new image source
* UI is adjusted for new image source

Non-goals:
* Write a controller that will provision PVCs based on the above configuration
