### ISSUE TITLE
Deploy Grafana Agent along with the monitoring stack

### ISSUE THREAD

**Issue by hbernardo** [kubermatic/kubermatic#12044]
Similar to `charts/monitoring/grafana`

Example of Grafana Agent configuration (mode "static", not "flow") for forwarding collected telemetry to Loki, Tempo, and Prometheus instances:
```
      server:
        log_level: 'debug'
      metrics:
        wal_directory: /tmp/wal
        global: {}
        configs:
          - name: default
            remote_write:
              - url: http://prometheus.monitoring.svc.cluster.local:9090/api/prom/push
      logs:
        positions_directory: /tmp/loki-pos
        configs:
          - name: default
            scrape_configs: []
            clients:
              - url: http://loki.logging.svc.cluster.local:3100/loki/api/v1/push
      traces:
        configs:
          - name: default
            remote_write:
              - endpoint: 'tempo.monitoring.svc.cluster.local:4317'
                insecure: true
            receivers:
              otlp:
                protocols:
                  grpc:
      integrations:
        app_agent_receiver_configs:
          - autoscrape:
              enable: true
              metrics_instance: 'default'
            instance: 'kkp-dashboard'
            logs_instance: 'default'
            traces_instance: 'default'
            server:
              api_key: 'api_key'
              host: 0.0.0.0
              port: 12347
              cors_allowed_origins:
                - '*'
            logs_labels:
              app: kkp-dashboard
              kind: ''
            logs_send_timeout: 5000
            sourcemaps:
              download: true
```

Extra needed run arg:
```
-enable-features=integrations-next
```
