### ISSUE TITLE
kubermatic-seed-controller-manager: Failed to collect metrics for backup destination

### ISSUE THREAD

**Issue by akurz** [kubermatic/kubermatic#12168]
### What happened?

We have configured an etcdBackupRestore destination with an AWS S3 endpoint. We are using the non region specific "s3.amazonaws.com" endpoint.  The backups are working fine and I'm not sure how long theses error messages are already generated but there are a lot of them:

 `kubermatic-seed-controller-manager-f47b4cc6f-q9mnk controller-manager  {"level":"error","time":"2023-04-12T08:42:35.627Z","caller":"collectors/clusterbackup.go:126","msg":"Failed to collect metrics for backup destination","destination":"aws-s3","error":"failed to list objects in bucket: Get \"https://********.dualstack.us-east-1.amazonaws.com/?delimiter=&encoding-type=url&fetch-owner=true&list-type=2&prefix=\": 301 response missing Location header"}`

The S3 bucket in use is located in the **eu-central-1** region. Once I change the etcdBackupRestore.destinations.aws-s3.endpoint to **s3.eu-central-1.amazonaws.com** the errors are gone.

### Expected behavior

I expect the controller to correctly resolv the endpoint for this metrics collection and therefor not spamming the logs.

### How to reproduce the issue?

Set up an AWS S3 Bucket in any (but us-east-1 ???) region and configure in the seed the etcdBackupRestore destination with the general `etcdBackupRestore.destinations.aws-s3.endpoint: s3.amazonaws.com`

### How is your environment configured?

- KKP version: 2.21.7
- Shared or separate master/seed clusters?: shared

### Provide your KKP manifest here (if applicable)

```yaml
# paste manifest here
etcdBackupRestore:
    defaultDestination: aws-s3
    destinations:
      aws-s3:
        bucketName: your-bucket-in-some-region
        credentials:
          name: kubermatic-default-backups
          namespace: kube-system
        endpoint: s3.amazonaws.com

```
### What cloud provider are you running on?

 non-natively supported provider - OpenNebula

### What operating system are you running in your user cluster?

Flatcar Linux
