### ISSUE TITLE
Component Override for usercluster-controller-manager - Test Release 2.23

### ISSUE THREAD

**Issue by embik** [kubermatic/kubermatic#12321]
#12211 added component overrides for `usercluster-controller-manager` since its settings were hardcoded before. Test it to make sure the changes in the component override reflect on the actual resources.

## How to Test

1. Create a user cluster on QA.
2. Add `.spec.componentsOverride.userClusterController` via `kubectl` to the cluster to change component overrides. Use [our CRD documentation](https://docs.kubermatic.com/kubermatic/main/references/crds/#componentsettings) to discover possible settings.
3. Adjust the values according to your liking and make sure they are being reconciled on the actual resources in the `cluster-<cluster ID>` namespace.
4. Repeat the same tests with a `ClusterTemplate` by creating one via `kubectl` and setting some values for the `userClusterController` override. Create user clusters from that template and make sure that a) their component overrides are set correctly and b) the set values are reflected in the `cluster-<cluster ID>`.

**Comment by wozniakjan** [comment]
most of it imho works as expected, but I have one question and one nit from testing for maybe followup work. 

**question:**
What is the expected output for configuration of leader election? I configured the following cluster spec and I couldn't observe any changes on the `usercluster-controller` deployment apart from the `replicas` changed from `1` to `2`.
```yaml
...
     userClusterController:
       leaderElection:
         leaseDurationSeconds: 50
         renewDeadlineSeconds: 5
         retryPeriodSeconds: 10
       replicas: 2
...
```
and while there is a `Lease` in `kube-system` called `user-cluster-controller-leader-lock`, it doesn't seem to have a lease for my cluster.

**nit for future work:**
When broken tolerations are specified, validating webhook on `Cluster` permits them and the issues are then reflected as events on `Cluster` CR, e.g.
```
  Warning  ReconcilingError  12m (x6 over 27m)    kkp-kubernetes-controller  failed to reconcile cluster: failed to ensure Deployment cluster-h4hf7gb22w/usercluster-controller: failed to update object *v1.Deployment "cluster-h4hf7gb22w/usercluster-controller": Deployment.apps "usercluster-controller" is invalid: spec.template.spec.tolerations[0].operator: Invalid value: core.Toleration{Key:"key", Operator:"Exists", Value:"val", Effect:"NoExecute", TolerationSeconds:(*int64)(nil)}: value must be empty when `operator` is 'Exists'
```
we could embed the validating code from kubernetes upstream in our webhook as well to unify the behaviour

**Comment by embik** [comment]
For 1.) the lease you discovered is the lease for the cluster _hosting_ QA, which in itself is a KKP user cluster. That means you need to check the `Lease` object in the user cluster's `kube-system` namespace.

However, I think you are right and I simply forgot/overlooked that the settings struct also added leader election settings. Can you please verify that (with checking the `Lease` in the user cluster) and open a bug report? I'm not sure this warrants a fix within the code freeze since messing with leader election settings last minute might bring more harm than good (and I wouldn't expect anyone to change this tbh), but need to track it.

For 2.) I agree. Another issue for our backlog (maybe we can even tag this one "help-wanted" since it seems straightforward) would be nice here.

**Comment by wozniakjan** [comment]
> That means you need to check the `Lease` object in the user cluster's `kube-system` namespace.

ah, of course, that makes sense :)

> checking the `Lease` in the user cluster

checked, looks like the parameters are still not reflected so I will open a bug ticket and I agree with it being a low priority
```yaml
spec:
  acquireTime: "2023-06-19T12:41:42.609220Z"
  holderIdentity: usercluster-controller-6674786546-chth5_68f1beab-356e-497f-989d-2f6b6c85c821
  leaseDurationSeconds: 15
  leaseTransitions: 1
  renewTime: "2023-06-19T12:42:29.181022Z"
```
