### ISSUE TITLE
Introduce Egress based NetworkPolicies for KubeVirt

### ISSUE THREAD

**Issue by mate4st** [kubermatic/kubermatic#12328]
Currently KubeVirt creates a default network policy to ensure VMs from different user clusters cannot communicate with each other. This policy is restricting ingress and comes with some caveats: 

* Ingress to the KubeVirt VMs is restricted to the KubeVirt cluster or LoadBalancers by design.
* This approach breaks incoming connections that are masqueraded through the k8s network. Meaning Load balancer only work when `externalTrafficPolicy: local` is set to avoid that incoming traffic is masqueraded. 

For the above reason and the fact we care what users can access with their KubeVirt VMs NOT who access their KubeVirt VMs we want to follow an Egress based approach:

* A default deny all Egress that allows explicitly pod 2 pod communication in the same namespace ensuring nodes are able to communicate
* With Egress we can restrict access to a whole DC internal IP range and only allow Public IPs (Internet)
* Enables us to use an allowlist approach for internal services that a user should be able to consume  (like dns) or the provider wants to offer to them
* As a benefit Egress Policy restricts access for users to all possible Kubernetes services running in the KubeVirt cluster they would otherwise have access to by default
* Debugging will have no restrictions by this network policy
* Minor down site is that we need to ensure that access to the seed is allowed and essential services (list below)
* The Cluster Network Should also be explicitly put into the except block to ensure that cluster access is denied (just in case someone uses a public IP range for their cluster network)

Egress connection to allow:

* Internet
* Seed nodeport-proxy
* DNS
* NTP
* KubeVirt image-repo

This is an example on how the end result could look like: 

```yaml
- name: restrict-egress
  spec:
    egress:
      - to:
          - ipBlock:
              cidr: 0.0.0.0/0  # alllow internet
              except:
                - 10.0.0.0/8
                - 172.16.0.0/12
                - 192.168.0.0/16
      - to:
          - ipBlock:
              cidr:   <nodeport-proxy ip> 
        ports:   # tunneling ports depends on expose strategy
          - port: 8088
            protocol: TCP
          - port: 6443
            protocol: TCP
      - to:
          - ipBlock:
              cidr:  <dns server ip>
        ports:
          - port: 53
            protocol: UDP
          - port: 53
            protocol: TCP
      - to:
          - ipBlock:
              cidr: 0.0.0.0/0   # allow ntp to everywhere
        ports:
          - port: 123
            protocol: UDP
      - to:
          - podSelector: {}
    podSelector: {}
    policyTypes:
      - Egress
- name: allow-kubevirt-importer   # kubevirt image repo only accessible for the importer
  spec:
    egress:
      - to:
          - namespaceSelector:
              matchLabels:
                kubernetes.io/metadata.name: kube-system
            podSelector:
              matchLabels:
                app: image-repo
        ports:
          - port: 80
            protocol: TCP
    podSelector:
      matchLabels:
        app: containerized-data-importer
        cdi.kubevirt.io: importer
    policyTypes:
      - Egress

```
