### ISSUE TITLE
KubeVirt cluster-isolation network policy - Test Release 2.23

### ISSUE THREAD

**Issue by mfranczy** [kubermatic/kubermatic#12378]
**Instruction** (related PR https://github.com/kubermatic/kubermatic/pull/12329)

1. Create two KubeVirt clusters 
1.1 Each cluster should have two machines
1.2 Use `rook-ceph` storage class
2. On KubeVirt infra cluster check if each cluster contains `cluster-isolation` network policy
2.1 `kubectl get networkpolicy cluster-isolation -n <cluster-namespace> -oyaml` 
3. Check if the policy contains egress rules similar to:
```yaml
spec:
  egress:
  - to:
    - podSelector: {}
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 10.0.0.0/8
        - 172.16.0.0/12
        - 192.168.0.0/16
  - to:
    - ipBlock:
        cidr: x.x.x.x/32
  - ports:
    - port: 53
      protocol: TCP
    - port: 53
      protocol: UDP
    to:
    - ipBlock:
        cidr: x.x.x.x/32
  podSelector: {}
  policyTypes:
  - Egress
```
4. Confirm that network communication between vms in the same cluster works
4.1 Get vms ip addresses `kubectl get vmi -n <cluster-namespace>`
4.2 Console into vm `virtctl console <vm-name> -n <cluster-namespace>` (ask for credentials at #sig-virtualization channel)
4.3 Ping the other vm in the same cluster
5. Confirm that network communication between vms in differnet clusters is disabled
5.1 Get vms ip addresses `kubectl get vmi -n <other-cluster-namespace>`
5.2 Console into vm `virtctl console <vm-name> -n <cluster-namespace>` (ask for credentials at #sig-virtualization channel)
5.3 Ping the other vm in a different cluster
6. Confirm DNS resolution inside vm works fine
6.1 `nslookup google.com`
6.2 `nslookup image-registry.default.svc.cluster.local`
