### ISSUE TITLE
Kubernetes API connectivity breaks in Azure user cluster when creating a `LoadBalancer` service

### ISSUE THREAD

**Issue by embik** [kubermatic/kubermatic#12419]
### What happened?

This issue has been identified while QA testing KKP 2.23.0, however it is reproducible in KKP 2.22.4.

When creating an Azure user cluster without assigning public IPs to the machines, creating a `LoadBalancer` service appears to break networking in _some_ way. The symptoms are as follows:

- `Node` objects toggle to `NotReady`.
- Pods toggle to being not ready, e.g. `calico-kube-controllers` pods starting showing 0/1. This is most likely because those Pods cannot reach the Kubernetes API any longer.
- Pod logs etc. cannot be accessed anymore, `kubectl logs` hangs (which means konnectivity also ceases to function).

My guess would be that Node -> Kubernetes API in the Seed connectivity is breaking down, but perhaps it is Internet access as a whole. Since the nodes are in a private network, it's hard to investigate what exactly is happening with them.

I first thought it was the load balancer SKU, but both `basic` and `standard` seem to have this problem. This does not happen with public IPs on the Nodes.

### Expected behavior

No issues when creating a load balancer in my Azure user cluster.

### How to reproduce the issue?

1. Create an Azure user cluster on KKP.
2. While configuring the initial machines, unselect "Assign Public IP".
3. Create a LoadBalancer service on the user cluster once created, e.g. with the bundle below.
4. Investigate Node and Pod status after a couple of minutes.

<details>

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: echoserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver
  namespace: echoserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: echoserver
  template:
    metadata:
      labels:
        app: echoserver
    spec:
      containers:
      - image: gcr.io/google-containers/echoserver:1.8
        imagePullPolicy: Always
        name: echoserver
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: echoserver
  namespace: echoserver
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: echoserver
```

</details>

### How is your environment configured?

- KKP version: v2.23.0-rc.0, v2.22.4 (not tested on older versions)
- Shared or separate master/seed clusters?: shared

### Provide your KKP manifest here (if applicable)

<details>

```yaml
# paste manifest here
```

</details>

### What cloud provider are you running on?

Azure

### What operating system are you running in your user cluster?

Ubuntu 22.04

### Additional information

N/A
