### ISSUE TITLE
Provide single registry override for all images in a KKP setup

### ISSUE THREAD

**Issue by embik** [kubermatic/kubermatic#12465]
### Description of the feature you would like to add / User story

As a KKP administrator trying to install KKP in an air-gapped setup
I would like to configure a single registry override
in order to easily configure KKP with a image source for everything.

### Solution details

- A field in `KubermaticConfiguration`'s `spec` that allows to give a single base URL for image repository overrides.
-The image repository override is applied to all images except for those where a specific configuration (also see below in the Alternatives approaches) is set.
- An expected repository structure under that base URL is properly documented. Maybe even add a config knob that changes this between collapsed (as the `mirror-images` command does) and per-upstream-repository, e.g. image locations from `quay.io/<organization>/<image name>` go to `your.registry.internal/quay/<organization>/<image name>` (as it would look like if you configure pull-through registry mirrors internally).

### Alternative approaches

The current situation and documentation [advises](https://docs.kubermatic.com/kubermatic/v2.23/installation/offline-mode/#configuring-kkp) to go over all dockerRepository configuration fields in `KubermaticConfiguration`. This is very tedious and error-prone. It's so difficult that the documentation doesn't even bother to list out all fields.

### Use cases

Air-gapped KKP installations

### Additional information

Sort of related to #12368, which would cover the ability to bring your images into an air-gapped environment.

**Comment by hc2p** [comment]
Why not using registry-mirrors for this? 

```
apiVersion: kubeone.k8c.io/v1beta2
kind: KubeOneCluster
containerRuntime:
  containerd:
    registries:
      "*":
        mirrors:
        - registry.archive.offline-reference.lab.kubermatic.io
      docker.io:
        mirrors:
        - registry.archive.offline-reference.lab.kubermatic.io
```

With this, every OCI being pulled by containerd is sent to the internal OCI registry instead, transparently. No need to change URIs.
