### ISSUE TITLE
Improve override configuration for API image

### ISSUE THREAD

**Issue by ahmedwaleedmalik** [kubermatic/kubermatic#12464]
### What happened?

In it's current state, the ability to override the image for KKP API is confusing. For UI, it's fairly simple since we can configure it in `KubermaticConfiguration` under `.spec.ui.*`. Although for API, we have a similar section `.spec.api` but it only allows us to override the image registry i.e. `dockerRepository`. The tag specified in the UI configuration is consumed for API as well. This segregation doesn't make much sense and is confusing for the end users.

The API section should have `dockerTag` and `dockerTagSuffix` fields similar to the UI configuration.

Current configuration for override looks like:

```yaml
apiVersion: kubermatic.k8c.io/v1
kind: KubermaticConfiguration
metadata:
  name: kubermatic
  namespace: kubermatic
spec:
  ui:
    dockerRepository: quay.io/kubermatic/dashboard-ee
    dockerTag: <image-tag>
  api:
    dockerRepository: quay.io/kubermatic/dashboard-ee
```

Code reference: https://github.com/kubermatic/kubermatic/blob/release/v2.23/pkg/controller/operator/master/resources/kubermatic/api.go#L246
