### ISSUE TITLE
KKP custom certificates: invalid spec

### ISSUE THREAD

**Issue by JamesClonk** [kubermatic/kubermatic#12674]
### What happened?

According to the docs at https://docs.kubermatic.com/kubermatic/v2.23/tutorials-howtos/kkp-configuration/custom-certificates/#kkp I have to simply set `spec.ingress.certificateIssuer.name` to an empty string in `KubermaticConfiguration` in order to use my own custom certificates, and not use an issuer from cer-manager.
However, when configuring the KubermaticConfiguration exactly as shown in the example in the docs, this will not work and fail with an error message:
```
INFO[0066]    📝 Applying Kubermatic Configuration…
INFO[0067]    ✅ Success.
ERRO[0067] ❌ Operation failed: failed to apply Kubermatic Configuration: KubermaticConfiguration.kubermatic.k8c.io "kubermatic" is invalid: spec.ingress.certificateIssuer.kind: Required value.
```

### Expected behavior

I expected this configuration to work:
```yaml
apiVersion: kubermatic.k8c.io/v1
kind: KubermaticConfiguration
metadata:
  name: kubermatic
  namespace: kubermatic
spec:
  ingress:
    certificateIssuer:
      name: ""
    className: nginx
    domain: my-wonderful-domain.com
```

Ideally that configuration should not result in an invalid spec for `KubermaticConfiguration.kubermatic.k8c.io`.

Either `spec.ingress.certificateIssuer.kind` should need to be made optional, or the example provided by the docs at https://docs.kubermatic.com/kubermatic/v2.23/tutorials-howtos/kkp-configuration/custom-certificates/#kkp should be updated to include the required value:
```yaml
apiVersion: kubermatic.k8c.io/v1
kind: KubermaticConfiguration
metadata:
  name: kubermatic
  namespace: kubermatic
spec:
  ingress:
    certificateIssuer:
      name: "" # empty string disables the cert-manager integration
      kind: ClusterIssuer # serves no purpose
    className: nginx
    domain: my-wonderful-domain.com
```

### How to reproduce the issue?

Apply the following KubermaticConfiguration to a new/fresh KKP installation:
```yaml
apiVersion: kubermatic.k8c.io/v1
kind: KubermaticConfiguration
metadata:
  name: kubermatic
  namespace: kubermatic
spec:
  ingress:
    certificateIssuer:
      name: ""
    className: nginx
    domain: my-wonderful-domain.com
```

### How is your environment configured?

- KKP version: `v2.23.4`
- Shared or separate master/seed clusters?: `shared` (irrelevant for this bug report)

### Provide your KKP manifest here (if applicable)

<details>

```yaml
apiVersion: kubermatic.k8c.io/v1
kind: KubermaticConfiguration
metadata:
  name: kubermatic
  namespace: kubermatic
spec:
  ingress:
    certificateIssuer:
      name: ""
    className: nginx
    domain: my-wonderful-domain.com
```

</details>

**Comment by wozniakjan** [comment]
I think there might be a discrepancy between the docs and our implementation of `KubermaticConfiguration` validation. We can either make the validation logic a bit more permissive or as an alternative solution, mention in our docs that disabling the certificate issuer can be achieved by the following snippet
```
apiVersion: kubermatic.k8c.io/v1
kind: KubermaticConfiguration
metadata:
  name: kubermatic
  namespace: kubermatic
spec:
  ingress:
    certificateIssuer: {}
    className: nginx
    domain: my-wonderful-domain.com
```
or setting `certificateIssuer: null` should also work. In both cases I get
```
INFO[0104]    📦 Deploying cert-manager…
INFO[0104]       No CertificateIssuer configured in KubermaticConfiguration, skipping.
```
the currently documented solution seems a bit awkward to me
```
spec:
  ingress:
    certificateIssuer:
      name: ""
```
