### ISSUE TITLE
Reconciliation fails after etcd backup/restore

### ISSUE THREAD

**Issue by koksay** [kubermatic/kubermatic#12718]
### What happened?

After an etcd backup/restore process, the user-cluster-manager was not able to reconcile `mla-monitoring-agent` ConfigMap and failed to start due to not having any successful reconciliations. Below is the debug logs:

[user-cluster-manager-debug.log](https://github.com/kubermatic/kubermatic/files/12892620/user-cluster-manager-debug.log)

After the ConfigMap deleted manually on the user cluster, it started to work well.

### Expected behavior

Successful reconciliation without any manual interaction.

### How to reproduce the issue?

1. Restore a MLA enabled kubevirt user cluster from etcd backup
2. user-cluster-manager will fail for the first reconciliation and will not become ready
3. Remove mla-monitoring-agent ConfigMap on the user cluster
4. See that user-cluster-manager is successful

### How is your environment configured?

- KKP version: 22.04
- Shared or separate master/seed clusters?: Separate master/seed

### What cloud provider are you running on?

KubeVirt (1.0.0)

### What operating system are you running in your user cluster?

Seed: Ubuntu 20.04.6 LTS   Kernel: 5.4.0-155-generic
User cluster: Ubuntu 20.04.5 LTS  Kernel: 5.4.0-135-generic

**Comment by embik** [comment]
Can you say if the restore process was ran after or before `2023-10-02T07:14:01.042Z`, the timestamp of the user-cluster-controller-manager starting?

**Comment by koksay** [comment]
We made 2 tests on that day, here are the creationTimestamps. So it was done before.

```
k get etcdrestores -n cluster-xxx -o jsonpath='{.items[*].metadata.creationTimestamp}'
2023-09-29T08:05:27Z 
2023-10-02T07:03:20Z 
2023-10-02T06:55:33Z
```

**Comment by embik** [comment]
so the user-cluster-controller-manager was never restarted. I suspect this is cache-related, and the user-cluster-controller-manager needs to be restarted after a restore. We should ensure that happens automatically.

**Comment by koksay** [comment]
@xrstf Well, in the current architecture, if you need to add more scraping configurations to the prometheus, then you add a ConfigMap. Our addon installations like node-exporter or kube-state-metrics do the same thing. Here are the example ConfigMaps:

```yaml
# k get cm monitoring-scraping-nginx -n mla-system  -o yaml
apiVersion: v1
data:
  monitoring-scraping-nginx.yaml: |
    - job_name: 'nginx'
      static_configs:
      - targets: ["xxx:9273"]
        labels:
          instance: KKK
      - targets: ["yyy:9273"]
        labels:
          instance: MMM
kind: ConfigMap
metadata:
  creationTimestamp: "2023-10-10T13:25:06Z"
  name: monitoring-scraping-nginx
  namespace: mla-system
```

```yaml
# k get cm monitoring-scraping-node-exporter -n mla-system  -o yaml
apiVersion: v1
data:
  custom-scrape-configs.yaml: |
    - job_name: node-exporter
      scrape_timeout: 20s
      scheme: http
      kubernetes_sd_configs:
        - role: endpoints
      relabel_configs:
        - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_label_app_kubernetes_io_name]
          regex: kube-system;node-exporter
          action: keep
        - source_labels: [__meta_kubernetes_pod_node_name]
          action: replace
          regex: (.+)
          replacement: $1
          target_label: node_name
kind: ConfigMap
metadata:
  creationTimestamp: "2023-09-05T15:40:22Z"
  labels:
    kubermatic-addon: node-exporter
  name: monitoring-scraping-node-exporter
  namespace: mla-system
```

So, I would say that installing node-exporter addon should be sufficient to reproduce.
