### ISSUE TITLE
Default Application Catalog installation

### ISSUE THREAD

**Issue by SimonTheLeg** [kubermatic/kubermatic#12782]
**[Hold] a Bug was discovered that needs to be fixed. Please run this test, after the following issue is fixed: #12780**

Scope of this is to test the new default application catalogue functionality in the kubermatic installer. For this the following should be the process to test it. Please also consult the documentation available at 

1. Either create a cluster locally (e.g. kind) or create one in the testing environment (cloud provider of choice)
2. Create an appropriate StorageClass called `kubermatic-fast`. For something like kind the following should work, for a cloud provider create one that is suitable.

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: kubermatic-fast
provisioner: rancher.io/local-path
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
``` 

3. Run the kubermatic installer with the `--deploy-default-app-catalog` flag

```bash
kubermatic-installer deploy --deploy-default-app-catalog 
```

4. Verify that the Application Catalogue is populated in the UI, it should have all the items from #12527 

5. Re-run the installer with the same flag again. It recoginize that there are already ApplicationDefinitions installed and finish successfully
