### ISSUE TITLE
App installation at cluster setup can block CNI deployment

### ISSUE THREAD

**Issue by embik** [kubermatic/kubermatic#12820]
### What happened?

When creating a user cluster through the dashboard, step 5 can be used to configure Applications that will be deployed upon cluster creation. An obvious candidate are the apps from the default app catalog (EE feature).

Unfortunately, this feature is problematic. App installation waits for the Helm chart to succeed deployment, which means it waits for Pods to start up. But Pods will never start up when no CNI is deployed, because nodes are not fully initialised.

If Cilium 1.13+ is used as CNI, it is also deployed via an "System" Application. But since System Applications  do not seem to have priority over normal Applications, you can run into the situation that user-cluster-controller-manager is stuck trying to deploy a "random" Application (e.g. cert-manager), and never gets to deploy Cilium. The cluster is then stuck as CNI never starts, so regular Pods can never start.

![Screenshot 2023-11-07 at 08 34 57](https://github.com/kubermatic/kubermatic/assets/10295525/cb45021e-801f-438b-a6d4-b6f3f676ec80)

The `cert-manager` ApplicationInstallation has the following status:

```yaml
  status:
    applicationVersion:
      template:
        source:
          helm:
            chartName: cert-manager
            chartVersion: v1.12.3
            url: https://charts.jetstack.io
      version: v1.12.3
    conditions:
      ManifestsRetrieved:
        lastHeartbeatTime: "2023-11-07T07:31:24Z"
        message: application's source successfully downloaded
        observedGeneration: 1
        reason: DownloadSourceSuccessful
        status: "True"
      Ready:
        lastHeartbeatTime: "2023-11-07T07:31:24Z"
        message: application is installing or upgrading
        observedGeneration: 1
        reason: InstallationInProgress
        status: Unknown
    method: helm
```

### Expected behavior

Cilium CNI "System Application" is installed with priority over normal Applications.

### How to reproduce the issue?

1. Create user cluster, during the wizard select "cert-manager" as Application to deploy.
2. Observe "cert-manager" Application stuck in deployment and "Cilium" Application never actually deploy.

### How is your environment configured?

- KKP version: `main`
- Shared or separate master/seed clusters?: shared

### Provide your KKP manifest here (if applicable)

<details>

```yaml
# paste manifest here
```

</details>

### What cloud provider are you running on?

N/A

### What operating system are you running in your user cluster?

N/A
