### ISSUE TITLE
Flaky handling of vcenter endpoint URL for vsphere datacenters

### ISSUE THREAD

**Issue by dharapvj** [kubermatic/kubermatic#12856]
### What happened?
If user provides `/` at the end of `vsphere.endpoint` in Seed spec, user cluster creation fails with very cryptic errors like below..

```
cluster validation failed: cloud: Invalid value: "<redacted>": failed to create vCenter session: POST "//sdk": 400 Bad Request
failed to get datastore list: failed to create vCenter session: POST "//sdk": 400 Bad Request
failed to create REST API session: POST "//sdk": 400 Bad Request
```

I believe that this happens because a) we append `/sdk/` at the end of the endpoint URL provided and b) we then search for `//` to strip out http or https at the start BUT due to one slash at end the of endpoint and another slash at start of /sdk, we get match for `//` just before sdk instead of just before https and so the parsing logic fails.

I do not know where in the code this parsing happens.

### Expected behavior
Code should be resilient to handle presence or absence of `/` at the end of endpoint url. Also, error thrown can be made more explicit.

### How to reproduce the issue?
1. Create a vsphere datacenter definition in seed
2. ensure to add a `/` at the end of the endpoint url in configuration
3. Try to create a user cluster in that DC

### How is your environment configured?

- KKP version: 2.23.4 (But this issue exists from the start of the time ;o) )
- Shared or separate master/seed clusters?: Separate

### Provide your KKP manifest here (if applicable)

<details>

```yaml
# Seed
apiVersion: kubermatic.k8c.io/v1
kind: Seed
metadata:
  name: seed-vsphere
  namespace: kubermatic
spec:
  country: DE
  datacenters:
    vsphere:
      country: DE
      location: Fra
      spec:
        vsphere:
          # rest of the spec removed for brevity
          # notice the / at the end
          endpoint: "https://my.awesome.vcenter.corp/"
```

</details>

### What cloud provider are you running on?
Vsphere

### What operating system are you running in your user cluster?
Ubuntu 22.04
