### ISSUE TITLE
Cilium with Tunneling Expose Strategy has overlapping Envoy base IDs what breaks network

### ISSUE THREAD

**Issue by toschneck** [kubermatic/kubermatic#12922]
### What happened?

If cilium is used together with Tunneling, we some instable network and if we disable enbeded envoy some issues with the envoy of cilium as they use the same envoy base ID as we use for our tunneling envoys will appear:

If the envoy enabled via values the error get visible:
```yaml
envoy:
  enabled: true
```
the following error makes it visible:
```
k logs cilium-envoy-bqsmg -p
[2023-12-14 15:34:09.986][1][debug][init] [external/envoy/source/common/init/watcher_impl.cc:31] init manager Server destroyed
unable to bind domain socket with base_id=0, id=0, errno=98 (see --base-id option)

k get pods -n kube-system
cilium-4sjxw                          1/1     Running            0               4m40s
cilium-envoy-bqsmg                    0/1     CrashLoopBackOff   5 (98s ago)     4m41s
cilium-envoy-gw7cf                    0/1     CrashLoopBackOff   5 (79s ago)     4m41s
cilium-operator-8567c6c78b-tqstj      1/1     Running            2 (5m57s ago)   43m
cilium-wb756                          1/1     Running            0               4m40s
```

If you enable the ingress, component:
```yaml
ingressController:
  enabled: true
  loadbalancerMode: shared
  default: true
  enforceHttps: false
```
you will see that communication is somehow broken an e.g. the ingress will deliver empty reply from server:
```
curl -v a1324f042ff6b4055af94959460afa2d-794591813.eu-central-1.elb.amazonaws.com/test
*   Trying 52.28.81.117:80...
* Connected to a1324f042ff6b4055af94959460afa2d-794591813.eu-central-1.elb.amazonaws.com (52.28.81.117) port 80
> GET /test HTTP/1.1
> Host: a1324f042ff6b4055af94959460afa2d-794591813.eu-central-1.elb.amazonaws.com
> User-Agent: curl/8.4.0
> Accept: */*
> 
* Empty reply from server
* Closing connection
curl: (52) Empty reply from server
```
### Expected behavior
Tunnenling and cilium works nicely together and has different base IDs

### How to reproduce the issue?

Create a cilium cluser with tunnling and set above mention values to the system application
<img width="579" alt="Cluster 'hardcore-hodgkin-cilium-ingress-test-b2vxk8vnm5' in Project 'Tobi's Demo Project 🚀' 2023-12-14 16-28-06" src="https://github.com/kubermatic/kubermatic/assets/4659261/aa4361b5-b290-41f9-8c81-94b64152146b">

### How is your environment configured?

- KKP version: `2.24.0`
- Shared or separate master/seed clusters?: shared with `Tunneling` Expose Strategy

### Provide your KKP manifest here (if applicable)

https://github.com/kubermatic/sig-cs-infra/tree/main/lab.kubermatic.io

<details>

```yaml
# paste manifest here
```

</details>

### What cloud provider are you running on?

tested on AWS 

### What operating system are you running in your user cluster?
Ubuntu

### Additional information

Somehow, the Cilium Envoy is set via the operator to the command args of the cilium-envoy. So it's may easier we choose an alternative base-id:
`kubectl edit ds cilium-envoy`:
```yaml
  containers:
  - args:
    - -c /var/run/cilium/envoy/bootstrap-config.json
    - --base-id 0
    ...
    image: quay.io/cilium/cilium-envoy:v1.25.10-f71a313bd0daee41470af31ce6ea20c750fe35dd@sha256:bfa1e919ed02afc66e9ff36c1fd9148237fc8b8560a0b44d89acf144b0ffb08c
```
