### ISSUE TITLE
offline_access blocks usage of OIDC Kubeconfig, WebTerminal and Dashboard

### ISSUE THREAD

**Issue by oliverbaehler** [kubermatic/kubermatic#12931]
### Expected behavior

We are trying to connect OIDC to our Keycloak instance (without using dex). However we run into issues with the OIDC offline_access claim.

We have created to clients on the keycloak instance `kubermatic` and `kubermatic-ui`. They both are pretty much default with implicit flow being enabled and additionally groups sent in the scope.  I can log into the KKP dashboard, but when we try to get the kubeconfig for a cluster, we are met with the following error:

```
{"error":{"code":400,"message":"error while exchanging oidc code for token: oauth2: \"not_allowed\" \"Offline tokens not allowed for the user or client\""}}
```

Keycloak logs: 

```
023-12-30 09:46:01,101 WARN  [org.keycloak.events] (executor-thread-259) type=CODE_TO_TOKEN_ERROR, realmId=buttah-identity, clientId=kubermatic, userId=bce7e82f-636e-48e1-9329-a296ff086765, ipAddress=127.0.0.1, error=not_allowed, grant_type=authorization_code, code_id=ca8cce31-0c19-4a97-a313-5a49225c3dfd, client_auth_method=client-secret
```

Alright so the obv. thing to do, is to remove the `offline_access` from the token.  So we removed `offline_access` from the `kubermatic` client.  If we try to access the kubeconfig again:

```
{"error":{"code":500,"message":"OIDC provider error invalid_scope: Invalid scopes: openid email groups offline_access"}}
```

Keycloak logs:

```
2023-12-30 09:34:47,357 ERROR [org.keycloak.services] (executor-thread-259) KC-SERVICES0093: Invalid parameter value for: scope
2023-12-30 09:34:47,360 WARN  [org.keycloak.events] (executor-thread-259) type=LOGIN_ERROR, realmId=buttah-identity, clientId=kubermatic, userId=null, ipAddress=127.0.0.1, error=invalid_request, response_type=code, redirect_uri=https://cluster-test.svc.buttah.cloud/api/v1/kubeconfig, response_mode=query
```

It looks like to me, there's somehow a problem with the scope request. Since offline_access is requested but not allowed. I am not a keycloak pro, so there might be a big chance the clients are missing some configuration. If so, could you share the configuration for the clients you are using?

### How to reproduce the issue?

Described as above.

### How is your environment configured?

- KKP version: 2.24.1
- Shared or separate master/seed clusters?: Shared

### Provide your KKP manifest here (if applicable)

<details>

```yaml
apiVersion: kubermatic.k8c.io/v1
kind: KubermaticConfiguration
metadata:
  name: kubermatic
  namespace: kubermatic
spec:
  exposeStrategy: Tunneling
  featureGates:
    # exposes an HTTP endpoint for generating kubeconfig
    # for a cluster that will contain OIDC tokens
    OIDCKubeCfgEndpoint: true
    # configures the flags on the API server to use
    # OAuth2 identity providers
    OpenIDAuthPlugin: true
    UserClusterMLA: true
  ingress:
    domain: kubermatic
    certificateIssuer:
      apiGroup: null
      kind: ClusterIssuer
      name: "cloudflare"
    className: ingress-internal
  ui:
    config: |
      {
        "share_kubeconfig": true,
        "oidc_provider": "keycloak",
        "oidc_provider_url": "https://keycloak/realms/buttah-identity/protocol/openid-connect/auth",
        "oidc_provider_scope": "openid email profile roles",
        "oidc_provider_client_id": "kubermatic-ui",
        "oidc_connector_id": "github",
        "oidc_logout_url": "https://keycloak/realms/buttah-identity/protocol/openid-connect/logout"
      }     

  # These secret keys configure the way components communicate with Dex.
  auth:
    tokenIssuer: 'https://keycloak/realms/buttah-identity'
    clientID: kubermatic-ui
    issuerClientID: kubermatic
    skipTokenIssuerTLSVerify: false
    issuerRedirectURL: https://kubermatic/api/v1/kubeconfig
    issuerClientSecret: X
    issuerCookieKey: X
    serviceAccountKey: X
```

</details>

### What cloud provider are you running on?

Kubevirt

### What operating system are you running in your user cluster?

Flatcar

### Additional information

I can test anything or even providew you with keycloak clients on our keycloak instance.

**Comment by oliverbaehler** [comment]
Also tried to configure on seed level:

```
apiVersion: kubermatic.k8c.io/v1
kind: Seed
metadata:
  name: kubermatic
  namespace: kubermatic
  labels:
    kustomize.toolkit.fluxcd.io/substitute: disabled
spec:
  # these two fields are only informational
  country: CH
  location: Wabern
  oidcProviderConfiguration:
    issuerURL: https://keycloak/realms/buttah-identity
    offlineAccessAsScope: false
    issuerClientID: kubermatic
    issuerClientSecret: x
    cookieSecureMode: true
    cookieHashKey: x
  ```
  
  Result is the same
