### ISSUE TITLE
Make vsphere templates configurable

### ISSUE THREAD

**Issue by alvaroaleman** [kubermatic/kubermatic#1297]
Currently the vsphere template name is a free-text field, we should adjust this to be a configured list, e.G. via frontend config from the backend

**Comment by mrIncompetent** [comment]
We could make this configurable in the datacenters.yaml:
```yaml
vsphere-hetzner:
  location: Hetzner
  seed: europe-west3-c
  country: DE
  provider: Loodse
  spec:
    vsphere:
      endpoint: "https://vcenter.loodse.com"
      datacenter: "Datacenter"
      datastore: "datastore1"
      cluster: "loodse-cluster"
      allow_insecure: true
      images:
        - type: coreos
          name: coreos_stable
        - type: ubuntu
          name: ubuntu_cloud_image
        - type: centos
          name: centos_cloud_image
```

We could make this available via the datacenters-endpoint.

But IMO it should still be possible to overwrite the possibilities (Due to special network configuration which mus be done on the template)

Same applies for OpenStack
