### ISSUE TITLE
Test Applications - ValuesBlock Change - Test Release 2.25

### ISSUE THREAD

**Issue by SimonTheLeg** [kubermatic/kubermatic#13096]
**What needs to be done**
1. Create an AppInstall via GitOps and set the Values Field 
2. Modify the values via the UI or API
3. Verify that in the AppInstall in Kubernetes the Values have been moved from Values to ValuesBlock field.
4. Verify that the App is still installed correctly

**Comment by akash-gautam** [comment]
On modifying the values from GUI it see the parameters moving from `values` to `valuesBlock` in the applicationinstallation of the application:
```
  values: {}
  valuesBlock: |
    server:
      replicas: 3
      ingress:
          enabled: true
      service:
        type: LoadBalancer
```

**Comment by akash-gautam** [comment]
But currently, none of the values seems to get passed to the applications helm chart, for example, I deployed argocd app which has a default values block 
```
  defaultValues:
    server:
      service:
        # To Expose ArgoCD externally without ingress, set service type as "LoadBalancer". Default value is "ClusterIP".
        type: "LoadBalancer"
```
But service of type LoadBalancer is not created
```
$ k get svc -n argocd
NAME                                      TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)             AGE
argocd-argocd-applicationset-controller   ClusterIP   10.240.24.222   <none>        7000/TCP            4h45m
argocd-argocd-dex-server                  ClusterIP   10.240.25.144   <none>        5556/TCP,5557/TCP   4h45m
argocd-argocd-redis                       ClusterIP   10.240.27.171   <none>        6379/TCP            4h45m
argocd-argocd-repo-server                 ClusterIP   10.240.25.173   <none>        8081/TCP            4h45m
argocd-argocd-server                      ClusterIP   10.240.23.19    <none>        80/TCP,443/TCP      4h45m
```
I then updated the values block to enable ingress & increase the replicas of argocd server to 3 but that didn't had any impact either
```
$ k get ing,pods -n argocd
NAME                                                          READY   STATUS    RESTARTS   AGE
pod/argocd-argocd-application-controller-0                    1/1     Running   0          4h55m
pod/argocd-argocd-applicationset-controller-649967c5d-tshnh   1/1     Running   0          4h55m
pod/argocd-argocd-dex-server-75cb676754-g422b                 1/1     Running   0          4h55m
pod/argocd-argocd-notifications-controller-69f454b6c5-jwn9c   1/1     Running   0          4h55m
pod/argocd-argocd-redis-6f4865684f-wpdt6                      1/1     Running   0          4h55m
pod/argocd-argocd-repo-server-8448b46747-gq75n                1/1     Running   0          4h55m
pod/argocd-argocd-server-5bdb57df4d-sqtkj                     1/1     Running   0          4h55m
```
If I try to get the values from the helm release then that also returns null

```
$ helm get values argocd-argocd -n argocd
USER-SUPPLIED VALUES:
null
```
I think we have a bug here @csengerszabo @SimonTheLeg
