### ISSUE TITLE
OIDC authentication against UC apiserver broken if custom ingress controller is used

### ISSUE THREAD

**Issue by judge-red** [kubermatic/kubermatic#13117]
### What happened?

So not too long ago, KKP started allowing bringing your own ingress controller. And it's working just fine, except the UC apiserver can't access dex to enable oidc authentication.

The log keep showing this error:
```
oidc authenticator: initializing plugin: Get "https://$DOMAIN/.well-known/openid-configuration": context deadline 
exceeded (Client.Timeout exceeded while awaiting headers)     
```

The problem lies in the `oidc-issuer-allow` NetworkPolicy:
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: oidc-issuer-allow
  namespace: cluster-kw7q55pgll
spec:
  egress:
  - to:
    - ipBlock:
        cidr: 86.119.65.191/32
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: nginx-ingress-controller
  podSelector:
    matchLabels:
      app: apiserver
  policyTypes:
  - Egress
```

As you can see, it only allows access to (Dex via) the ingress controller - or rather its namespace. Well, no ingress controller other than the KKP-provided one sets the `kubernetes.io/metadata.name: nginx-ingress-controller` label!

I created this NetworkPolicy in addition and now it works for this UC:
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: oidc-issuer-allow-test
  namespace: cluster-kw7q55pgll
spec:
  egress:
  - to:
    - ipBlock:
        cidr: 86.119.65.191/32
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: ingress-nginx
  podSelector:
    matchLabels:
      app: apiserver
  policyTypes:
  - Egress
```

As you can see, we're using the upstream ingress-nginx Helm chart (as an intermediary step, the end goal is to use the Cilium  built-in ingress controller).

### Expected behavior

OIDC authentication against the UC apiserver works with any ingress controller

### How to reproduce the issue?

- deploy KKP without the nginx-ingress-controller Helm chart
- deploy any other ingress-controller
- try accessing a UC using a downloaded OIDC kubeconfig

### How is your environment configured?

- KKP version: 2.24.2 EE
- Shared or separate master/seed clusters?: shared

### Provide your KKP manifest here (if applicable)

N/A

### What cloud provider are you running on?

OpenStack

### What operating system are you running in your user cluster?

Ubuntu 22.04
