### ISSUE TITLE
Frequent failures of cilium application's upgrade

### ISSUE THREAD

**Issue by akash-gautam** [kubermatic/kubermatic#13125]
### What happened?
After upgrading KKP, newer versions of cilium CNI were available for the user cluster but after performing the upgrade through UI we observed frequent failures, sometimes the upgrade went through but still the cilium application installation showed error.

### Expected behavior
When newer version of the CNI is available we should be able to upgrade without any issues.

### How to reproduce the issue?
The bug is not consistently reproducible but is happening quite frequently.

### How is your environment configured?

- KKP version: 2.23.9 & 2.24.3

### Provide your KKP manifest here (if applicable)

<details>

```yaml
```

</details>

### What cloud provider are you running on?
Azure & Vsphere

### What operating system are you running in your user cluster?
Ubuntu

### Additional information
The error message on applicationinstallation object is `message: another operation (install/upgrade/rollback) is in progress` 
```
    Ready:
      lastHeartbeatTime: "2024-02-23T08:55:32Z"
      lastTransitionTime: "2024-02-23T08:55:32Z"
      message: another operation (install/upgrade/rollback) is in progress
      observedGeneration: 3
      reason: InstallationFailed
      status: "False"
```
once this state is reached it never recovers & the only way out is to delete and re-create the app.
