### ISSUE TITLE
air-gapped - kkp cilium CNI: hubble container images ignored with overwriteRegistry   

### ISSUE THREAD

**Issue by renelehmann** [kubermatic/kubermatic#13136]
### What happened?

After applying an updated kkp config with "overwriteRegistry" the hubble-ui images overwrite is ignored.

On a newly created user cluster, the worker nodes lists the two hubble images wrongly pulled form from the original registry.
The hubble-relay image was correctly pulled from the defined local registry set with the overwriteRegistry.

```
# cilium CNI images on worker node. hubble-ui and hubble-ui-backend images from upstream!
ubuntu@lucid-varahamihira-57467f7875-5qwzx:~$ sudo crictl images | grep cilium
quay.io/cilium/hubble-ui-backend                                            <none>              b599a0e0d6927       17MB
quay.io/cilium/hubble-ui                                                    <none>              fcdd1b69b2df9       22.7MB
myregistry.com/cilium/certgen                                               v0.1.9              28b1dbaa28193       23MB
myregistry.com/cilium/cilium                                                v1.14.3             bcfbf725bad20       184MB
myregistry.com/cilium/hubble-relay                                          v1.14.3             7c58c9e6eff38       21.8MB
myregistry.com/cilium/operator-generic                                      v1.14.3             864b88d44ea85       25.2MB 
```

Looking into the cilium config of the system application on the newly created user cluster:
```
# cilium app definition (System application)
hubble:
  relay:
    image:
      repository:
        myregistry.com/cilium/hubble-relay
  ui:
    backend: {}
    enabled: true
    frontend: {}
```

### Expected behavior

These two images form the cilium CNI system application should be pulled from the registry set with the kkp "overwriteRegistry" property.

The value should be set on:
hubble.ui.backend.image
hubble.ui.frontend.image

### How is your environment configured?

- KKP version: 2.24.2
- Shared or separate master/seed clusters?:  shared

### Provide your KKP manifest here (if applicable)

```yaml
spec:
  userCluster:
    overwriteRegistry: myregistry.com
```

### Additional information
At the code it looks like the overwriteRegistry should take place but it doesn't:
https://github.com/kubermatic/kubermatic/blob/v2.24.2/pkg/cni/cilium/cilium.go
