### ISSUE TITLE
AWS CCM crash loops after upgrade to v2.25.0-beta.2 and cloud spec cannot be upgraded

### ISSUE THREAD

**Issue by embik** [kubermatic/kubermatic#13144]
### What happened?

When upgrading KKP with an AWS user cluster present, the AWS CCM starts crash looping after the KKP upgrade:

```
F0301 10:58:40.691451       1 main.go:106] Cloud provider could not be initialized: could not init cloud provider "aws": unable to create sts client, incorrect ARN format for role kubernetes-bwfnsv2mkk-control-plane
```

The cloud spec looks like this post-upgrade:

```yaml
cloud:
    aws:
      credentialsReference:
        name: credential-aws-bwfnsv2mkk
        namespace: kubermatic
      instanceProfileName: kubernetes-bwfnsv2mkk
      nodePortsAllowedIPRanges:
        cidrBlocks: []
      roleARN: kubernetes-bwfnsv2mkk-control-plane
      routeTableID: rtb-<id>
      securityGroupID: sg-<id>
      vpcID: vpc-<id>
    dc: aws-eu-central-1a
    providerName: aws
```

@xrstf implemented cloud provider reconciliation that updates the cloud spec field for the AWS role, but that has two problems:

1. It takes up to 6 hours for cloud provider reconciliation to run; that's not acceptable since the CCM will be down for up to 6 hours.
2. The field is immutable, if the cloud provider reconciliation is triggered, it fails with the following error:

```json
{"level":"error","time":"2024-03-01T11:04:45.114Z","caller":"controller/controller.go:266","msg":"Reconciler error","controller":"kkp-cloud-controller","object":{"name":"bwfnsv2mkk"},"namespace":"","name":"bwfnsv2mkk","reconcileID":"c5d76027-2bcf-4a1b-8793-e7d38878caae","error":"failed cloud provider init: admission webhook \"clusters.kubermatic.io\" denied the request: spec.cloud: Forbidden: updating AWS control plane ARN is not supported (was kubernetes-bwfnsv2mkk-control-plane, updated to arn:aws:iam::533267092196:role/kubernetes-bwfnsv2mkk-control-plane)","errorCauses":[{"error":"failed cloud provider init: admission webhook \"clusters.kubermatic.io\" denied the request: spec.cloud: Forbidden: updating AWS control plane ARN is not supported (was kubernetes-bwfnsv2mkk-control-plane, updated to arn:aws:iam::<id>:role/kubernetes-bwfnsv2mkk-control-plane)"}]}
```

### Expected behavior

AWS CCM runs fine and is automatically migrated.

### How to reproduce the issue?

1. Set up KKP v2.24.4.
2. Create AWS user cluster.
3. Upgrade KKP to v2.25.0-beta.2.
4. Observe crashing AWS CCM.
5. Attempt to update the `status.pastProviderReconciliation` with `kubectl edit-status` (requires a kubectl plugin) to something older than 6 hours to see the seed-controller-manager failing to reconcile cloud provider.

### How is your environment configured?

- KKP version: v2.25.0-beta.2
- Shared or separate master/seed clusters?: shared

### Provide your KKP manifest here (if applicable)

<details>

```yaml
# paste manifest here
```

</details>

### What cloud provider are you running on?

AWS

### What operating system are you running in your user cluster?

N/A
