### ISSUE TITLE
KubermaticConfiguration ImagePullSecret is not Used

### ISSUE THREAD

**Issue by MAttia2022** [kubermatic/kubermatic#13251]
We have ImagePullSecret configured in the KubermaticConfiguration object however, this is not being used for the deployment of the Envoy Proxy to the clusters. We encountered rate limit issue with dockerhub because of that and hence the Envoy is not deployed and requested clusters are not running.

Here's a snippet of our KubermaticConfiguration resource:

```yaml
apiVersion: [kubermatic.k8c.io/v1](http://kubermatic.k8c.io/v1)
kind: KubermaticConfiguration
metadata:
  name: kubermatic
  namespace: kubermatic
spec:
  …..
  imagePullSecret: ‘{“auths”:{“[docker.io](http://docker.io/)”:{“username”:“xxxxxx”,“password”:“yyyyy,“email”:“.”,“auth”:“xxxxx”}}}’ 
```

### Expected behavior

The imagePullSecret to be used in the deployment of Kubermatic components.

### How to reproduce the issue?

Add the ImagePullSecret to the KubermaticConfiguration and see if they are ejected to the EnvoyProxy DaemonSet.

### How is your environment configured?

- KKP version: 2.23.5
- Shared or separate master/seed clusters?: Shared

### Provide your KKP manifest here (if applicable)

```yaml
apiVersion: [kubermatic.k8c.io/v1](http://kubermatic.k8c.io/v1)
kind: KubermaticConfiguration
metadata:
  name: kubermatic
  namespace: kubermatic
spec:
  …..
  imagePullSecret: ‘{“auths”:{“[docker.io](http://docker.io/)”:{“username”:“xxxxxx”,“password”:“yyyyy,“email”:“.”,“auth”:“xxxxx”}}}’ 
```

### What cloud provider are you running on?
AWS

### What operating system are you running in your user cluster?

Flatcar
