### ISSUE TITLE
Provide a merged/unified kubeconfig for all the clusters a user has access to

### ISSUE THREAD

**Issue by SamuAlfageme** [kubermatic/kubermatic#13410]
### Description of the feature 

Since Dex only allows one refresh token per user (https://github.com/dexidp/dex/issues/981), managing multiple user clusters in KKP from the CLI by downloading their kubeconfigs becomes [toil](https://sre.google/workbook/eliminating-toil/). It requires some non-intuitive, manual steps as every kubeconfig generated invalidates the previous `refresh-token`: 

```diff
stalk -n oauth refreshtokens.dex.coreos.com
--- (none)
+++ RefreshToken oauth/pkl4tzhi27hjtf6pmxrfkca6n v706531878 (2024-05-28T16:10:27+02:00) (gen. 1)
@@ -0 +1,26 @@
+CreatedAt: "2024-05-28T14:10:27.870883109Z"
[...]
+token: ghwdtfrtw7h7b3zs5d5a7js23

--- RefreshToken oauth/ekoyfywgnlrm67ez3rflpmxt5 v706531881 (2024-05-28T16:10:27+02:00) (gen. 1)
+++ (none)
@@ -1,26 +0 @@
-CreatedAt: "2024-05-28T14:09:03.869115595Z"
[...]
-token: ppi66f4sakergbzanrl5i67r3
```

I think KKP could provide an _"all-in-one"_ kubeconfig with one context per user cluster to simplify this scenario.

- As a KKP end-user,
- I would like to download a single kubeconfig file that contains the contexts to access all my UCs.
- to simplify the process of **downloading the individual kubeconfig files and [merging them]((https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/#merging-kubeconfig-files)), while keeping a valid `user.auth-provider.config`**.

### Solution details

- The _all-in-one_ kubeconfig should contain all the `clusters` the user has access to in KKP.
- The cluster/context `.name` should be human-readable (not the kubermatic id).
- The `user.auth-provider.config` section should contain a valid `refresh-token`.

Here's an example of a user who has access to two clusters in all his projects: 

```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: []
    server: https://er9q6sfwf5.<KKP>:6443
  name: er9q6sfwf5
- cluster:
    certificate-authority-data: []
    server: https://k8hzznh2ch.<KKP>:6443
  name: k8hzznh2ch
contexts:
- context:
    cluster: k8hzznh2ch
    user: samuel.alfageme@gmail.com
  name: laughing-lovelace
- context:
    cluster: er9q6sfwf5
    user: samuel.alfageme@gmail.com
  name: vigilant-wiles
current-context: vigilant-wiles
kind: Config
preferences: {}
users:
- name: samuel.alfageme@gmail.com
  user:
    auth-provider:
      config:
        client-id: kubermaticIssuer
        client-secret: [...]
        id-token: [...]
        idp-issuer-url: https://<IDP>
        refresh-token: [...]
      name: oidc
```

### Alternative approaches

To further circumvent Dex's limitation, this _all-in-one_ kubeconfig could be the one globally provided for a user by the "Get Kubeconfig" button on the KKP dashboard. Altering the active context to match the cluster from which the kubeconfig was requested on the web UI: 

![vigilant-wiles](https://github.com/kubermatic/kubermatic/assets/2644445/ec9c6ab8-2b90-4ba9-9b9a-455c728d3078)

Will download: 

```yaml
apiVersion: v1
clusters:
[...]
current-context: vigilant-wiles
[...]
```

The web terminal could also reuse this kubeconfig to authenticate the user against the cluster, rather than generating a new one for every new session.

### Use cases

This is the result of using above's Kubeconfig (generated manually) in combination with [`kubectx`](https://github.com/ahmetb/kubectx) and [`fzf`](https://github.com/junegunn/fzf) to simplify cluster-switching:

[![asciicast](https://asciinema.org/a/RNERrUoZnXGbly1DcuRc5prz2.svg)](https://asciinema.org/a/RNERrUoZnXGbly1DcuRc5prz2)

### Additional information

Note that: opening a new web terminal or downloading a new config file after generating this "_all-in-one_" kubeconfig **would still invalidate its refresh token with a new one** due to the original Dex limitation.
