### ISSUE TITLE
Configuring LoadBalancer type for API Server 

### ISSUE THREAD

**Issue by ahmedwaleedmalik** [kubermatic/kubermatic#13584]
### What happened?

We added the support to configure **type** for the `apiserver-external` service of user clusters through https://github.com/kubermatic/kubermatic/pull/13562. The functionality is working as expected, although there are errors in the UI, specifically in the cluster status. This seems like a transient error with the cache but also could be a genuine issue somewhere.

```
  errorMessage: 'failed to ensure Service cluster-hthltqtwgb/apiserver-external: failed
    waiting for the cache to contain our latest changes: context deadline exceeded'
  errorReason: ReconcileError
```

### How to reproduce the issue?

Configure a datacenter as the following:

```yaml
gcp-westeurope:
  country: DE
  location: Europe West (Germany)
  spec:
    apiServerServiceType: LoadBalancer
```

Create a new cluster, check it's status from CLI and UI.

### How is your environment configured?

- KKP version: development
- Shared or separate master/seed clusters?: shared/doesn't matter

/milestone KKP 2.26
