### ISSUE TITLE
Add support for seed-cluster DNS overwrite in datacenters.yaml

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#1358]
**Current state**:
Having this datacenters.yaml:
```yaml
datacenters:
#===============Seed===============
  europe-west3-c: #Master
    location: Frankfurt
    country: DE
    provider: Loodse
    is_seed: true
    spec:
      bringyourown:
        region: DE
      seed:
        bringyourown:
#===========Digitalocean===========
  do-ams3:
    location: Amsterdam
    seed: europe-west3-c
    country: NL
    spec:
      digitalocean:
        region: ams3
```

The cluster-controller runs with the flag `-external-url=kubermatic.foo.com`.
Every Digitalocean cluster with the node-Datacenter `do-ams3` will run inside the seed-Datacenter `europe-west3-c`. 
Thus the external-domain for clusters will be:
`cluster-name.europe-west3-c.kubermatic.foo.com`

A DNS entry exist to point `*.europe-west3-c.kubermatic.foo.com` to IP `192.168.10.15`
`192.168.10.15` Is either a LoadBalancer or a worker node of the seed-cluster.
Via this LB or worker node the apiserver of all user-clusters will be exposed to the outside.

For each cluster, the cluster-controller looks up the IP for the external name of the cluster & will configure it as the `-advertise-address` on the kubernetes-apiserver.
This address will later be used inside the users-cluster (every pod inside the cluster can call `kubernetes.local` which will finally resolve to `192.168.10.15`).

**Problem**
In some environments the seed-cluster worker nodes (or LB) won't be reachable by nodes from some node-datacenter's.
For example if the seed-cluster is located in a very restricted network.
In those scenarios customers might setup a proxy host (IP: `90.187.32.181`), which only proxies specific ports from the outside to the seed-cluster. That way the seed-cluster would be made available from the outside.

The issue here is, that the controller still would get `192.168.10.15` as `-advertise-address`.
As this IP is not accessable from the node-datacenter, all in-cluster pod->apiserver communication won't work.

**Possible solution**
It should be possible in each node-datacenter to specify an optional DNS overwrite (`seed_dns_overwrite: "europe-west3-c-external"`).
For example:
```yaml
#===========Digitalocean===========
  do-ams3:
    location: Amsterdam
    seed: europe-west3-c
    country: NL
    seed_dns_overwrite: "europe-west3-c-external"
    spec:
      digitalocean:
        region: ams3
```

A wildcard DNS entry would now need to exist for `*.europe-west3-c-external.kubermatic.foo.com` which points to the proxy host: IP: `90.187.32.181`

**Comment by alvaroaleman** [comment]
If we allow already overwrites, wouldn't it be better to use that override for the full dns name?

E.G. then an overwrite would look like `seed_dns_overwrite: "my-seed.company.com"`

**Comment by alvaroaleman** [comment]
But to go a step back: Why wouldn't it be possible to rename the `seed dc`, in your example like this:

```
#===========Digitalocean===========
europe-west3-c-external:
    location: Amsterdam
    seed: europe-west3-c
    country: NL
    spec:
      digitalocean:
        region: ams3
```

**Comment by mrIncompetent** [comment]
> But to go a step back: Why wouldn't it be possible to rename the seed dc, in your example like this:
```yaml
#===========Digitalocean===========
europe-west3-c-external:
    location: Amsterdam
    seed: europe-west3-c
    country: NL
    spec:
      digitalocean:
        region: ams3
```

In your example, you're just renaming the node-dc :thinking: This would not have any effect, as the externalName for a cluster gets generated by:
`<cluster-name>.<see-dc-name>.<external-url-flag>`

**Comment by alvaroaleman** [comment]
Oh sorry. Well, rename the seed dc then:

```
#===========Digitalocean===========
  do-ams3:
    location: Amsterdam
    seed: europe-west3-c-external
    country: NL
    spec:
      digitalocean:
        region: ams3
```

**Comment by mrIncompetent** [comment]
`seed: europe-west3-c-external` is a reference to:
```yaml
datacenters:
#===============Seed===============
  europe-west3-c: #Master
    location: Frankfurt
    country: DE
    provider: Loodse
    is_seed: true
    spec:
      bringyourown:
        region: DE
      seed:
        bringyourown:
```

Ok, in this case, the reference is broken.
