### ISSUE TITLE
kubermatic and dex ingresses have unnecessarily define a defaultBackend

### ISSUE THREAD

**Issue by judge-red** [kubermatic/kubermatic#13649]
### What happened?

The behavior of the `defaultBackend` of ingresses seems to be badly defined / too vague in Kubernetes, and thus different ingress controllers have implemented it differently (I've verified this with ingress-nginx and Cilium) - probably despite being conformant.

Specifically a `defaultBackend` doesn't define a host. Now Cilium assumes that every `defaultBackend` should apply to all hosts (i.e. `*`) while ingress-nginx assumes that the `defaultBackend` should apply to the `/` path prefix of every host defined in the same ingress (and will be overwritten if a rule for the `/` path/prefix exists). Long story short, `defaultBackend` is (probably unintentionally so) implementation specific.

However, a `defaultBackend` is only required, if no rules are defined in an ingress (and in this specific case ingress-nginx and Cilium behave the same afaict). As soon as a single rule is defined in the ingress, the `defaultBackend` becomes optional.

KKP deploys two ingresses by default: `kubermatic` and `dex`. Both have a rule for the `/` path, so a `defaultBackend` seems to be completely unnecessary. Yet both have a `defaultBackend` specified. It's not quite clear why, but as far as I can tell the people who implemented the ingresses thought it would be good to have a fallback for when no rule matches, but since there is a rule for the `/` path this is never necessary afaict.

For example, this is the result of the two defaultBackends in KKP with Cilium:
```
    - '@type': type.googleapis.com/envoy.config.route.v3.RouteConfiguration
      name: listener-insecure
      virtualHosts:
      - domains:
        - '*'
        name: '*'
        routes:
        - match:
            prefix: /
          route:
            maxStreamDuration:
              maxStreamDuration: 0s
            weightedClusters:
              clusters:
              - name: kubermatic:kubermatic-dashboard:80
                weight: 1
              - name: oauth:dex:5556
                weight: 1
```

As you can see, they're both set up for the `/` path on the `*` host/domain with an equal weight. Luckily there are specific rules for the `/` at all hosts/domain that that KKP cares about, so this is of no consequence. But we could need to deploy an ingress on an additional domain with just a rule for the path `/foo` and then visitors to `/` on that domain would end up with the KKP dashboard or dex randomly!

Thus, to avoid problems due to relying on something that is de-facto implementation specific, I think using `defaultBackend` for no reason is a bug in KKP and both should be removed completely.

### Expected behavior

`kubermatic` and `dex` Ingresses should not specify a `defaultBackend` as it's not required and dangerous due to the fact that implementation depends on the ingress controller.

### How to reproduce the issue?

Deploy KKP and look at the manifests of the `kubermatic` and `dex` ingresses.

Also you can create the `kubermatic` ingress once with ingressClass nginx and once with cilium, if you have both ingress controllers installed, and then compare the nginx config with the envoy config if you want to see how their implementation differs.

### How is your environment configured?

- KKP version: 2.25.8
- Shared or separate master/seed clusters?: shared

### Provide your KKP manifest here (if applicable)

N/A

### What cloud provider are you running on?

N/A

### What operating system are you running in your user cluster?

N/A

### Additional information

As a side note, there's also currently a bug in Cilium. The presence of a defaultBackend in the `kubermatic` ingress results in the rule for the `/api` path prefix to be ignored completely. Thus the KKP dashboard is unusable with the Cilium ingress controller.
