### ISSUE TITLE
User clusters are not updated automatically when only `automaticNodeUpdate: true` is set

### ISSUE THREAD

**Issue by dakraus** [kubermatic/kubermatic#13669]
### What happened?

On page [Version & Update configuration](https://docs.kubermatic.com/kubermatic/v2.25/tutorials-howtos/administration/version-and-upgrade-configuration/) of the KKP documentation we state, that setting `automaticNodeUpdate: true` also implies an automatic control plane update (`automatic: true`). However, when defining an update with only `automaticNodeUpdate` set to true, the update fails with an error message (unfortunately I do not have the exact error message).

### Expected behavior

KKP should also update the control plane when `automaticNodeUpdate` is set to true

### How to reproduce the issue?

1. Define the following update in the `KubermaticConfiguration`
    ```yaml
    ...
    spec:
      versions:
        updates:
          - from: 1.28.6
            to: 1.28.7
            automaticNodeUpdate: true
    ...
    ```
1. Check the logs of the seed-controller-manager

### How is your environment configured?

- KKP version: 2.25.3
- Shared or separate master/seed clusters?: Separate master / seed cluster

### Provide your KKP manifest here (if applicable)

Not relevant

### What cloud provider are you running on?

vSphere

### What operating system are you running in your user cluster?

Not relevant

### Additional information
