### ISSUE TITLE
API server service type - Test Release 2.26

### ISSUE THREAD

**Issue by xrstf** [kubermatic/kubermatic#13755]
This is about testing https://github.com/kubermatic/kubermatic/pull/13562

## Steps

1. Configure a data center as the following:

```
gcp-westeurope:
  country: DE
  location: Europe West (Germany)
  spec:
    apiServerServiceType: LoadBalancer
```

2. Create a cluster.
3. Ensure that `apiserver-external` is of type LoadBalancer and has been assigned an IP.
4. Once the cluster is ready and all components are healthy. Check the cluster status and events to ensure that the following error is not there anymore w.r.t https://github.com/kubermatic/kubermatic/issues/13584
```
  errorMessage: 'failed to ensure Service cluster-hthltqtwgb/apiserver-external: failed
    waiting for the cache to contain our latest changes: context deadline exceeded'
  errorReason: ReconcileError
```
5. From CLI: Verify the `Cluster.Status.Address.APIServerExternalAddress` exists and points to the hostname or IPv4 IP of the `apiserver-external` service.
6. From UI: Download Kubeconfig(non-admin) for this cluster and make sure that the address for API server is same as `Cluster.Status.Address.APIServerExternalAddress`.

**Comment by ahmedwaleedmalik** [comment]
## Steps

1. Configure a data center as the following:

```
gcp-westeurope:
  country: DE
  location: Europe West (Germany)
  spec:
    apiServerServiceType: LoadBalancer
```

2. Create a cluster
3. Ensure that `apiserver-external` is of type LoadBalancer and has been assigned an IP
4. Once the cluster is ready and all components are healthy. Check the cluster status and events to ensure that the following error is not there anymore w.r.t https://github.com/kubermatic/kubermatic/issues/13584
```
  errorMessage: 'failed to ensure Service cluster-hthltqtwgb/apiserver-external: failed
    waiting for the cache to contain our latest changes: context deadline exceeded'
  errorReason: ReconcileError
```
5. From CLI: Verify the `Cluster.Status.Address.APIServerExternalAddress` exists and points to the domain or IPv4 IP for the load balancer
6. From UI: Download Kubeconfig(non-admin) for this cluster and make sure that the address for API server is same as `Cluster.Status.Address.APIServerExternalAddress`
