### ISSUE TITLE
Partially failing user cluster backups due to empty label selector

### ISSUE THREAD

**Issue by moelsayed** [kubermatic/kubermatic#13830]
### What happened?
User Cluster backups partially-fail when created via the UI. As a result, not all work loads are backed up. 

The following error can be seen in the `velero backup describe` command output:
```
message: /Error listing resources error: /found '<', expected: !, identifier, or 'end of string'
message: /Error listing resources error: /found '<', expected: !, identifier, or 'end of string'
message: /Error listing resources error: /found '<', expected: !, identifier, or 'end of string'
message: /Error listing resources error: /found '<', expected: !, identifier, or 'end of string'
message: /Error listing resources error: /found '<', expected: !, identifier, or 'end of string'
message: /Error listing resources error: /found '<', expected: !, identifier, or 'end of string'
message: /Error listing resources error: /found '<', expected: !, identifier, or 'end of string'
message: /Error listing resources error: /found '<', expected: !, identifier, or 'end of string'
message: /Error listing resources error: /found '<', expected: !, identifier, or 'end of string'
message: /Error listing resources error: /found '<', expected: !, identifier, or 'end of string'
message: /Error listing resources error: /found '<', expected: !, identifier, or 'end of string'
message: /Error listing resources error: /found '<', expected: !, identifier, or 'end of string'
message: /Error listing resources error: /found '<', expected: !, identifier, or 'end of string'
message: /Error listing resources error: /found '<', expected: !, identifier, or 'end of string'
message: /Error listing resources error: /found '<', expected: !, identifier, or 'end of string'
message: /Error listing resources error: /found '<', expected: !, identifier, or 'end of string'
message: /Error listing resources error: /found '<', expected: !, identifier, or 'end of string'
message: /Error listing resources error: /found '<', expected: !, identifier, or 'end of string'
```

### Expected behavior
Backups should complete successfully.

### How to reproduce the issue?
Create backup via the UI

### How is your environment configured?

- KKP version:
- Shared or separate master/seed clusters?:

### Provide your KKP manifest here (if applicable)

<details>

```yaml
# paste manifest here
```

</details>

### Additional information
The UI sends a few empty values in the backup spec:
```
spec:
  csiSnapshotTimeout: 10m0s
  defaultVolumesToFsBackup: false
  hooks: {}
  includedNamespaces:
  - cloud-init-settings
  - default
  - k8sgpt
  - kube-node-lease
  - kube-public
  - kube-system
  - kubernetes-dashboard
  - velero
  itemOperationTimeout: 4h0m0s
  labelSelector: {}
  metadata: {}
  snapshotMoveData: false
  storageLocation: default-cluster-backup-bsl
```

The main issue here is `labelSelector: {}` which is not supported by [Velero](https://github.com/vmware-tanzu/velero/issues/2083).
