### ISSUE TITLE
RBAC issue with csi-driver for kubevirt tenant cluster

### ISSUE THREAD

**Issue by redradrat** [kubermatic/kubermatic#13966]
csi-driver for kubevirt provider clusters is complaining about non-existing clusterRole `csi-controller`. There is none, but there is kubevirt-csi-controller.

```
csi-driver I0106 10:58:56.571789       1 controller.go:464] failed removing volume pvc-2a552866-acf8-4459-b8a6-3bd18c17f4ff from VM loving-poitras-65679c7b5d-qbz5g, err: virtualmachin
einstances.kubevirt.io "loving-poitras-65679c7b5d-qbz5g" is forbidden: User "system:serviceaccount:cluster-rl877lc7c6:kubevirt-csi" cannot get resource "virtualmachineinstances" in AP
I group "kubevirt.io" in the namespace "cluster-rl877lc7c6": RBAC: clusterrole.rbac.authorization.k8s.io "csi-controller" not found
```

1. Issue

The roleRef here should specify `resources.KubeVirtCSIClusterRoleName` instead of`resources.KubeVirtCSIControllerName`?

https://github.com/kubermatic/kubermatic/blob/25ed4f7ccd44d2be69c34e745c9bcb59ae1927fd/pkg/resources/csi/kubevirt/rbac.go#L170-L174

2. Issue

Additionally, the Role created for the cluster (`kubevirt-csi`), is lacking the `get` verb for `vmis`.

**Comment by toschneck** [comment]
For documentation:
Temporary patcher:
```
# TEMPORARY WORKAROUND for kubevirt CSI bug https://github.com/kubermatic/kubermatic/pull/13967
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubevirt-csi-rbac-patcher
  namespace: kubermatic
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubevirt-csi-rbac-patcher
  namespace: kubermatic
rules:
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "rolebindings"]
    verbs: ["get", "watch", "list", "create", "update"]
  - apiGroups: ["kubermatic.k8c.io"]
    resources: ["clusters"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["kubevirt.io"]
    resources: ["virtualmachineinstances"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubevirt-csi-rbac-patcher
  namespace: kubermatic
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubevirt-csi-rbac-patcher
subjects:
  - kind: ServiceAccount
    name: kubevirt-csi-rbac-patcher
    namespace: kubermatic
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubevirt-csi-rbac-patcher
  namespace: kubermatic
data:
  entrypoint.sh: |
    #!/usr/bin/env bash

    # Set up potential deps
    apk update
    apk add envsubst

    # https://github.com/flant/shell-operator/blob/master/Dockerfile#L40
    exec /sbin/tini -- /shell-operator start
  rbac.yaml: |
    ---
    apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      name: kubevirt-csi-vmis-rbac-patch
      namespace: cluster-${CLUSTER_ID}
      labels:
        kubermatic.k8c.io/app: kubevirt-csi-rbac-patcher
        kubermatic.k8c.io/cluster: cluster-${CLUSTER_ID}
    rules:
    - apiGroups:
      - kubevirt.io
      resources:
      - virtualmachineinstances
      verbs:
      - get
    ---
    apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      labels:
        kubermatic.k8c.io/app: kubevirt-csi-rbac-patcher
        kubermatic.k8c.io/cluster: cluster-${CLUSTER_ID}
      name: csi-controller-vmis-rbac-patch
      namespace: cluster-${CLUSTER_ID}
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: kubevirt-csi-vmis-rbac-patch
    subjects:
    - kind: ServiceAccount
      name: kubevirt-csi
      namespace: cluster-${CLUSTER_ID}
  patcher.sh: |
    #!/usr/bin/env bash

    get_obj() {
      type=$(jq -r .[0].type $BINDING_CONTEXT_PATH)
      case "$type" in
      Event)
        name=$(jq -r .[0].object.metadata.name $BINDING_CONTEXT_PATH)
        echo $(kubectl get cluster -n cluster-$name $name -ojson | jq -r [.])
        ;;
      Synchronization)
        echo $(jq -c '[.[0].objects[].object]' $BINDING_CONTEXT_PATH)
        ;;
      *)
        echo "Skipping trigger..."
        exit 0
        ;;
      esac
    }

    if [[ $1 == "--config" ]]; then
      cat <<EOF
    configVersion: v1
    kubernetes:
    - apiVersion: kubermatic.k8c.io/v1
      kind: Cluster
      executeHookOnEvent: ["Added", "Modified"]
    EOF
    else
      objs=$(get_obj)

      echo $objs | jq -c '.[] | {name: .metadata.name, providerName: .spec.cloud.providerName}' |
        while read -r obj; do
          name=$(echo $obj | jq -r .name)
          providerName=$(echo $obj | jq -r .providerName)
          echo "Reconciling cluster-$name/$name..."
          case $providerName in
          "kubevirt")
            CLUSTER_ID=$name envsubst </resources/rbac.yaml | kubectl apply -f -
            ;;
          "")
            echo "Could not parse provider name... invalid object"
            exit 1
            ;;
          *)
            echo "non-kubevirt cluster... skipping"
            ;;
          esac
        done

      echo "Reconiliation successful."
    fi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubevirt-csi-rbac-patcher
  namespace: kubermatic
  annotations:
    configmap.reloader.stakater.com/reload: "kubevirt-csi-rbac-patcher"
  labels:
    kubermatic.k8c.io/app: kubevirt-csi-rbac-patcher
spec:
  replicas: 1
  selector:
    matchLabels:
      kubermatic.k8c.io/app: kubevirt-csi-rbac-patcher
  template:
    metadata:
      labels:
        kubermatic.k8c.io/app: kubevirt-csi-rbac-patcher
    spec:
      serviceAccountName: kubevirt-csi-rbac-patcher
      volumes:
        - name: kubevirt-csi-rbac-patcher
          configMap:
            name: kubevirt-csi-rbac-patcher
            defaultMode: 0755
      containers:
        - name: kubevirt-csi-rbac-patcher
          image: flant/shell-operator:v1.5.2
          env:
            - name: LOG_TYPE
              value: text
          command:
            - /entrypoint.sh
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: kubevirt-csi-rbac-patcher
              subPath: patcher.sh
              mountPath: /hooks/patcher.sh
            - name: kubevirt-csi-rbac-patcher
              subPath: rbac.yaml
              mountPath: /resources/rbac.yaml
            - name: kubevirt-csi-rbac-patcher
              subPath: entrypoint.sh
              mountPath: /entrypoint.sh

```
