### ISSUE TITLE
Problems with separate ccm and infra users for vsphere

### ISSUE THREAD

**Issue by koksay** [kubermatic/kubermatic#13995]
### What happened?

We have some issues when using separate ccm and infra users as [documented](https://docs.kubermatic.com/kubermatic/v2.26/architecture/supported-providers/vsphere/#credentials--cloud-config)

The permissions seem to be working as there is not a problem while using it this way on KubeOne.

However, there are either query issues on the KKP UI (e.g. not being able to get network listing), or permission issues while creating the virtual machines. Here are different combinations I tired:

1. Provide ccm and infra users on the UI separately:

In this case, I believe the vsphere session is created via the ccm user, and it cannot get the network list and tags:

![Image](https://github.com/user-attachments/assets/2d0494b5-803d-4b42-bbd1-351a324280ee)

2. Provide infra user in the seed configuration, and ccm user on the UI:

```yaml
    vsphere-dc:
        vsphere:
          infraManagementUser:
            password: xxx
            username: kkp-demo-infra@vsphere.local
```
In this case, the query issues are resolved, as they session is executed by the infra user (and it has the necessary permissions)
Network, datastore. tags, vmgroups, all can be selected.

However, this time machine deployment creation fails:

```
failed cloud provider init: failed to reconcile cluster folder: failed to create the 
VM folder "xxx": couldn't find rootpath, see: NoPermission
```

When I check the events on vsphere side, I see that the infra user do not have `System.Read` permision against the `datacenter`:

```
Description:
Privilege check failed for user VSPHERE.LOCAL\kkp-demo-infra for missing permission System.Read. 
Session user performing the check: VSPHERE.LOCAL\kkp-demo-infra
```

I changed the infra user to admin on the seed side to continue. It is relatively safe as the credentials will be stored on the seed side. Then the Machine Deployment is created (together with the folder on the correct path), but get this error:

```
An error of type = InvalidConfiguration, with message = failed to create cloned vm: 
'failed to clone template vm: ServerFaultCode: Permission to perform this operation was denied.' occurred
```

When I check this on the vsphere events, I get this:

```
Description:
Privilege check failed for user VSPHERE.LOCAL\kkp-demo-ccm for missing permission 
VirtualMachine.Inventory.CreateFromExisting. Session user performing the check:
```

It's weird, because it's not resolved even if I provide this role (actually `k8c-user-datacenter` role to the ccm user). Another point I noticed in the message it that `Session user performing the check` is empty.

I also noticed that, when the infraManagementUser is provided on the seed configuration, the `cloud-credentials` secret is not populated with the user and it's empty:

```yaml
k get secret cloud-credentials -n cluster-xxx -o yaml
apiVersion: v1
data:
  infraManagementUserPassword: ""
  infraManagementUserUsername: ""
  password: yyy
  username: xxx
kind: Secret
metadata:
  name: cloud-credentials
  namespace: cluster-xxx
type: Opaque
```

### Expected behavior

We need separate users so that the one propagated to the user cluster will have only the required permissions. Customers are concerned that their customers will use those credentials to act against the vsphere setup.

### How to reproduce the issue?

Described above.

### How is your environment configured?

- KKP version: v2.26.2
- Shared or separate master/seed clusters?: shared

### Provide your KKP manifest here (if applicable)

<details>

```yaml
# paste manifest here
```

</details>

### What cloud provider are you running on?

VMware vSphere

### What operating system are you running in your user cluster?

Ubuntu 22.04
