### ISSUE TITLE
Node labels on the clustertemplate are not applied to the cluster

### ISSUE THREAD

**Issue by koksay** [kubermatic/kubermatic#14004]
### What happened?

I add node labels to the `clustertemplate`, they are not applied to the cluster. I guess, they are overridden while applying `system/cluster` and `system/project` labels.

Cluster Template view:

<img width="746" alt="Image" src="https://github.com/user-attachments/assets/ba8c5a39-c6c1-435a-8c52-bf7bfacf9665" />

Node Labels after cluster creation:

<img width="724" alt="Image" src="https://github.com/user-attachments/assets/5b119822-b942-403f-a068-021ab85b1ce5" />

### Expected behavior

Node labels defined in the template are added to the cluster.

### How to reproduce the issue?

1. Add node labels to a cluster template
2. Create a cluster with this template and check the labels.

### How is your environment configured?

- KKP version: v2.26.2
- Shared or separate master/seed clusters?: Shared

### Provide your KKP manifest here (if applicable)

Here is the part of `ClusterTemplate`:

<details>

```yaml
apiVersion: kubermatic.k8c.io/v1
clusterLabels:
  is-credential-preset: "true"
  type: demo
credential: credential-vsphere-sig-vsphere-vmgroup
kind: ClusterTemplate
metadata:
  annotations:
    kubermatic.io/initial-machinedeployment-request: |
      {
        "metadata": {
          "name": "sig-vsphere-vmgroup1-worker",
          "namespace": "kube-system",
          "annotations": {
            "k8c.io/operating-system-profile": "osp-ubuntu"
          },
          "finalizers": [
            "foregroundDeletion"
          ]
        },
        "spec": {
          "replicas": 1,
          "selector": {
            "matchLabels": {
              "machine": "md-sig-vsphere-vmgroup1"
            }
          },
          "template": {
            "metadata": {
              "labels": {
                "machine": "md-sig-vsphere-vmgroup1"
              }
            },
            "spec": {
              "metadata": {
                "labels": {
                  "system/cluster": "sig-vsphere-vmgroup1",
                  "topology.kubernetes.io/region": "eu-ham",
                  "topology.kubernetes.io/zone": "az-1",
                  "failure-domain.beta.kubernetes.io/region": "eu-ham",
                  "failure-domain.beta.kubernetes.io/zone": "az-1"
                }
              },
...
```

</details>
