### ISSUE TITLE
ArgoCD - Test Release 2.27

### ISSUE THREAD

**Issue by xrstf** [kubermatic/kubermatic#14094]

**Comment by ahmedwaleedmalik** [comment]
```
    - template:
        source:
          helm:
            chartName: argo-cd
            chartVersion: 7.7.17
            url: https://argoproj.github.io/argo-helm
      version: v2.13.4
```

Seems like a mismatch in chart version?
