### ISSUE TITLE
Scrape apiserver_storage_size_bytes by default when User Cluster MLA is enabled

### ISSUE THREAD

**Issue by kron4eg** [kubermatic/kubermatic#14131]
### Description of the feature you would like to add / User story

As a User of the usercluster
I would like to know how big the etcd database of the usercluster is
in order to proactively know own limits of the quota.

### Solution details

Scrape the usercluster kube-apiservers, look for `apiserver_storage_size_bytes` metric which exposes that database size.

Example scrape config to grab the /metrics of the kube-apiserver.

```yaml
- job_name: kube-apiserver
  honor_timestamps: false
  scheme: https
  tls_config:
    ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    insecure_skip_verify: true
  bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  kubernetes_sd_configs:
    - role: endpoints
      namespaces:
        names:
          - default
  relabel_configs:
    - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
      action: keep
      regex: kubernetes;https
```

### Use cases

Sometimes usercluster etcds grow too much in size, this situation needs to be monitored.
