### ISSUE TITLE
User Cluster MLA - mla-gateway - Hardcoded DNS resolver hostname

### ISSUE THREAD

**Issue by pszabo891** [kubermatic/kubermatic#14161]
### What happened?

The DNS resolver hostname in the Nginx config file of the `mla-gateway` component is hardcoded to `kube-dns.kube-system.svc.cluster.local`:
https://github.com/kubermatic/kubermatic/blob/b702378ec49ffd7558f1091c7e4fca40d52732a7/pkg/controller/seed-controller-manager/mla/resources.go#L67
The CoreDNS service provided by default on an RKE2 cluster comes with another service name making the hardcoded hostname not resolvable and the `mla-gateway` fails to start up.
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: rke2-coredns
    meta.helm.sh/release-namespace: kube-system
  labels:
    app.kubernetes.io/instance: rke2-coredns
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: rke2-coredns
    helm.sh/chart: rke2-coredns-1.33.005
    k8s-app: kube-dns
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: CoreDNS
  name: rke2-coredns-rke2-coredns
  namespace: kube-system
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: udp-53
      port: 53
      protocol: UDP
      targetPort: 53
    - name: tcp-53
      port: 53
      protocol: TCP
      targetPort: 53
  selector:
    app.kubernetes.io/instance: rke2-coredns
    app.kubernetes.io/name: rke2-coredns
    k8s-app: kube-dns
  sessionAffinity: None
  type: ClusterIP
```

### Expected behavior

The resolver hostname is either autodetected, or there is possibility to parametrize it.

### How to reproduce the issue?

Deploy the KKP Seed on an RKE2 cluster.

### How is your environment configured?

- KKP version: 2.26.4
- Shared or separate master/seed clusters?: Separate

### Provide your KKP manifest here (if applicable)

N/A

### What cloud provider are you running on?

N/A

### What operating system are you running in your user cluster?

N/A

### Additional information

As a workaround I have deployed another service on the Seed cluster with the desired name:
```
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: kube-dns
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: CoreDNS
  name: kube-dns
  namespace: kube-system
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: udp-53
      port: 53
      protocol: UDP
      targetPort: 53
    - name: tcp-53
      port: 53
      protocol: TCP
      targetPort: 53
  selector:
    app.kubernetes.io/instance: rke2-coredns
    app.kubernetes.io/name: rke2-coredns
    k8s-app: kube-dns
  sessionAffinity: None
  type: ClusterIP
```
