### ISSUE TITLE
User Cluster Audit Logs Source Identification Automation

### ISSUE THREAD

**Issue by csengerszabo** [kubermatic/kubermatic#14160]
### Description of the feature you would like to add / User story

As a KKP admin
I would like User Cluster Audit Logs to include automated source identification
in order to automatically know which was the source cluster for security considerations.

### Problem Statement
Currently, there is no direct way to inject the cluster name into audit logs. Users have tested various configurations of the sidecar and determined that having environment variables such as `CLUSTERNAME` would make their logging setup more efficient.

### Solution details
Introduce an environment variable (e.g., `CLUSTERNAME`) to the audit-logs container. This would allow configurations like the following:

```yaml
spec:
  auditLogging:
    enabled: true
    sidecar:
      config:
        filters:
        - Match: '*'
          Name: grep
        - Match: '*'
          Name: record_modifier
          Record: usercluster ${CLUSTERNAME}
        outputs:
        - Format: json
          Host: x.cluster.local
          Match: '*'
          Name: http
          Port: "8889"
          URI: /x
        service:
          Flush: "10"
```

### Additional information

- As per our documentation, future KKP releases may add an environment variable to automatically get the cluster ID or enrich records with this information by default.
- Internal reference: 7828
- If KubeAPI is responsible for logging, adding an environment variable is a straightforward change.
