### ISSUE TITLE
AppInstallation with ApplicationDefinition using `template.source.git` is throwing go panic

### ISSUE THREAD

**Issue by dharapvj** [kubermatic/kubermatic#14177]
### What happened?
In user-clusters when installing an application which uses ApplicationDefinition with helm templating method and git repo as source for helmchart, application installation fails with a panic stacktrace shown in user-cluster's usercluster-controller pod logs.

Application does NOT get installed in the user-cluster.

The panic log (after formatting)
```log
{"level":"error","time":"2025-02-14T06:01:50.624Z","caller":"util/util.go:120","msg":"
Observed a panic","controller":"kkp-app-installation-controller","controllerGroup":"apps.kubermatic.k8c.io","controllerKind":"ApplicationInstallation","ApplicationInstallation":{"name":"ingress-nginx","namespace":"kube-system"},"namespace":"kube-system","name":"ingress-nginx","reconcileID":"036a5a74-dec4-4fb2-b7cb-d57bb1c0008f","panic":"runtime error: invalid memory address or nil pointer dereference","panicGoValue":"\"invalid memory address or nil pointer dereference\"","stacktrace":"

goroutine 658 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x3dce6f8, 0xc005e94d50}, {0x3067120, 0xad04160})
	k8s.io/apimachinery@v0.31.2/pkg/util/runtime/runtime.go:107 +0xbc
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile.func1()
	sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:105 +0x114
panic({0x3067120?, 0xad04160?})
	runtime/panic.go:785 +0x132
k8c.io/kubermatic/v2/pkg/applications/providers/util.NewAuthSettingsFromHelmSource(...)
	k8c.io/kubermatic/v2/pkg/applications/providers/util/util.go:120
k8c.io/kubermatic/v2/pkg/applications/providers/template.HelmTemplate.InstallOrUpgrade({{0x3dce6f8, 0xc005e94d50}, {0x7ffe8628ad5a, 0x25}, {0x7ffe8628aeab, 0x13}, 0xc005308528, {0x7ffe8628add4, 0x12}, {0x3df2da0, ...}}, ...)
	k8c.io/kubermatic/v2/pkg/applications/providers/template/helm.go:65 +0x182
k8c.io/kubermatic/v2/pkg/applications.(*ApplicationManager).Apply(0xc0028d66c0, {0x3dce6f8, 0xc005e94d50}, 0xc005308528, {0x3df2da0?, 0xc0028c8000?}, {0x3df2da0, 0xc0020e9cb0}, 0xc006dc8960, 0xc006dc81e0, ...)
	k8c.io/kubermatic/v2/pkg/applications/installer.go:97 +0x1a2
k8c.io/kubermatic/v2/pkg/controller/user-cluster-controller-manager/application-installation-controller.(*reconciler).handleInstallation(0xc0028cb900, {0x3dce6f8, 0xc005e94d50}, 0xc005308528, 0xc006dc8960, 0xc006dc81e0)
	k8c.io/kubermatic/v2/pkg/controller/user-cluster-controller-manager/application-installation-controller/controller.go:277 +0xbd1
k8c.io/kubermatic/v2/pkg/controller/user-cluster-controller-manager/application-installation-controller.(*reconciler).reconcile(0xc0028cb900, {0x3dce6f8, 0xc005e94d50}, 0xc005308528, 0xc006dc81e0)
	k8c.io/kubermatic/v2/pkg/controller/user-cluster-controller-manager/application-installation-controller/controller.go:197 +0x73d
k8c.io/kubermatic/v2/pkg/controller/user-cluster-controller-manager/application-installation-controller.(*reconciler).Reconcile(0xc0028cb900, {0x3dce6f8, 0xc005e94d50}, {{{0xc000ad00f0, 0xb}, {0xc000ad00e0, 0xd}}})
	k8c.io/kubermatic/v2/pkg/controller/user-cluster-controller-manager/application-installation-controller/controller.go:127 +0x32c
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile(0xc005e94cc0?, {0x3dce6f8?, 0xc005e94d50?}, {{{0xc000ad00f0?, 0x0?}, {0xc000ad00e0?, 0x0?}}})
	sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:116 +0xbf
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler(0x3dfed40, {0x3dce730, 0xc0022e08c0}, {{{0xc000ad00f0, 0xb}, {0xc000ad00e0, 0xd}}})
	sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:303 +0x368
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem(0x3dfed40, {0x3dce730, 0xc0022e08c0})
	sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:263 +0x230
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2()
	sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:224 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2 in goroutine 206
	sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:220 +0x490
"}
```

### Expected behavior
Application installation should succeed.

### How to reproduce the issue?
Below are the yaml definitions of application definition and application installation that I used.

#### ApplicationDefinition CR - slightly cleaned up yaml output

```yaml
apiVersion: apps.kubermatic.k8c.io/v1
kind: ApplicationDefinition
metadata:
  annotations:
  name: nginx-ingress
spec:
  description: nginx-ingress-controller application
  method: helm
  selector: {}
  versions:
  - template:
      source:
        git:
          path: charts/ingress-nginx
          ref:
            tag: helm-chart-4.9.1
          remote: https://github.com/kubernetes/ingress-nginx.git
    version: 1.9.6
  - template:
      source:
        git:
          path: charts/ingress-nginx
          ref:
            tag: helm-chart-4.12.0
          remote: https://github.com/kubernetes/ingress-nginx.git
    version: 1.12.0
```

#### ApplicationInstallation CR in usercluster - slightly cleaned up yaml output

```yaml
apiVersion: apps.kubermatic.k8c.io/v1
kind: ApplicationInstallation
metadata:
  annotations:
  name: ingress-nginx
  namespace: kube-system
spec:
  applicationRef:
    name: nginx-ingress
    version: 1.12.0
  namespace:
    create: true
    name: ingress-nginx
  reconciliationInterval: 0s
  values: {}
  valuesBlock: |-
    controller:
      allowSnippetAnnotations: true
      config:
        proxy-body-size: "0"
      metrics:
        enabled: true
        port: 10254
        portName: metrics
        service:
          annotations:
            prometheus.io/port: "10254"
            prometheus.io/scrape: "true"
      replicaCount: 3
      service:
        annotations:
          service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /healthz
          service.beta.kubernetes.io/azure-load-balancer-internal: "true"
        loadBalancerIP: 10.45.0.1
    fullnameOverride: ingress-nginx
    nameOverride: ""
status:
  applicationVersion:
    template:
      source:
        git:
          path: charts/ingress-nginx
          ref:
            tag: helm-chart-4.12.0
          remote: https://github.com/kubernetes/ingress-nginx.git
    version: 1.12.0
  conditions:
    ManifestsRetrieved:
      lastHeartbeatTime: "2025-02-26T08:27:55Z"
      lastTransitionTime: "2025-01-27T00:02:41Z"
      message: application's source successfully downloaded
      observedGeneration: 9
      reason: DownloadSourceSuccessful
      status: "True"
    Ready:
      lastHeartbeatTime: "2025-02-26T08:27:55Z"
      lastTransitionTime: "2024-12-02T05:10:20Z"
      message: application is installing or upgrading
      observedGeneration: 9
      reason: InstallationInProgress
      status: Unknown
  helmRelease:
    info:
      description: Upgrade complete
      firstDeployed: "2024-02-26T05:47:41Z"
      lastDeployed: "2024-12-02T05:02:40Z"
      notes: |
        The ingress-nginx controller has been installed.
        It may take a few minutes for the load balancer IP to be available.
        You can watch the status by running 'kubectl get service --namespace ingress-nginx ingress-nginx-controller --output wide --watch'

        An example Ingress that makes use of the controller:
          apiVersion: networking.k8s.io/v1
          kind: Ingress
          metadata:
            name: example
            namespace: foo
          spec:
            ingressClassName: nginx
            rules:
              - host: www.example.com
                http:
                  paths:
                    - pathType: Prefix
                      backend:
                        service:
                          name: exampleService
                          port:
                            number: 80
                      path: /
            # This section is only required if TLS is to be enabled for the Ingress
            tls:
              - hosts:
                - www.example.com
                secretName: example-tls

        If TLS is enabled for the Ingress, a Secret containing the certificate and key must also be provided:

          apiVersion: v1
          kind: Secret
          metadata:
            name: example-tls
            namespace: foo
          data:
            tls.crt: <base64 encoded cert>
            tls.key: <base64 encoded key>
          type: kubernetes.io/tls
      status: deployed
    name: kube-system-ingress-nginx
    version: 691
  method: helm

```

### How is your environment configured?

- KKP version: 2.26.2 (but issue is also reported for 2.27.0)
- Shared or separate master/seed clusters?: Separate

### Provide your KKP manifest here (if applicable)
NA

### What cloud provider are you running on?
Vsphere

### What operating system are you running in your user cluster?
ubuntu 22.04

### Additional information
NA
