### ISSUE TITLE
support custom pre-defined values based on conditions for helm values managed by application installations

### ISSUE THREAD

**Issue by soer3n** [kubermatic/kubermatic#14190]
### Description of the feature you would like to add / User story

As a kkp admin 
I would like to configure values based on a condition in an application installation  `valueBlock` for certain environments like dev,stage and prod in order to use different values for the same key in different clusters.

### Solution details

General idea: use labels & annotations for grouping and then make these available inside values templating.

So for example a customer would label their dev clusters with a label dev. And then in their default-values have something like this

```yaml
# default-values.yaml
{{ if .cluster.labels[“env”] eq “dev” }}
url: [dev.example.com](http://dev.example.com/)
{{ else if .cluster.labels[“env”] eq “production” }}
url: prod[.example.com](http://dev.example.com/)
{{ end }}
```

### Use cases

 One example would be to enforce different kyverno policies in different clusters.

### Additional information

This ticket includes testing that if statements work properly inside our templating.
