### ISSUE TITLE
Subscription and Billing 

### ISSUE THREAD

**Issue by scheeles** [kubermatic/kubermatic#142]
We want to capture the usage of the nodes connected to the customer cluster and use this information for billing. For this we need two parts:

## NodeUpTime:
NodeUpTime will run as a cron-job every minute on the seed-cluster in the namespace of each customer cluster. It will connect to the customer api-server and will execute a function similar to “kubectl get nodes”.  The job will grab some information of the node and save this in a ThirdPartyResource kubermatic.io/node in each namespace. Additional the nodeUpTime will calculate based on the existing and new information the new upTime. This is executed when the kubelet has the status “ready”.

Information which are stored in the ThirdPartyResource kubermatic.io/node:
```
 name: gke-dev-kubermatic-default-pool-3a37543c-84zw
 creationTimestamp: 2016-11-23T08:52:44Z 
 lastHeartbeatTime: 2016-12-14T18:00:32Z
 lastTransitionTime: 2016-11-23T08:53:14Z
 upTime: 126 sec
 message: kubelet is posting ready status. 
 reason: KubeletReady
 status: "True"
 type: Ready
 nodeInfo:
    architecture: amd64
    bootID: a68486b0-d4be-4bcb-86e8-db5ac6b701d2
    containerRuntimeVersion: docker://1.11.2
    kernelVersion: 4.4.21+
    kubeProxyVersion: v1.4.6
    kubeletVersion: v1.4.6
    machineID: 01a630835c568051c126195458355858
    operatingSystem: linux
    osImage: Google Container-VM Image
    systemUUID: FC52A2D3-D8FB-EBDC-0C1E-57DDD95FFC00
```

##SubscriptionJob
The subscription job will forward the upTime from each ThirdPartyResource kubermatic.io/node to stripe https://stripe.com/subscriptions.

Exact spec for this tbd.

**Comment by scruplelesswizard** [comment]
Lgtm

**Comment by mrIncompetent** [comment]
Lgtm

**Comment by OnAirNetlines** [comment]
﻿So, using ThirdPartyResource as storage on Kubernetes seems a bit flawed at this time.

I have investigated multiple paths of what the program is going to do. For example, how the program is going to communicate to the API Server, how it is going to eventually create or not the ThirdPartyResource, how to access resources defined in ThirdPartyResources inside namespaces via the Go Kubernetes Client (to avoid big dependencies), and how to communicate to an API server outside a cluster and inside it.

The part about Go Kubernetes Client feels rather fine. Well, contacting a ThirdPartyResource may need manual interaction somehow, or well maybe. This client handles at least resource creation itself, but not especially the resource creation of a Third Party type (I haven’t found that one yet). But that’s not the issue there.

However, after investigating more into ThirdPartyResource, I have found some practical information about the usage of ThirdPartyResource in real Kubernetes environment, and here’s the gotcha: I discovered there that ThirdPartyResource is only available when explicitly enabled via the kubelet --runtime-config option.

In fact, only some beta extensions are enabled by default. As described in Github ( https://github.com/kubernetes/kubernetes/blob/v1.5.1/docs/api.md#enabling-resources-in-the-extensions-group ), the only extensions enabled by default are DaemonSets, Deployments, HorizontalPodAutoscalers, Ingress, Jobs and ReplicaSets. See, ThirdPartyResource isn’t part of that list. So I first tried to see if it was activated on Google Container Engine.

I’ve so created a testing ThirdPartyResource to know if the creation is accepted and all operations I need to do to store billing data is working as expected on the cluster right now. Well, the problem is that right at the first step, it failed: Google Container Engine rejects to create a ThirdPartyResource. So the follow-up question is: how can we enable, in Google Container Engine, the ThirdPartyResource mechanism, to avoid this error altogether and to continue the development?

Well, the thing is that, I have investigated the REST API of Google Container Engine, as much I have investigated the gcloud commands, and in all of these places I do not find a trace to manually tell the command line to the kubelet, or to set/enable some extensions in Google Container Engine.

This is why I’ve asked on the chat whether if someone actually used a ThirdPartyResource in practice. The fact it is not enabled by default isn’t documented clearly, but it was told by someone testing in practice in a bulletin board thread. And that one will lead you to search and find the Github markdown file above telling that only some APIs are enabled by default - and so the one you’re interested in is implied to be disabled.

So here’s what options we’ve left for billing storage:
1. We find another way to store the data about billing.
2. We find a way to enable the runtime-config flag inside Google Container Engine.
3. We no longer use Google Container Engine to use ThirdPartyResource.

What’s your choice? Do you have suggestions? Questions about how I knew that? Anything?

**Comment by mrIncompetent** [comment]
Not sure why you're TPR creation failed. What it did (on a new created GKE cluster (defaults)):

My TPR:
```yaml
apiVersion: extensions/v1beta1
kind: ThirdPartyResource
description: "A specification of an kubernetes addon"
metadata:
  name: "cluster-addon.kubermatic.io"
versions:
  - name: v1
```

```bash
kubectl apply -f addon.yaml
```

After this i was able to query the resource:
```bash
curl -X GET "http://localhost:8001/apis/kubermatic.io/v1/clusteraddons"
```

And create entries:
```bash
curl -X POST -H "Content-Type: application/json" -d '{
   "metadata": {
     "name": "foo-bar-addon"
   },
   "Foo": "Bar"
}' "http://localhost:8001/apis/kubermatic.io/v1/namespaces/default/clusteraddons"
```

Response:
```javascript
{
  "Foo": "Bar",
  "metadata": {
    "name": "foo-bar-addon",
    "namespace": "default",
    "selfLink": "/apis/kubermatic.io/v1/namespaces/default/clusteraddons/foo-bar-addon",
    "uid": "49da4c7a-c9cc-11e6-a1b1-42010a800023",
    "resourceVersion": "1182",
    "creationTimestamp": "2016-12-24T11:29:53Z"
  }
}
```


Infos on ThirdPartyResources:
https://github.com/kubernetes/kubernetes/blob/master/docs/design/extending-api.md
https://github.com/coreos/etcd-operator
https://github.com/kubernetes/client-go/tree/master/examples/third-party-resources (+ https://github.com/kubernetes/client-go/pull/37)

**Comment by scruplelesswizard** [comment]
@OnAirNetlines please create a WIP pull request for the branch you are working on and reference it in this issue

**Comment by OnAirNetlines** [comment]
@mrIncompetent Hi,
Thanks for the hint. I'm going to try on my side again and see what messed up. About TPR I already found 2 of 3 links, but nice to have pointers.

@chaosaffe Will do later today.

**Comment by OnAirNetlines** [comment]
@mrIncompetent So:
1. There was an error of indentation in my YAML file. I have fixed it though, and it still does not work.
2. I have copy/pasted your example and tried both `kubectl create -f filename.yaml` and `kubectl apply -f filename.yaml`, and I got:
```sh
$ kubectl create -f ThirdPartyRessource.OnAirNetlines.yaml 
Error from server (Forbidden): error when creating "ThirdPartyRessource.OnAirNetlines.yaml": the server does not allow access to the requested resource (post thirdpartyresources.extensions)
$ kubectl create -f ThirdPartyRessource.mrIncompetent.yaml 
Error from server (Forbidden): error when creating "ThirdPartyRessource.mrIncompetent.yaml": the server does not allow access to the requested resource (post thirdpartyresources.extensions)
$ kubectl apply -f ThirdPartyRessource.OnAirNetlines.yaml 
Error from server (Forbidden): error when creating "ThirdPartyRessource.OnAirNetlines.yaml": the server does not allow access to the requested resource (post thirdpartyresources.extensions)
$ kubectl apply -f ThirdPartyRessource.mrIncompetent.yaml 
Error from server (Forbidden): error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"kind\":\"ThirdPartyResource\",\"apiVersion\":\"extensions/v1beta1\",\"metadata\":{\"name\":\"cluster-addon.kubermatic.io\",\"creationTimestamp\":null},\"description\":\"A specification of an kubernetes addon\",\"versions\":[{\"name\":\"v1\"}]}"},"creationTimestamp":null}}
to:
&{0xc4205e6240 0xc4202df180  cluster-addon.kubermatic.io ThirdPartyRessource.mrIncompetent.yaml &ThirdPartyResource{ObjectMeta:k8s_io_kubernetes_pkg_api_v1.ObjectMeta{Name:cluster-addon.kubermatic.io,GenerateName:,Namespace:,SelfLink:,UID:,ResourceVersion:,Generation:0,CreationTimestamp:0001-01-01 00:00:00 +0000 UTC,DeletionTimestamp:<nil>,DeletionGracePeriodSeconds:nil,Labels:map[string]string{},Annotations:map[string]string{kubectl.kubernetes.io/last-applied-configuration: ,},OwnerReferences:[],Finalizers:[],ClusterName:,},Description:A specification of an kubernetes addon,Versions:[{v1}],} &TypeMeta{Kind:,APIVersion:,} 789416 false}
for: "ThirdPartyRessource.mrIncompetent.yaml": the server does not allow access to the requested resource (patch thirdpartyresources.extensions cluster-addon.kubermatic.io)
```

However, given the last message tells clearly that you could create a 3rd party ressource in the same cluster, I guess that this is an IAM (Identity & Access Management) problem. @scheeles 

------
EDIT: This is confirmed by a look on [Google Cloud Docs](https://cloud.google.com/container-engine/docs/iam-integration#iam_permissions). See also how [IAM roles maps to Kubernetes access](https://cloud.google.com/container-engine/docs/iam-integration#iam_roles).

**Comment by scruplelesswizard** [comment]
@OnAirNetlines What cluster are you deploying this to, and can you please share the content of your YAML spec? We can't really assist in resolving the issue if without some more information.

**Comment by OnAirNetlines** [comment]
@chaosaffe I forgot the YAML of my end. But anyway, as told in the issue, I have tried the @mrIncompetent YAML's as well, so the issue can't be the YAML anyway.

I think it is because I don't have enough IAM to do anything in the cluster:
```
$ kubectl run nginx --image=nginx 
Error from server (Forbidden): the server does not allow access to the requested resource (post deployments.extensions)
```

My test YAML:
```yaml
apiVersion: extensions/v1beta1
kind: ThirdPartyResource
description: "Try to push a 3rd party ressource to test it in Kubermatic"
metadata:
  name: test-billing.kubermatic.io
versions:
  - name: v1
```
