### ISSUE TITLE
Cannot set flags with "false" for applications that use HTTP Prober

### ISSUE THREAD

**Issue by ahmedwaleedmalik** [kubermatic/kubermatic#14296]
### What happened?

Cannot set flags to "false" for applications that use HTTP Prober to run the controller/application binaries. We uncovered this issue while testing KubeLB with a customer. When [DisableIngressClass](https://docs.kubermatic.com/kubermatic/v2.27/references/crds/#:~:text=DisableIngressClass%20is%20used%20to%20disable%20the%20ingress%20class%20%60kubelb%60%20filter%20for%20kubeLB.) is set to false, the flag `use-ingress-class=false` is configured for the KubeLB CCM. However, the flag remains ineffective. Tried the same without any wrappers and it worked fine.

Then for further investigation, I stopped a cluster and updated the OSM deployment with `-leader-elect=false` flag but that had the same effect; leader election was still defaulted to true in OSM.

```
      containers:
      - args:
        - -endpoint
        - https://apiserver-external.cluster-fzbxp25pww.svc.cluster.local./healthz
        - -insecure
        - -retries
        - "100"
        - -retry-wait
        - "2"
        - -timeout
        - "1"
        - -command
        - '{"command":"/usr/local/bin/osm-controller","args":["-kubeconfig","/etc/kubernetes/kubeconfig/kubeconfig","-cluster-dns","169.254.20.10","-health-probe-address","0.0.0.0:8085","-metrics-address","0.0.0.0:8080","-namespace","kube-system","-external-cloud-provider","-container-runtime","containerd", "-leader-elect", "false"]}'
        command:
        - /http-prober-bin/http-prober
```

### How is your environment configured?

- KKP version: All versions are affected
- Shared or separate master/seed clusters?:

### Provide your KKP manifest here (if applicable)

<details>

```yaml
# paste manifest here
```

</details>

### Additional information

This is a rough write-up since there was only limited time that I could spend on this issue.
