### ISSUE TITLE
KubeLB Tenant Configuration at Project Level

### ISSUE THREAD

**Issue by csengerszabo** [kubermatic/kubermatic#14297]
### User story

As a Project admin
I want to manage KubeLB tenant configurations at the Project level,
so that I can enforce consistent Tenant Specs across all user clusters within a Project.

### Solution details

- Using the Tenant Level Filtering for DNS / Certificates
- Sync the Tenant Specs like Allowed Domains, Certificate Allowed Domains etc. 
- Possibility to restrict Project to specific DNS Zones

**Comment by csengerszabo** [comment]
Internal reference: 7740

**Comment by ahmedwaleedmalik** [comment]
As a KKP/project admin, I want to manage the default values for the KubeLB tenant at a project level. This will help us manage configurations such as allowed domains for DNS/Certificates from a centralized point. Right now, KKP doesn't provide us with a way to manage them and we have to update them manually **after** a cluster/tenant has been created.

Suggested implementation could look something like:

```
apiVersion: kubermatic.k8c.io/v1
kind: Project
metadata:
  name: id
spec:
  name: '#1'
  defaultTenantSpec:
    allowedDomains:
    - 'testing.localhost'
    certificates: {}
    dns: {}
    ... 
```

Here `defaultTenantSpec` is the embedded [tenant spec](https://docs.kubermatic.com/kubelb/v1.1/references/ee/#tenantspec). Any field within defaultTenantSpec that has been configured for the project, should be copied over and used in the tenant that's created for clusters of that project. 

@csengerszabo can you please update the ticket with this description? :D
