### ISSUE TITLE
Disabling enabled VPA feature doesn't stop and cleanup VPA resources

### ISSUE THREAD

**Issue by toschneck** [kubermatic/kubermatic#14307]
### What happened?

Disabled VPA.
```
apiVersion: kubermatic.k8c.io/v1
kind: KubermaticConfiguration
metadata:
  name: kubermatic
  namespace: kubermatic
spec:
  featureGates:
    KonnectivityService: true
    OIDCKubeCfgEndpoint: true
    OpenIDAuthPlugin: true
    OperatingSystemManager: true
    TunnelingExposeStrategy: true
    UserClusterMLA: true
    #VerticalPodAutoscaler: false #FIXME currently a lot of delete events, k logs deployments/vpa-recommender  --since 8h | grep '{cluster-'
  
```

but recommender is still doing things and is NOT disabled

### Expected behavior

VPA what have been installed by KKP get cleaned up and stop his job.

### How to reproduce the issue?

Enable at Config the feature flag and then disable it again

### How is your environment configured?

- KKP version: `2.27.2`
- Shared or separate master/seed clusters?: shared

### Provide your KKP manifest here (if applicable)

<details>
https://github.com/kubermatic/demo-infra/blob/main/kubermatic/secrets/kubermatic.operator.config.yaml
```yaml
# paste manifest here
```

</details>

## Current Workaround
execute the cleanup script manual
https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/hack/vpa-down.sh
