### ISSUE TITLE
Kubevirt Provisioning of VMs with Containerized Data Importer 1.62 don't work with block device by default - permission denined

### ISSUE THREAD

**Issue by toschneck** [kubermatic/kubermatic#14352]
### What happened?

In our Demo Setup we use
- KubeOne `1.9.2` what uses contained as default
- Kubevirt Setup `1.5.0` + CDI `1.62.0`
- KKP `2.27.2`
- Piraeus.io Linstor based Block Storage `2.8.0`

At the creation of an kubevirt worker, we get now a the import job of CDI, the following error
```
k logs importer-prime-fad20650-a11d-4335-8880-4b849b354e3c -p
I0408 21:25:23.841210       1 importer.go:107] Starting importer
E0408 21:25:23.843191       1 importer.go:137] exit status 1, blockdev: cannot open /dev/cdi-block-volume: Permission denied

kubevirt.io/containerized-data-importer/pkg/util.GetAvailableSpaceBlock
        pkg/util/file.go:135
kubevirt.io/containerized-data-importer/pkg/util.GetAvailableSpaceByVolumeMode
        pkg/util/util.go:99
main.main
        cmd/cdi-importer/importer.go:135
runtime.main
        bazel-out/k8-fastbuild-ST-b33d65c724e6/bin/external/io_bazel_rules_go/stdlib_/src/runtime/proc.go:272
runtime.goexit
        src/runtime/asm_amd64.s:1700
```

Unfortunately this error is not really clear what is the main issue, after some research it leaded to the problem that pod `runAsNonRoot: true` and  `runAsUser: 107` is set, but the contained seams to mount block device default as `root`.

As more users could fall into this trap, I started this issue.
More Details see:
- [containerized-data-importer - block_cri_ownership_config](https://github.com/kubevirt/containerized-data-importer/blob/v1.62.0/doc/block_cri_ownership_config.md)

xref relevant github issues:
- https://github.com/kubevirt/containerized-data-importer/issues/2919
- https://github.com/kubevirt/containerized-data-importer/pull/2458 (Thx to @akalenyu for documenting)

 

### Expected behavior

By default the setup, shouldn't be depend on such setting.  We need to:
- document this during the setup of the kubevirt progress
- may set better defaults at kubeone for containerd (separate issue for this) 

### How to reproduce the issue?

Setup kubevirt similar to demo system and create a new kubevirt cluster.

Or alternative create this testing VM:
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: test-kubevirt
---
apiVersion: instancetype.kubevirt.io/v1beta1
kind: VirtualMachineInstancetype
metadata:
  name: standard-2
  namespace: test-kubevirt
spec:
  cpu:
    guest: 2
  memory:
    guest: 8Gi
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  namespace: test-kubevirt
  labels:
    kubevirt.io/vm: kkp-ubuntu
  name: kkp-ubuntu
spec:
  dataVolumeTemplates:
  - metadata:
      creationTimestamp: null
      name: kkp-ubuntu
    spec:
      source:
        http:
          url: http://vm-image-registry.kube-system.svc/vms/ubuntu-22.04-2025-01-13.img
          #latest cloudimg
          #url: https://cloud-images.ubuntu.com/releases/24.04/release/ubuntu-24.04-server-cloudimg-amd64.img
      storage:
        accessModes:
        - ReadWriteMany
        resources:
          requests:
            storage: 15G
        storageClassName: kubevirt-vm-storage
  instancetype:
    kind: VirtualMachineInstancetype
    name: standard-2
  runStrategy: Once
  template:
    metadata:
      labels:
        kubevirt.io/vm: kkp-ubuntu
    spec:
      dnsConfig:
        nameservers:
        - 8.8.8.8
      dnsPolicy: None
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: datavolumedisk
          - disk:
              bus: virtio
            name: cloudinitdisk
      terminationGracePeriodSeconds: 30
      volumes:
      - dataVolume:
          name: kkp-ubuntu
        name: datavolumedisk
      - cloudInitNoCloud:
          userData: |
            #!/bin/sh
            uname -a
            mkdir -p /root/.ssh
            cat << EOF >> /root/.ssh/authorized_keys
            ###### TODO ADD your SSH PUB key
            echo 'ssh key added ...'
            cp /root/.ssh/authorized_keys /home/ubuntu/.ssh/authorized_keys
            cat /root/.ssh/authorized_keys
            echo 'connect via: virtctl ssh root@kkp-ubuntu'
        name: cloudinitdisk
```

### How is your environment configured?

see above + https://github.com/kubermatic/demo-infra

#### Important configs
```yaml
apiVersion: cdi.kubevirt.io/v1beta1
kind: CDI
metadata:
  name: cdi
spec:
  config:
    featureGates:
    - HonorWaitForFirstConsumer
  imagePullPolicy: IfNotPresent
  infra:
    nodeSelector:
      kubernetes.io/os: linux
    tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
  workload:
    nodeSelector:
      kubernetes.io/os: linux
```
Storage Class
```yaml
# https://github.com/piraeusdatastore/linstor-csi/tree/master/examples/kubevirt
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: kubevirt-vm-storage
provisioner: linstor.csi.linbit.com
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
#https://linbit.com/drbd-user-guide/linstor-guide-1_0-en/#s-kubernetes-sc-parameters
parameters:
  #linstor.csi.linbit.com/placementCount: "1"
  linstor.csi.linbit.com/storagePool: k1-zfs-thin-sp
  linstor.csi.linbit.com/resourceGroup: kubevirt
  ### Enables Live Migration: not tested
  linstor.csi.linbit.com/placementCount: "2"
  DrbdOptions/Net/allow-two-primaries: "yes"
```
### Provide your KKP manifest here (if applicable)

see repo

</details>

### What cloud provider are you running on?

KubeVirt

### What operating system are you running in your user cluster?

Ubuntu

### Workaround

Patch KubeOne containerd settings: TODO add info

**Comment by toschneck** [comment]
Kubeone will set the flag as default I see, and offers already an adjustment, see https://github.com/kubermatic/kubeone/pull/3392, https://github.com/kubermatic/kubeone/issues/3395

So the TODO is then to ensure that the kubevirt provider documentation will get updated, to avoid future failures.

**Comment by csengerszabo** [comment]
@toschneck did your PR fix this?

**Comment by toschneck** [comment]
It's fixed it for me, but is a workaround, as we don't have it document or as a default setting.  So  I think we should set this setting as default in kubeone  as also @moadqassem agreed:
```
#kubeone.yaml
containerRuntime:
  containerd:
    # fixes CDI kubevirt image permission denied error
    deviceOwnershipFromSecurityContext: true
```
Or if this is not done, need to document this as a requirement for a kubevirt provider setup in our official docs
