### ISSUE TITLE
Kubelogin kubectl plugin support

### ISSUE THREAD

**Issue by koksay** [kubermatic/kubermatic#14404]
### Description of the feature you would like to add / User story

As a KKP user
I would like to have support for `kubectl` [kubelogin plugin](https://github.com/int128/kubelogin) on the UI
in order to have easier access to the OIDC kubeconfigs on the command line. 

### Solution details

Currently, when the OIDC kubeconfig feature is enabled, users can download a kubeconfig file, valid for a defined period of time (1 day by default). When this expires, users need to log in to the KKP UI, find their cluster, download the kubeconfig file again, and update their `KUBECONFIG` environment variable or the' ~/.kube/config` file.

With the `kubelogin` plugin solution, users can download the kubeconfig only once. When the OIDC token expires, the browser window will be opened to authenticate, and they will continue with their work. This will provide a better user experience as they will not need to deal with downloading and managing kubeconfig files for the user clusters.

Here is how our current OIDC kubeconfig files look like:

```yaml
apiVersion: v1
kind: Config
...
users:
- name: koray@example.com
  user:
    auth-provider:
      config:
        client-id: exampleIssuer
        client-secret: xxx
        id-token:  xxx
        idp-issuer-url: https://kkp.example.com/dex
        refresh-token:  xxx
      name: oidc
```

This is how it works with `kubelogin` plugin:

```yaml
apiVersion: v1
kind: Config
...
users:
  - name: koray@example.com
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1
        args:
          - oidc-login
          - get-token
          - --oidc-issuer-url=https://kkp.example.com/dex
          - --oidc-client-id=exampleIssuer
          - --oidc-client-secret=xxx
          - --oidc-extra-scope=email
        command: kubectl
        env: null
        interactiveMode: Never
        provideClusterInfo: false
```

### Additional information

Users will need to install the plugin on their environments, and it's not maintained by Kubermatic.

```bash
# Homebrew (macOS and Linux)
brew install kubelogin

# Krew (macOS, Linux, Windows and ARM)
kubectl krew install oidc-login

# Chocolatey (Windows)
choco install kubelogin
```
