### ISSUE TITLE
Typo in cluster-autoscaler application's default values

### ISSUE THREAD

**Issue by judge-red** [kubermatic/kubermatic#14428]
The default values for the cluster-autoscaler application contain a typo:

```
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: cluster-autoscaler-clusterapi-cluser-autoscaler
```

Should be `cluster` (twice) instead of `cluser` (towards the end).

I figure this name isn't used anywhere, so at least the typo shouldn't break anything.

Just in case it's not clear where I'm seeing this:

![Image](https://github.com/user-attachments/assets/ffb6468d-9074-4249-a712-2a4a9c8c5433)
