### ISSUE TITLE
Velero Checksum Algorithm - Test Release 2.28

### ISSUE THREAD

**Issue by csengerszabo** [kubermatic/kubermatic#14542]
Goal: Validate default checksum algorithm configuration for Velero backups.
PR: https://github.com/kubermatic/kubermatic/pull/14253

**Comment by adoi** [comment]
The linked PR works fine, setting the default KubermaticSettings to use the default checksum algorithm is working as intended. 
- [x] - Seting `defaultChecksumAlgorithm` 
```
k patch kubermaticsettings globalsettings \
  --type merge \
  -p '{"spec":{"clusterBackupOptions":{"defaultChecksumAlgorithm":"CRC32"}}}' 
```

The KubermaticSettings in Seed:
```
apiVersion: kubermatic.k8c.io/v1                                              
kind: KubermaticSetting
spec:
    <other fields>
    clusterBackupOptions:                                                       
    defaultChecksumAlgorithm: CRC32   
```
This ticket can be closed.
