### ISSUE TITLE
Configure registry mirrors at cluster level

### ISSUE THREAD

**Issue by ahmedwaleedmalik** [kubermatic/kubermatic#14716]
### Description of the feature you would like to add / User story

As a KKP admin, we want to configure the containerd registry mirrors at the cluster level. 

We basically need these configurations at the cluster level(some might be covered by KKP already):

```yaml
      node:
        # Optional: ContainerdRegistryMirrors configure registry mirrors endpoints. Can be used multiple times to specify multiple mirrors.
        containerdRegistryMirrors: null
        # Optional: If set, this proxy will be configured for both HTTP and HTTPS.
        httpProxy: ""
        # Optional: These image registries will be configured as insecure
        # on the container runtime.
        insecureRegistries: []
        # Optional: If set this will be set as NO_PROXY environment variable on the node;
        # The value must be a comma-separated list of domains for which no proxy
        # should be used, e.g. "*.example.com,internal.dev".
        # Note that the in-cluster apiserver URL will be automatically prepended
        # to this value.
        noProxy: ""
        # Optional: Translates to --pod-infra-container-image on the kubelet.
        # If not set, the kubelet will default it.
        pauseImage: ""
        # Optional: These image registries will be configured as registry mirrors
        # on the container runtime.
        registryMirrors: []
      # Spec describes the cloud provider settings used to manage resources
      # in this datacenter. Exactly one cloud provider must be defined
```

Once we have these options available we can simply pass them to OSM from [here](https://github.com/kubermatic/kubermatic/blob/main/pkg/resources/operatingsystemmanager/deployment.go#L275-L305).

/label customer-request
