### ISSUE TITLE
Missing ProviderID on Flatcar Stable 4230.2.0 due to incorrect KUBELET_HOSTNAME

### ISSUE THREAD

**Issue by ealogar** [kubermatic/kubermatic#14733]
### What happened?

When using Flatcar Linux 4230.2.0 (and Alpha builds) as the operating system for user clusters, the kubelet fails to set the --provider-id flag correctly. This causes issues with the cloud controller manager and prevents nodes from being properly registered in Kubernetes.

The root cause is that the default OperatingSystemProfile for Flatcar sets the KUBELET_HOSTNAME to the short hostname (e.g., ip-10-54-69-123) instead of the fully qualified domain name (FQDN), which is expected by the API server and used for RBAC (system:node:<fqdn>).
CCM logs:

User "system:node:ip-10-54-69-123" cannot list resource "nodes"

### Expected behavior

The kubelet should be configured with the correct FQDN in KUBELET_HOSTNAME, such as ip-10-54-69-123.yyyy.xxx.zzz, which matches its expected identity and allows proper node registration and population of the provider-id.

### How to reproduce the issue?

Create a KKP user cluster using AWS as the provider.

Use Flatcar-stable-4230.2.0-hvm or a newer Alpha build as the machine image.

Let the cluster bootstrap with the default osp-flatcar.yaml profile.

Observe kubelet logs on the worker node:

User "system:node:<short-hostname>" cannot list resource "nodes"

Check --provider-id is empty and the node fails to register properly. It also has the taint node.cloudprovider.kubernetes.io/uninitialized which avoids pods to be scheduled because the kubelet can not fully configured the providerID.

### How is your environment configured?

- KKP version: 2.27.3
- Separated seed clusters

### Provide your KKP manifest here (if applicable)
Using kubeone

### What cloud provider are you running on?
AWS

### What operating system are you running in your user cluster?
Flatcar Linux 4230.2.0-hvm (and Alpha variants tested as well)

### Additional information

Workaround/Fix:

We created a custom OperatingSystemProfile for flatcar that explicitly sets the FQDN for KUBELET_HOSTNAME, like this:
```
              FULL_HOSTNAME=$(grep COREOS_EC2_HOSTNAME /run/metadata/coreos | cut -d= -f2)
              if [ -z "$FULL_HOSTNAME" ]; then
                FULL_HOSTNAME=$(hostname -f)
              fi
```
This replaces the following line here: https://github.com/kubermatic/operating-system-manager/blob/main/deploy/osps/default/osp-flatcar.yaml#L571
making it using the coreos metadata that flatcar provides or defaulting to the previous one.

I will raise this issue in flatcar as well.

**Comment by ahmedwaleedmalik** [comment]
This is the same issue as https://github.com/kubermatic/kubermatic/issues/14731.

The hostname is set properly to the full FQDN name by MC/OSM initially. But the problem is with flatcar's update engine , it changes the hostname to the short hostname after performing an upgrade. 

For now, we recommend disabling auto updates for you machine deployments:

```yaml
operatingSystemSpec:
  disableAutoUpdate: true
  disableLocksmithD: true
```

**Comment by ahmedwaleedmalik** [comment]
> We created a custom OperatingSystemProfile for flatcar that explicitly sets the FQDN for KUBELET_HOSTNAME, like this:

This might not work as after an update and a reboot, it would change the hostname back to the short name for your machine.

**Comment by ealogar** [comment]
We are not using autoUpdates:
```
operatingSystemSpec:                                                                                                                                                                                                                                                                                                                                                                                   
  disableAutoUpdate: true
  disableLocksmithD: true
  disableUpdateEngine: false
  provisioningUtility: ignition
```
It's happening with new machines bootstrapped with the default OperatingSystemProfile osp-flatcar In the flatcar version I mentioned and up.
I have login in the machine and run hostname -f to verify that is not being resolved to the fqdn and the environments file that kubelet usses is not populated /etc/kubernetes/nodeip.conf with the fqdn
