### ISSUE TITLE
Improve cluster's health endpoint

### ISSUE THREAD

**Issue by p0lyn0mial** [kubermatic/kubermatic#1485]
At the moment the data we return from `cluster/{cluster_name}/health` endpoint are very basic :
```
type NewClusterHealth struct {
	Apiserver         bool `json:"apiserver"`
	Scheduler         bool `json:"scheduler"`
	Controller        bool `json:"controller"`
	MachineController bool `json:"machineController"`
	Etcd              bool `json:"etcd"`
}
```

This issue helps to define the new metrics we would like to return to the users.

**Comment by p0lyn0mial** [comment]
@mrIncompetent could you help to define the new metrics ?

**Comment by mrIncompetent** [comment]
The 4 status of a Apiserver Deployment:

# Creation of the 1st pod
```yaml
status:
  conditions:
  - lastTransitionTime: 2018-07-19T15:09:34Z
    lastUpdateTime: 2018-07-19T15:09:34Z
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: 2018-07-19T15:09:34Z
    lastUpdateTime: 2018-07-19T15:09:34Z
    message: ReplicaSet "apiserver-6797dffdb" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
```

# 1st Pod is running
```yaml
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2018-07-19T15:11:12Z
    lastUpdateTime: 2018-07-19T15:11:12Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: 2018-07-19T15:09:34Z
    lastUpdateTime: 2018-07-19T15:11:12Z
    message: ReplicaSet "apiserver-6797dffdb" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
```

# Deployment got updated -> New Pod get scheduled
```yaml
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2018-07-19T15:11:12Z
    lastUpdateTime: 2018-07-19T15:11:12Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: 2018-07-19T15:09:34Z
    lastUpdateTime: 2018-07-19T15:13:25Z
    message: ReplicaSet "apiserver-5bb455d554" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 2
  unavailableReplicas: 1
  updatedReplicas: 1
```

# Deployment finished updating
```yaml
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2018-07-19T15:11:12Z
    lastUpdateTime: 2018-07-19T15:11:12Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: 2018-07-19T15:09:34Z
    lastUpdateTime: 2018-07-19T15:13:54Z
    message: ReplicaSet "apiserver-5bb455d554" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
```
