### ISSUE TITLE
Add List of webhooks to the add-on manager config

### ISSUE THREAD

**Issue by guusvw** [kubermatic/kubermatic#1541]

**Comment by guusvw** [comment]
After the Add-On manager installed all add-ons successfully, it should call a list of HTTP/S endpoints to trigger additional actions.

CloudiFire Ref: https://github.com/CloudiFire/caas/issues/57

@glower will write a proposal for this, covering 

* how to deal with errors
* should we send meta infos? (list of add-ons, the name of the cluster, ...)

**Comment by toschneck** [comment]
should be finished in next sprint, to have it for the cloudifire demo at the beginn of August

**Comment by glower** [comment]
We will create an extra docker container  with an application inside making http calls from the config. This application will be installed to the user cluster as a k8s job. Installation is done with the kubermatic addon manager
* write the app for the webhooks and dockerize it 
* write a manifest for k8s to run the container as a Job
* build a new docker image based on `quay.io/kubermatic/addons`
* for the installation follow the steps from: https://docs.kubermatic.io/advanced/addons/
* test it with a fake drone CI pipeline

**Comment by glower** [comment]
# How to create web-hook addon for kubermatic user cluster

With this addon we will trigger a build on `circleci.com` each time user cluster is created

## Basic setup
All addon files:
```
> tree .
├── Dockerfile
└── webhook
    └── job.yaml
```

Dockerfile:
```
FROM quay.io/kubermatic/addons:v0.1.4
RUN apk add --no-cache curl
ADD ./ /addons/
```

webhook/job.yaml:
```
apiVersion: batch/v1
kind: Job
metadata:
  name: webhook-addon
  namespace: kube-system
spec:
  template:
    metadata:
      name: webhook-addon
    spec:
      containers:
      - name: webhook-addon
        image: byrnedo/alpine-curl
        command: ["/bin/sh"]
        args:
          - "-c"
          - >
            /usr/bin/curl -X POST "https://circleci.com/api/v1.1/project/github/glower/hello-web/tree/master?circle-token=6f5b226361afd32a6edddd8726cb7c300303cf7d"
      restartPolicy: Never
```

### Build and release of the addon

```
export TAG=v1.2.3
docker build -t customer/k8c-addons:${TAG} .
docker push customer/k8c-addons:${TAG}
```

## Kubermatic setup

We will update an existing kubermatic setup. In the kubermatic/kubermatic-installer update `value.yaml` file:

```
kubermatic:
  ...
  addons:
    defaultAddons:
    - canal
    - dashboard
    - dns
    - heapster
    - kube-proxy
    - openvpn
    - rbac
    - webhook # the name of the addon is same as directory where manifest file is placed
...
  controller:
    ...
    addons:
      image:
        repository: "customer/k8c-addons"
        tag: "v1.2.3"
        pullPolicy: "IfNotPresent"

```

Now update the kubermatic:

```
helm upgrade --install --wait --timeout 300 --values values.yaml --namespace kubermatic kubermatic charts/kubermatic/
```

After this check if `controller-manager-v1` is in `Running` status.

```
>  k get pods -n kubermatic   
NAME                                    READY     STATUS    RESTARTS   AGE
controller-manager-v1-b797f6ff6-4sn6z   1/1       Running   0          1m
controller-manager-v1-b797f6ff6-pbn4m   1/1       Running   0          1m
kubermatic-api-v1-5787d65d85-22vjv      1/1       Running   0          30m
kubermatic-api-v1-5787d65d85-r28qq      1/1       Running   0          30m
kubermatic-ui-v2-5c9945597d-48shs       1/1       Running   0          1d
kubermatic-ui-v2-5c9945597d-7dm45       1/1       Running   0          1d
```

Now try to create a user cluster and the addon manager will call the configured endpoint to trigger a build
