### ISSUE TITLE
[Grafana/Prom Customizing] Allow the use of grafana plugins

### ISSUE THREAD

**Issue by pkavajin** [kubermatic/kubermatic#1782]
It would be good to have the possibility to install grafana plugins, which could be maybe done with such an init container for example:

```
      {{- if .Values.grafana.plugins }}
      initContainers:
      - name: install-plugins
        image: {{ .Values.grafana.image.repository }}:{{ .Values.grafana.image.tag }}
        env:
        - name: GF_PLUGIN_DIR
          value: /data/plugins
        command:
          - /bin/sh
          - -c
          - |
            mkdir -p /data/plugins
            {{- range .Values.grafana.plugins }}
            ./bin/grafana-cli plugins install {{ . }}
            {{- end }}
        volumeMounts:
        - mountPath: /data
          name: grafana-storage
          readOnly: false
      {{- end }}
```

Issue extracted from https://github.com/kubermatic/kubermatic/pull/1775#issuecomment-413459153
