### ISSUE TITLE
Add SeedDatacenter & NodeLocation CRD's

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#2114]
**User Story**
To be able to manage Datacenters via API we need to start moving the datacenter.yaml into a CRD.
As the current `datacenters.yaml` contains both Seed & Node datacenters - on the same leven, which has been causing confusion, we're restructure the format in the CRD..
Instead of using same level datacenters, we're going to have a SeedDatacenter as object which has n node datacenters as list in its spec. But instead of sticking to the name `datacenter` for nodes, we're going to rename it to `node location` as it is a better fit. On AWS for example, we have a Region with different Zones. Theoretically the user could create nodes in each zone. 
Naming it NodeDatacenter would be too specific and confusing.

**SeedDatacenter**
Defines a seed cluster, a kubernetes cluster which houses user clusters.
```yaml
apiVersion: kubermatic.k8s.io/v1
kind: SeedDatacenter
metadata:
  name: europe-west3-c
spec:
  # Country of the cluster (Relevant for global setups)
  country: "DE"
  # Detailed location of the cluster (Region / Datacenter / Rack? )
  location: "Frankfurt"
  # The kubeconfig to access the cluster (Required for the kubermatic API)
  kubeconfig:
    secretRef:
      namespace: "kubermatic"
      name: "kubeconfig-europe-west3-c"
  nodeLocations:
    aws-us-east-1a:
      # Country of the nodes
      country: "US"
      # Detailed location of the nodes (Zone / Datacenter / Rack? )
      location: "North Virginia"
      # cloud provider specifics
      provider:
        aws:
          region: us-east-1
          zones:
          - a
          - b
          - c
```

**Acceptance criteria**
- [ ] 2 new CRD manifests have been added to the kubermatic chart: https://github.com/kubermatic/kubermatic/tree/master/config/kubermatic/templates
- [ ] The CRD manifests have a full OpenAPI validation
- [ ] The CRD go types have been added to https://github.com/kubermatic/kubermatic/tree/master/api/pkg/crd/kubermatic/v1
- [ ] The generated go-client has been updated with the new types

**Comment by mrIncompetent** [comment]
@p0lyn0mial @alvaroaleman Please review the above mentioned types.

**Comment by alvaroaleman** [comment]
IMHO the review of a new type should not happen in an issue but in a PR as the latter allows for inline comments which the former does not. That being said I have some questions:

* Are they going to be namespaced?
* If no, how is the namespace of the `kubeconfig` secret of a `SeedDatacenter` determined?
* How is the key of the `kubeconfig` secret of a `SeedDatacenter` determined?

**Comment by alvaroaleman** [comment]
Hmm, thinking about this a little more we have a 1-n relation of `SeedDatacenter` to `NodeLocation`.

Wouldn't it make sense to not define two CRDs but instead let the `SeedDatacenter` have a field `.spec.nodeLocations` which contains a list of `nodeLocations`?

**Comment by mrIncompetent** [comment]
@alvaroaleman 
> Are they going to be namespaced?

No. I don't see any reason to namespace it.

> How is the key of the kubeconfig secret of a SeedDatacenter determined?

Should we use current-context? 

> Wouldn't it make sense to not define two CRDs but instead let the SeedDatacenter have a field .spec.nodeLocations which contains a list of nodeLocations?

That's a interesting question. It seems easier!

It made me think of how we would keep those CRD's in sync with multiple seed clusters.
Each seed cluster needs to have those NodeLocations (As we apply defaulting based on them). Maybe we need to implement another controller to populate those resources from the master to the seeds ?

Who needs what (From my understanding):
- Master 
  - SeedDacenter's
  - NodeLocation's (Either as own CRD or as part if the SeedDacenter)
- Seed
  - NodeLocation's (Either as own CRD or as part if the SeedDacenter)

I dislike the need to synchronize the data, but it seems its necessary here :(
@alvaroaleman WDYT?

**Comment by alvaroaleman** [comment]
>> How is the key of the kubeconfig secret of a SeedDatacenter determined?

> Should we use current-context?

Oups, fail. The question was "how is the namespace of the kubeconfig secret determined" as secretRef does not have a namespace. But the kubeconfig certainly should have one context only.

> I dislike the need to synchronize the data, but it seems its necessary here :(
I dislike it as well, but it seems to be the least evil here. Maybe we can make it less evil by adding a admissionWebhook that only allows update/create if the resulting CR then equals the one in the master?

Just from a user perspective I find it very logical to have one CRD that has the `nodeDatacenter` as property of the `seedDatacenter`

**Comment by mrIncompetent** [comment]
> > > How is the key of the kubeconfig secret of a SeedDatacenter determined?

> > Should we use current-context?

> Oups, fail. The question was "how is the namespace of the kubeconfig secret determined" as secretRef does not have a namespace. But the kubeconfig certainly should have one context only.

Right, namespaces... Maybe:
```yaml
seedRef:
  name: "europe-west3-c"
  namespace: "kubermatic"
```
?


> > I dislike the need to synchronize the data, but it seems its necessary here :(

> I dislike it as well, but it seems to be the least evil here. Maybe we can make it less evil by adding a admissionWebhook that only allows update/create if the resulting CR then equals the one in the master?

Maybe we just make it read-only on non-master systems to avoid any complications?
I suppose - a sync controller/loop would override changes anyway.

> Just from a user perspective I find it very logical to have one CRD that has the nodeDatacenter as property of the seedDatacenter

sgtm, i'll update the description

**Comment by alvaroaleman** [comment]
`seedRef` as dedicated sub property seems a good idea :+1: 

> Maybe we just make it read-only on non-master systems to avoid any complications?
> I suppose - a sync controller/loop would override changes anyway.

That was what I was going write on my comment before until I realized it cant be read-only because our controller has to update it, thats why I came up with the webhook that would allow only our controller to upadte it :D

**Comment by mrIncompetent** [comment]
> seedRef as dedicated sub property seems a good idea +1

Btw. i mixed up the properties, i mean kubeconfig.
To follow actually the kubernetes style here, i would use:
```yaml
  kubeconfig:
    secretRef:
      namespace: "kubermatic"
      name: "kubeconfig-europe-west3-c"
```

> That was what I was going write on my comment before until I realized it cant be read-only because our controller has to update it, thats why I came up with the webhook that would allow only our controller to upadte it :D

Ah dammit...
