### ISSUE TITLE
Hide credentials from an enduser 

### ISSUE THREAD

**Issue by zreigz** [kubermatic/kubermatic#3549]
**User Story**
User can specify predefined presets for the providers. Credentials are part of the provider preset. Presets are set in the separate presets.yaml configuration.
**Acceptance criteria**
The user should not see/copy/access the preconfigured credentials

presets.yaml example:
```
presets:
  digitalocean:
    credentials:
      - name: digitalocean
        token:
  azure:
    credentials:
      - name: azure
        tenantId:
        subscriptionId:
        clientId:
        clientSecret:
        resourceGroup:
        vnet:
        subnet:
        routeTable:
        securityGroup:
  aws:
    credentials:
      - name: aws
        accessKeyId:
        secretAccessKey:
        vpcId:
        subnetId:
        routeTableId:
        instanceProfileName:
        securityGroupID:
  openstack:
    credentials:
      - name: openstack
        username:
        password:
        tenant:
        domain: DEFAULT
        network:
        securityGroups:
        floatingIpPool:
        routerID:
        subnetID:
  hetzner:
    credentials:
      - name: default
        token:
  vsphere:
    credentials:
      - name: default
        username:
        password:
        vmNetName:
  packet:
    credentials:
      - name: default
        apiKey:
        projectId:
        billingCycle:
  gcp:
    credentials:
      - name: default
        serviceAccount:
        network:
        subnetwork:
```
