### ISSUE TITLE
Move credentials to presets

### ISSUE THREAD

**Issue by zreigz** [kubermatic/kubermatic#3699]
**User Story**
Credentials are part of presets right now.

**Acceptance criteria**
Change credentials.yaml to presets.yaml:
```
presets:
  digitalocean:
    credentials:
      - name: zz
        token: zz
  azure:
    credentials:
      - name: azure
        tenantId: aa
        subscriptionId: bb
        clientId: cc
        clientSecret: cc
  aws:
    credentials:
      - name: aws
        accessKeyId: dd
        secretAccessKey: tt
  openstack:
    credentials:
      - name: openstack
        username: 
        password: 
        tenant: 
        domain: DEFAULT
  hetzner:
    credentials:
      - name: default
        token:
  vsphere:
    credentials:
      - name: default
        username: a
        password: b
  packet:
    credentials:
      - name: default
        apiKey:
        projectId:
  gcp:
    credentials:
      - name: default
        serviceAccount:
```

Change credentials path: GET /api/v1/providers/{provider_name}/presets/credentials
