### ISSUE TITLE
Allow to disable specific default addons

### ISSUE THREAD

**Issue by maciaszczykm** [kubermatic/kubermatic#4522]
**User Story** As a Kubermatic user I would like to be able to disable some of the default addons. The default addons can be specified in the `values.yaml` file:

```yaml
  controller:
    addons:
      kubernetes:
        # list of Addons to install into every user-cluster. All need to exist in the addons image
        defaultAddons:
        - canal
        - dashboard
        - dns
        - kube-proxy
        - openvpn
        - rbac
        - kubelet-configmap
        - default-storage-class
        - nodelocal-dns-cache
        - pod-security-policy
```

It would be nice to have a flag like `disabled-default-addons` which would disable some of the above.

**Acceptance criteria** 
- [ ] The functionality was implemented
- [ ] The secrets repo was updated to use this flag (https://github.com/kubermatic/secrets/pull/381#issuecomment-544536219 removed the `node-exporter` addon explicitly)
