### ISSUE TITLE
Broken vSphere cloud-config when using non standard port

### ISSUE THREAD

**Issue by chrkl** [kubermatic/kubermatic#4540]
**User Story**

When a vSphere endpoint uses a different port than 443, it is not properly transferred to the cloud-config.

Datacenter spec:
```
  vsphere1:
    location: Test VMware
    seed: seed-1
    country: DE
    spec:
      vsphere:
        endpoint: "https://10.0.0.1:9443"
```

Generated cloud-config:
```
[Global]
    ...
    port              = "443"
    insecure-flag     = true
    ...
    server            = "10.0.0.1:9443"

```

Creating worker nodes works, but creating a PV fails with

`“Failed to provision volume with StorageClass "standard": Post https://[10.0.0.1:9443]:443/sdk: dial tcp: lookup 10.0.0.1:9443: no such host”`

**Acceptance criteria**

The port from the vSphere endpoint in the datacenter spec should be translated properly to the port attribute in the cloud-config.
