### ISSUE TITLE
Prometheus runbook_url is broken

### ISSUE THREAD

**Issue by toschneck** [kubermatic/kubermatic#4828]
**User Story**
Due to the changed doc repository structure in https://github.com/loodse/docs/pull/203 the `runbook_url` is not working anymore.
```
alert: HttpProbeFailed
expr: probe_success != 1
for: 5m
labels:
  severity: warning
annotations:
  message: Probing the blackbox-exporter target {{ $labels.instance }} failed.
  runbook_url: https://docs.kubermatic.io/monitoring/runbook/#alert-httpprobefailed
```
This also effects the older releases. The new URL need contain the current version of kubermatic. For the above example it would be 
```
runbook_url: https://docs.kubermatic.io/kubermatic/v2.12/monitoring/runbook/#alert-httpprobefailed
```
**Acceptance criteria**

- [ ] field `runbook_url` points to a working URL of the dedicated release
