### ISSUE TITLE
Addon deployment fails

### ISSUE THREAD

**Issue by toschneck** [kubermatic/kubermatic#4980]
**Bug Report**

Version: `weekly-2020-03`
In the release development of 2.13, the default user of the controller-manager have been changed to `nobody`. As unwanted side effect the copied addon files `/opt/addon/xxx` are not readable anymore and the deployment of the addons fails with an error "Cannot access manifest under /opt/addon/xxx"

At the current installer chart we need to modify the init container. Adding a `chmod a+r` solved the issue at my site:
```
      initContainers:
      - name: copy-addons-kubernetes
        image: '{{ .Values.kubermatic.controller.addons.kubernetes.image.repository }}:{{ .Values.kubermatic.controller.addons.kubernetes.image.tag }}'
        imagePullPolicy: {{ .Values.kubermatic.controller.addons.kubernetes.image.pullPolicy }}
        command: ["/bin/sh"]
        args:
        - "-c"
        - "mkdir -p /opt/addons/kubernetes && cp -r /addons/* /opt/addons/kubernetes"
        - "&& chmod a+r -R /opt/addons/kubernetes"
        volumeMounts:
        - name: addons
          mountPath: /opt/addons
      - name: copy-addons-openshift
        image: '{{ .Values.kubermatic.controller.addons.openshift.image.repository }}:{{ .Values.kubermatic.controller.addons.openshift.image.tag }}'
        imagePullPolicy: {{ .Values.kubermatic.controller.addons.openshift.image.pullPolicy }}
        command: ["/bin/sh"]
        args:
        - "-c"
        - "mkdir -p /opt/addons/openshift && cp -r /addons/* /opt/addons/openshift"
        - "&& chmod a+r -R /opt/addons/kubernetes"
```

**Acceptance criteria**
- [ ] Addons can get deployed without errors
