### ISSUE TITLE
Dashboard addon deletion failes after 2.13 upgrade

### ISSUE THREAD

**Issue by chrkl** [kubermatic/kubermatic#5194]
**User Story**

The dashboard addon has been removed in 2.13. The addon_controller tries to remove the dashboard from existing clusters. Since the directory is missing in the addon image as well, the controller runs into an error:
```
kubermatic_addon_controller  failed to delete manifests from cluster: failed to get addon manifests: failed to parse addon templates in /opt/addons/kubernetes/dashboard: open /opt/addons/kubernetes/dashboard: no such file or directory
```

**Acceptance criteria**

Dashboard addon should be deleted without errors.

**Comment by zreigz** [comment]
@chrkl Is it a constant problem? I've reproduced this by stopping the seed-controller-manager and adding the dashboard addon without manifest files. When I started the controller the kubermatic_addoninstaller_controller removed the dashboard addon without errors:
```
{"level":"info","time":"2020-05-14T07:22:42.306Z","logger":"kubermatic_addoninstaller_controller","caller":"addoninstaller/addoninstaller_controller.go:227","msg":"deleting addon dashboard from cluster cluster-b4j24dwlrp","worker-name":"","request":"/b4j24dwlrp","clustertype":"kubernetes"}
```
The important thing is to remove the dashboard from the addon list `kubermatic/values.yaml`:

```
    addons:
      kubernetes:
        # list of Addons to install into every user-cluster. All need to exist in the addons image
        defaultAddons:
        - canal
        - csi
        - dns
        - kube-proxy
        - openvpn
        - rbac
        - kubelet-configmap
        - default-storage-class
        - nodelocal-dns-cache
        - pod-security-policy
        - logrotate
```
Maybe the seed-controller-manager restart will help.
