### ISSUE TITLE
Seed Controller: spec.nodeport_proxy.annotations get not applied

### ISSUE THREAD

**Issue by toschneck** [kubermatic/kubermatic#5631]
**User Story**
If the following config get applied, the seed controller does not respect the annotation at the service (or any other object). Due to the docs, this should annotate the LB service: 
https://github.com/kubermatic/kubermatic/blob/master/docs/zz_generated.seed.yaml#L210

`seedconfig.yaml`:
```
apiVersion: kubermatic.k8s.io/v1
kind: Seed
metadata:
  name: k1-kubevirt
  namespace: kubermatic
spec:
  # reference to the kubeconfig to use when connecting to this seed cluster
  kubeconfig:
    name: seed-kubeconfig-k1-kubevirt
    namespace: kubermatic
  ### Seed location
  # Optional: Country of the seed as ISO-3166 two-letter code, e.g. DE or UK.
  # For informational purposes in the Kubermatic dashboard only.
  country: US
  location: "Sunnyvale"
  # Datacenters contains a map of the possible datacenters (DCs) in this seed.
  # Each DC must have a globally unique identifier (i.e. names must be unique
  # across all seeds).
  datacenters:
    k1-sunnyvale:
      country: US
      location: "Sunnyvale"
      spec:
        kubevirt: {}
  nodeport_proxy:
    # Annotations are used to further tweak the LoadBalancer integration with the
    # cloud provider where the seed cluster is running.
    # FIXME: doesn't work
    annotations:
      metallb.universe.tf/address-pool: "kubermatic-nodeport"
```
`svc.nodeport-proxy.output.yaml`:
```
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-07-09T20:46:39Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:loadBalancer:
          f:ingress: {}
    manager: controller
    operation: Update
    time: "2020-07-09T20:46:39Z"
  name: nodeport-proxy
  namespace: kubermatic
  resourceVersion: "5267088"
  selfLink: /api/v1/namespaces/kubermatic/services/nodeport-proxy
  uid: 33ae068d-e18c-4ccf-80b3-743e938a5c92
spec:
  clusterIP: 10.111.115.174
  externalTrafficPolicy: Cluster
  ports:
  - name: healthz
    nodePort: 31571
    port: 8002
    protocol: TCP
    targetPort: 8002
  selector:
    app.kubernetes.io/name: nodeport-proxy-envoy
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 192.168.150.110
```
**Acceptance criteria**
- [ ] Annotations get respected by service `nodeport-proxy`

**Comment by erdii** [comment]
https://github.com/kubermatic/kubermatic/pull/5730 should fix this

**Comment by erdii** [comment]
@kdomanski verified today with `kubermatic-ee:latest` image tag!

```yaml
apiVersion: kubermatic.k8s.io/v1
kind: Seed
metadata:
  annotations:
    helm.fluxcd.io/antecedent: kubermatic:helmrelease/kubermatic-seeds
  name: master
  namespace: kubermatic
spec:
  country: DE
  datacenters:
    aws-eu-central-1:
      country: DE
      location: Frankfurt
      node: {}
      spec:
        aws:
          images: null
          region: eu-central-1
        enforceAuditLogging: false
        enforcePodSecurityPolicy: false
  kubeconfig:
    name: kubeconfig-master
  location: Frankfurt
  nodeport_proxy:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: '*.master.example.com'
    envoy:
      resources: {}
    envoy_manager:
      resources: {}
    updater:
      resources: {}
```

results in

```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: '*.master.example.com'
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  name: nodeport-proxy
  namespace: kubermatic
spec:
  clusterIP: 10.108.239.35
  externalTrafficPolicy: Cluster
  ports:
  - name: healthz
    nodePort: 31627
    port: 8002
    protocol: TCP
    targetPort: 8002
  selector:
    app.kubernetes.io/name: nodeport-proxy-envoy
  sessionAffinity: None
  type: LoadBalancer
```
