### ISSUE TITLE
Can't set addons.kubermatic.io/ensure label for accessible addons

### ISSUE THREAD

**Issue by phiphi282** [kubermatic/kubermatic#5672]
**User Story**
Currently there doesn't seem to be a way to set the `addons.kubermatic.io/ensure` label for accessible addons.
Because of this all addons created from within the ui aren't being reconciled after the initial creation.

**Acceptance criteria**
Having a way of specifying which addons should get the ensure label on them. Preferably this should be done when setting up the accessible addons.
For example like this:
```yaml
kubermatic_accessible_addons:
- name: node-exporter
  labels:
    addons.kubermatic.io/ensure: true
```

But it is also possible to add this as an api option when creating the addon.
