### ISSUE TITLE
Unable to create node deployment: Internal error occurred: failed calling webhook "machine-controller.kubermatic.io-machinedeployments"

### ISSUE THREAD

**Issue by balous** [kubermatic/kubermatic#5828]
**User Story**
I've setup a new Kubermatic 2.14.4 instance, than I've created a new openstack cluster. Now I am unable to create the first node deployment.

I am using the web UI, I just click the `Add Node Deployment`, fill in the name and leave other fields unchanged. After sumbitting the form, I receive following error:

```
"code":500,"message":"failed to create machine deployment: Internal error occurred: failed calling webhook \"machine-controller.kubermatic.io-machinedeployments\": Post https://machine-controller-webhook.cluster-9vspt68hwq.svc.cluster.local./machinedeployments?timeout=30s: Service Unavailable"
```

There are no relevant log messages in the `machine-controller-webhook` pod.

I've tried to exec into the `kubermatic-api` pod:

```
petr@baloun:~/prace/kubermatic/install$ kubectl exec -n kubermatic -ti kubermatic-api-6887878cdd-tx78r bash
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.

nobody@kubermatic-api-6887878cdd-tx78r:/$ curl -k 'https://machine-controller-webhook.cluster-9vspt68hwq.svc.cluster.local./machinedeployments?timeout=30s'
{"response":{"uid":"","allowed":false,"status":{"metadata":{},"message":"header Content-Type was , expected application/json"}}}nobody@kubermatic-api-6887878cdd-tx78r:/$ 
nobody@kubermatic-api-6887878cdd-tx78r:/$ 
```

So I think the webhook basically works, it just issues 500 without anything in the log.

**Acceptance criteria**
No error, node deployment is created.

**Comment by xrstf** [comment]
Does this happen consistently or randomly?

**Comment by balous** [comment]
It happens every time.

BTW, one thing is strange to me. The machine controller and the machine controller webhook pods are running but there are none of machine controller CRDs (Machine, MachineDeployment).

Could this be related?

**Comment by irozzo-1A** [comment]
> BTW, one thing is strange to me. The machine controller and the machine controller webhook pods are running but there are none of machine controller CRDs (Machine, MachineDeployment).

This is weird because the webhook server should not start until the CRDs are installed, and apparently you got a response when you tested with curl.

https://github.com/kubermatic/kubermatic/blob/c380b3b33e1cfb5337dcd661aeb3481feeb80bc2/pkg/resources/machinecontroller/webhook.go#L138

Note that CRDs should be deployed in the user cluster and not in the seed cluster that is hosting the control plane of your k8s cluster. Are you sure that you used the right kubeconfig? Please provide the output of the following command:
```
kubectl api-resources --api-group=cluster.k8s.io
```

You can download the kubeconfig of your cluster from Kubermatic UI.

**Comment by balous** [comment]
Yes, this is what I've learned yesterday - I need to search for this in the user cluster.

OK, so the connection works but the machine-controller-webhook doesn't log anything useful. Is there a way how to increase it's log verbosity? My manual changes to its deployment are instantly reverted (by master controller?) and I can't find any relevant setting in the `cluster` resource.

**Comment by irozzo-1A** [comment]
Indeed the manifests get reconciled by the `seed-controller-manager`, if you want to manually increase verbosity you should "pause" the cluster first:
```
kubectl patch cluster "YOUR-CLUSTER" --type='json' -p='[{"op": "replace", "path": "/spec/pause", "value":false}]'
```

**Comment by balous** [comment]
Thank you, good hint. So I've increased the level to `-v 150` but still no connection logging.

But I've noticed something different - I downscaled the webhook deployment to 0 pods. `curl` correctly fails with connection refused but apiserver is still logging `Service Unavailable`. 

So where the apiserver acutally gets connected to?

**Comment by balous** [comment]
I've got the culprit - in `kubermatic` seed I've set `proxy_settings` and the `apiserver` pod got following env:

```
        env:
        - name: HTTP_PROXY
          value: http://proxy.dev.dszn.cz:3128
        - name: HTTPS_PROXY
          value: http://proxy.dev.dszn.cz:3128
        - name: http_proxy
          value: http://proxy.dev.dszn.cz:3128
        - name: https_proxy
          value: http://proxy.dev.dszn.cz:3128
        - name: NO_PROXY
          value: apiserver-external.cluster-nd4mlnrt56.svc.cluster.local.
        - name: no_proxy
          value: apiserver-external.cluster-nd4mlnrt56.svc.cluster.local.
```

But the hook is at `https://machine-controller-webhook.cluster-nd4mlnrt56.svc.cluster.local.` so the apiserver uses the proxy to reach it. Shouldn't be there some kind of wildcard for `no_proxy`.
