### ISSUE TITLE
Grafana  - User cluster metrics are incorrect

### ISSUE THREAD

**Issue by toschneck** [kubermatic/kubermatic#5914]
**User Story**
At the dashboard wrong metrics are getting shown:
- doubled cluster numbers at every metric
- wrong cluster type

```
k get cluster
NAME         AGE   HUMANREADABLENAME   OWNER             VERSION   PAUSED
wchcmmgwn8   20m   goofy-hypatia       tobi@loodse.com   1.18.8    false
```
```
k get cluster -o yaml | grep -C 5 openshift 
--
      scheduler:
        replicas: 1
    exposeStrategy: NodePort
    humanReadableName: goofy-hypatia
    oidc: {}
    openshift: {}
    pause: false
    version: 1.18.8
  status:
    cloudMigrationRevision: 2
    conditions:
```
Env: https://grafana.run-2.lab.kubermatic.io/
Version:  `weekly-2020-38`

![image.png](https://images.zenhubusercontent.com/5b6454d031c5fe7463837d8b/e81ef859-c7ad-4636-943c-6ad3a3b2a515)
**Acceptance criteria**
- Display correct metrics
