### ISSUE TITLE
Enabling encryption at rest for user clusters

### ISSUE THREAD

**Issue by irozzo-1A** [kubermatic/kubermatic#5946]
**User Story**

Kubernetes provides the possibility of encrypting some resources at rest in ETCD: https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/
It could be useful to introduce the possibility of encrypting resources containing credentials (e.g. secrets, machine-deployments?). 

We should be careful when introducing this because it brings some risks: e.g. if the encryption key is rotated restoring an old Etcd backup could result in data loss.

**Acceptance criteria**
It is possible to create user clusters with encryption at rest activated on resources containing secrets.

```[tasklist]
### Tasks
- [ ] #8400
- [ ] #8401 
- [ ] #8402 
- [ ] #8403 
- [ ] #8405
- [ ] https://github.com/kubermatic/kubermatic/issues/12377
```

**Comment by KhizerRehan** [comment]
**Note for Implementation (KKP Controller Side)**

Currently, the UI adds an Encryption At Rest checkbox in the Cluster Wizard and prompts the user for an encryption key. This key is used to create a Secret in the `kubermatic` namespace, since the cluster namespace does not yet exist at creation time.

The KKP controller must handle `mirroring` this Secret from the `kubermatic` namespace into the **user cluster namespace** once the cluster is created.

Example:

```yaml
encryptionConfiguration:
  enabled: true
  resources:
    - secrets
  secretbox:
    keys:
      - name: encryption-key-cluster-<cluster_id>
        secretRef:
          name: encryption-key-cluster-<cluster_id>
          key: key
```

Without this controller logic, cluster creation is blocked with:

```yaml
errorMessage: 'failed to ensure that the Secret exists: failed to ensure Secret
    cluster-sbx4h6dckv/apiserver-encryption-configuration: failed to generate object:
    Secret "encryption-key-cluster-<cluster_id>" not found'
```
**Action Required:**
Implement a controller in KKP to detect when **Encryption At Rest** is enabled on a cluster using the [cluster annotations added here](https://github.com/kubermatic/dashboard/pull/7525/files#diff-b024561f7f258488d96c6a6bdc4151a1e4b612169d30b3982c880a947f5b20b0R433) during cluster creation.

FYI: Encryption at Rest is only available during cluster creation. [This PR](https://github.com/kubermatic/dashboard/pull/7525) does not support  ~disabling~, enabling, or re-enabling the feature afterward. Clarification is needed on key rotation if a user provides a new key.
