### ISSUE TITLE
Seed Controller Manager - imagePullPolicy for Addons needs to be "Always"

### ISSUE THREAD

**Issue by toschneck** [kubermatic/kubermatic#6081]
**User Story**
Currently there is no option to ensure an updated Addon Image get pulled, because of `imagePullPolicy: IfNotPresent` is set.
This is bad and we need somehow ether or:
- as default `      imagePullPolicy: Always`
- or Configureable at `KubermaticConfiguration1` > `spec.userCluster.addons.kubernetes.dockerRepository`

*Pod Yaml:*
```yaml
spec:
  containers:
    - args:
        - -logtostderr
        - -internal-address=0.0.0.0:8085
        - -kubernetes-addons-path=/opt/addons/kubernetes
        - -openshift-addons-path=/opt/addons/openshift
        - -worker-count=4
        - -backup-container=/opt/backup/store-container.yaml
        - -cleanup-container=/opt/backup/cleanup-container.yaml
        - -seed-admissionwebhook-cert-file=/opt/seed-webhook-serving-cert/serving.crt
        - -seed-admissionwebhook-key-file=/opt/seed-webhook-serving-cert/serving.key
        - -namespace=kubermatic
        - -external-url=tobi.lab.kubermatic.io
        - -datacenter-name=tobi-vsphere-seed
        - -etcd-disk-size=5Gi
        - -feature-gates=OIDCKubeCfgEndpoint=true,OpenIDAuthPlugin=true
        - -nodeport-range=30000-32767
        - -worker-name=
        - -kubermatic-image=quay.io/kubermatic/kubermatic-ee
        - -dnatcontroller-image=quay.io/kubermatic/kubeletdnat-controller
        - -etcd-launcher-image=quay.io/kubermatic/etcd-launcher
        - -overwrite-registry=
        - -apiserver-default-replicas=2
        - -controller-manager-default-replicas=1
        - -scheduler-default-replicas=1
        - -max-parallel-reconcile=10
        - -apiserver-reconciling-disabled-by-default=false
        - -pprof-listen-address=:6600
        - -in-cluster-prometheus-disable-default-rules=false
        - -in-cluster-prometheus-disable-default-scraping-configs=false
        - -dynamic-datacenters=true
        - -docker-pull-config-json-file=/opt/docker/.dockerconfigjson
        - -v=2
        - -versions=/opt/extra-files/versions.yaml
        - -updates=/opt/extra-files/updates.yaml
        - -openshift-addons-file=/opt/extra-files/openshift-addons.yaml
        - -kubernetes-addons-file=/opt/extra-files/kubernetes-addons.yaml
        - -oidc-issuer-url=https://tobi.lab.kubermatic.io/dex
        - -oidc-issuer-client-id=kubermaticIssuer
        - -oidc-issuer-client-secret=NS4WyQojqMU7gEqlAUcAoq0kcbCxzehX
        - -oidc-ca-file=/opt/dex-ca/caBundle.pem
      command:
        - seed-controller-manager
      image: quay.io/kubermatic/kubermatic-ee:weekly-2020-42
      imagePullPolicy: IfNotPresent
      name: controller-manager
      ports:
        - containerPort: 8085
          name: metrics
          protocol: TCP
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 200m
          memory: 512Mi
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /opt/addons/
          name: addons
          readOnly: true
        - mountPath: /opt/backup/
          name: backup-container
          readOnly: true
        - mountPath: /opt/seed-webhook-serving-cert/
          name: seed-webhook-serving-cert
          readOnly: true
        - mountPath: /opt/docker/
          name: dockercfg
          readOnly: true
        - mountPath: /opt/extra-files/
          name: extra-files
          readOnly: true
        - mountPath: /opt/dex-ca
          name: dex-ca
          readOnly: true
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: kubermatic-seed-token-s4b5g
          readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
    - name: dockercfg
  initContainers:
    - args:
        - -c
        - mkdir -p /opt/addons/kubernetes && cp -r /addons/* /opt/addons/kubernetes
      command:
        - /bin/sh
      image: quay.io/kubermatic/ps-addons:weekly-2020-42
      imagePullPolicy: IfNotPresent
      name: copy-addons-kubernetes
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /opt/addons/
          name: addons
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: kubermatic-seed-token-s4b5g
          readOnly: true
    - args:
        - -c
        - mkdir -p /opt/addons/openshift && cp -r /addons/* /opt/addons/openshift
      command:
        - /bin/sh
      image: quay.io/kubermatic/openshift-addons:weekly-2020-42
      imagePullPolicy: IfNotPresent
      name: copy-addons-openshift
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /opt/addons/
          name: addons
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: kubermatic-seed-token-s4b5g
          readOnly: true
```
**Acceptance criteria**
- Update Addon Images for K8s and Openshift get polled at everytime
