### ISSUE TITLE
Implement User-Management Step1

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#622]
Kubermatic-API:

- Whenever a user does a apicall we create:
  - the user resource if it does not exist
  - the user ClusterRole gets created
- User Impersonation (https://kubernetes.io/docs/admin/authentication/#user-impersonation):
Every call from the DataProvider should use Impersonation with the logged in user.
- Whenever a cluster / ssh-key gets created:
  - update the user's ClusterRole to give access to the created resource

The default/empty user ClusterRole should probably look the following:
```yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: <SOME_GENERIC_NAME>
rules:
- apiGroups:
  - kubermatic.k8s.io
  resources:
  - clusters
  - usersshkeies
  verbs:
  - "create"
```

When the user has a cluster named `zcwpma` it should look like:
```yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: <SOME_GENERIC_NAME>
rules:
- apiGroups:
  - kubermatic.k8s.io
  resources:
  - clusters
  - usersshkeies
  verbs:
  - "create"
- apiGroups:
  - kubermatic.k8s.io
  resources:
  - clusters
  resourceNames:
  - zcwpma
  verbs:
  - "get"
  - "update"
  - "patch"
  - "delete"
```

Open questions:
- I assume we need an Authorization-provider which is responsible for creating/updating the rbac rules?

FYI: @realfake
