### ISSUE TITLE
Extend Cluster CRD for PodNodeSelectorAdmissionPluginConfig

### ISSUE THREAD

**Issue by zreigz** [kubermatic/kubermatic#6304]
**User Story**
The user should be able to configure PodNodeSelector plugin when it's used during the cluster creation.
Finally, the API deployment controller should create the file:
```
podNodeSelectorPluginConfig:
  clusterDefaultNodeSelector: <node-selectors-labels>
  namespace1: <node-selectors-labels>
  namespace2: <node-selectors-labels>
```
