### ISSUE TITLE
Multi-cluster IP range management

### ISSUE THREAD

**Issue by shaase-ctrl** [kubermatic/kubermatic#6421]
**User Story**
As kubermatic user cluster creator,
I have one static IP range for multiple clusters. Each cluster should allocate on his own a dedicate set of IPs (e.g. defined by a parameter input at an KKP addon).

The detailed use case right now ist the output of the configuration of MetalLB, e.g.:
```
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - {{ .Variables.addressPoolRange }}
```
https://github.com/kubermatic-labs/community-components/blob/master/kubermatic-addons/custom-addon/metallb/address-pools-cm.yaml#L12

In an managed service scenario, the infrastructure setup should  allocate the needed numbers of free virtual IPs by a centralized component or mechanism to avoid conflicting IP allocations for the n used metalLB setups. 

**Acceptance criteria**
- [ ] the solutions provides allocation of a defined number of IPs
- [ ] a release cycle is somehow in place (open for any mechanism)
