### ISSUE TITLE
CA certs are not mounted to the controller-manager

### ISSUE THREAD

**Issue by youssefazrak** [kubermatic/kubermatic#6469]
**User Story**

Running Kubermatic 2.15.7 without the external CCM for Openstack, the `controller-manager` "crashloops". After further investigation, the image has been changed from `hyperkube` (2.14) to `kube-controller-manager`. This new image doesn't contain by default CA certs and those are supposed to be mounted from the Host itself. 
In the case of this reported bug, the nodes were running CentOS 7.9. 
This doesn't happen and thus triggers the error below, as the CA is not recognized as a valid root authority: 

`F0127 07:39:37.262651       1 controllermanager.go:230] error building controller context: cloud provider could not be initialized: could not init cloud provider "openstack": Post https://some.website.com: x509: certificate signed by unknown authority
`

**Acceptance criteria**
Have the CA store installed inside the container.

**Comment by xrstf** [comment]
I'm trying to replicate the issue, but when I hack myself to a controller-manager with internal openstack support, the controller-manager pod _does_ mount the CAs from the hosts (i.e. the Seed cluster's hosts):

```yaml
  - hostPath:
      path: /etc/ssl/certs
      type: DirectoryOrCreate
    name: ca-certs
  - hostPath:
      path: /usr/share/ca-certificates
      type: DirectoryOrCreate
    name: usr-share-ca-certificates
```

I assume the problem is that the Seed in this case is running CentOS and the certs are in different places there maybe?
