### ISSUE TITLE
Failed to show MachineDeployments

### ISSUE THREAD

**Issue by xrstf** [kubermatic/kubermatic#6637]
**User Story**
In my usercluster, I opted to manage the MachineDeployments myself. I created two simple MD's, they are basically identical and look like this:

```yaml
apiVersion: cluster.k8s.io/v1alpha1
kind: MachineDeployment
metadata:
  name: worker-dedicated
  namespace: kube-system
spec:
  # do not specify replica count, as its going to be dynamically altered
  # for our custom scale up/down solution
  # replicas: 3
  selector:
    matchLabels:
      prow: worker-dedicated
  strategy:
    rollingUpdate:
      maxSurge: 5
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        prow: worker-dedicated
    spec:
      metadata:
        annotations:
          # Make rotation quick. Nothing but test jobs is supposed to be on these nodes
          kubermatic.io/skip-eviction: "true"
        labels:
          # Required by the CSI drivers
          csi.hetzner.cloud/location: __HETZNER_LOCATION__
          # Mark dedicated nodes, so we can schedule only specific jobs here using nodeSelector.
          kubermatic.io/dedicated: "true"
      providerSpec:
        value:
          cloudProvider: hetzner
          cloudProviderSpec:
            location: __HETZNER_LOCATION__
            serverType: ccx31
            networks:
              - __HETZNER_NETWORK__
            labels:
              keep: "true"
          operatingSystem: ubuntu
          sshPublicKeys:
            - __SSH_PUBKEY__
      versions:
        kubelet: 1.20.2
```

The MD works just fine, but when I list my clusters in the KKP dashboard I get:

![screenshot-2021-03-04-161032](https://user-images.githubusercontent.com/127499/109984907-846cdc00-7d04-11eb-9cf4-b7d8760a474f.png)

Maybe because I don't have an `operatingSystemSpec`?

**Acceptance criteria**
- [ ] The error does not happen anymore, I guess?

**Comment by kron4eg** [comment]
I would say it's more bug of a machine-controller webook that it let machineDeployment without `operatingSystemSpec`

**Comment by xrstf** [comment]
What I posted above was my template, the actual object in the cluster has this spec:

```yaml
spec:
   minReadySeconds: 0
   progressDeadlineSeconds: 600
   replicas: 3
   revisionHistoryLimit: 1
   selector:
   matchLabels:
      workerset: captain-workers
   strategy:
   rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
   type: RollingUpdate
   template:
   metadata:
      creationTimestamp: null
      labels:
         workerset: captain-workers
      namespace: kube-system
   spec:
      metadata:
         creationTimestamp: null
         labels:
         workerset: captain-workers
      providerSpec:
         value:
         cloudProvider: hetzner
         cloudProviderSpec:
            image: ubuntu-20.04
            labels:
               captain-workers: workers
               keep: "true"
            location: nbg1
            networks:
            - "1018508"
            serverType: cpx31
         operatingSystem: ubuntu
         operatingSystemSpec:
            distUpgradeOnBoot: false
         sshPublicKeys:
         - <my key here>
      versions:
         kubelet: 1.19.7
```
