### ISSUE TITLE
Webhook errors in kubermatic-operator

### ISSUE THREAD

**Issue by HaveFun83** [kubermatic/kubermatic#6749]
Hi we recently upgrade our kubermatic cluster from 2.14.beta to 2.16.5.
The upgrade went fine so far but we see the following errros within the kubermatic-operator log
```json
{"level":"error","time":"2021-03-23T14:30:16.117Z","logger":"controller","caller":"controller/controller.go:218","msg":"Reconciler error","controller":"kubermatic-seed-operator","name":"kubermatic","namespace":"kubermatic","error":"failed to reconcile AdmissionWebhooks: failed to ensure ValidatingWebhookConfiguration /kubermatic-clusters: failed waiting for the cache to contain our latest changes: timed out waiting for the condition"}
{"level":"error","time":"2021-03-23T14:30:16.145Z","logger":"kubermatic-seed-operator","caller":"seed/reconciler.go:76","msg":"failed to reconcile","request":"/kubermatic","error":"failed to reconcile AdmissionWebhooks: failed to ensure ValidatingWebhookConfiguration /kubermatic-clusters: failed waiting for the cache to contain our latest changes: timed out waiting for the condition"}
{"level":"error","time":"2021-03-23T14:30:16.145Z","logger":"controller","caller":"controller/controller.go:218","msg":"Reconciler error","controller":"kubermatic-seed-operator","name":"kubermatic","namespace":"","error":"failed to reconcile AdmissionWebhooks: failed to ensure ValidatingWebhookConfiguration /kubermatic-clusters: failed waiting for the cache to contain our latest changes: timed out waiting for the condition"}
```
All resources are in place.
```
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: kubermatic-clusters
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    caBundle: <ca b64enc>
    service:
      name: cluster-webhook
      namespace: kubermatic
      path: /validate-kubermatic-k8s-io-cluster
      port: 443
  failurePolicy: Fail
  matchPolicy: Exact
  name: clusters.kubermatic.io
  rules:
  - apiGroups:
    - kubermatic.k8s.io
    apiVersions:
    - '*'
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusters
    scope: Cluster
  sideEffects: None
  timeoutSeconds: 30
  ```

```
NAME                            TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                                                                                                          AGE     SELECTOR
endpoints/cluster-webhook         192.168.x.25:8100                                                      3h34m

NAME                              ENDPOINTS                                                                AGE
service/cluster-webhook         ClusterIP      10.x.x.x   <none>        443/TCP

NAME                                                        READY   STATUS    RESTARTS   AGE     IP               NODE                              NOMINATED NODE   READINESS GATES
pod/kubermatic-seed-controller-manager-5fc884f5db-zbdzv     1/1     Running   0          173m    192.168.x.x   kubermatic-dev1-worker-0   <none>           <none>
```

Maybe someone can help to find the root cause here?
tia
