### ISSUE TITLE
Allow for regular Constraint parameters instead of rawJSON

### ISSUE THREAD

**Issue by lsviben** [kubermatic/kubermatic#6770]
Currently the Kubermatic Constraints `parameters` field which should mirror the Gatkeeper Constraint parameters field is just a raw JSON representation of it:

```
spec:
  constraintType: K8sRequiredLabels
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Namespace"]
  parameters:
    rawJSON: '{"labels":["gatekeeper"]}'
```

```
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Namespace"]
  parameters:
    labels: ["gatkeeper"]
```

This was because there was some issue (i dont remeber correctly) with json/encoding and that because for the Gatkeeper Constraint we need to use Unstructured. But I think its time to take another look at this so it will be easier for users to create Kubermatic Constraints.
