### ISSUE TITLE
Multi AZ/Zone support for nodes

### ISSUE THREAD

**Issue by scheeles** [kubermatic/kubermatic#678]
**Note:** Issues relating to this epic are managed [via ZenHub](https://app.zenhub.com/workspace/o/kubermatic/kubermatic/issues/678).

As a user of kubermatic i want to add nodes from different AvailabilityZones to my cluster.

**Comment by kdomanski** [comment]
It seems that from the machine-controller POV all the necessary pieces are there. What is missing is Kubermatic API/UI part. cc @p0lyn0mial

**Comment by kron4eg** [comment]
bump

**Comment by toschneck** [comment]
currently this only blocked by the API/UI.
A current **workaround** is, to create a second MachineDeployment and adjust the AZ and the subnet over `kubectl edit -n kube-system machinedeployment` and it works, e.g.:
```
     providerSpec:
        value:
          cloudProvider: aws
          cloudProviderSpec:
            accessKeyId: ""
            ami: ""
            availabilityZone: eu-west-1b   #updated
            diskSize: 25
            diskType: standard
            instanceProfile: kubermatic-instance-profile-xvwqx68s9v
            instanceType: t3.medium
            region: eu-west-1
            secretAccessKey: ""
            securityGroupIDs:
            - sg-0e75780326baaaed2
            subnetId: subnet-d62b68b2 #updated
```
