### ISSUE TITLE
(oauth) Connector icon is hard-coded to Google

### ISSUE THREAD

**Issue by michalvanco** [kubermatic/kubermatic#7096]
**User Story**
When I want to integrate dex with other OIDC provider, I get the hard-coded Google icon in the theme instead of general OIDC icon.

![image](https://user-images.githubusercontent.com/1215131/119358766-3c2cdc80-bca9-11eb-8b52-8f928e047269.png)

**Acceptance criteria**
OIDC icon is present when adding connector of type `oidc`.

Like:
![image](https://user-images.githubusercontent.com/1215131/119358895-58307e00-bca9-11eb-9b52-617312759e36.png)

Problem comes from https://github.com/kubermatic/kubermatic/blob/master/charts/oauth/theme/styles.css#L147, switching to `url(../static/img/oidc-icon.svg);` solves the problem (+ some additional update of color on background).

Related code snippet for connector example:
```
      connectors:
      - type: oidc
        id: oidc-test
        name: OIDC test
        config:
          issuer: https://xxx/
          clientID: xxx
          clientSecret: xxx
          redirectURI: https://xxx/dex/callback
          scopes:
          - profile
```
