### ISSUE TITLE
Expose strategy LoadBalancer does not work in AWS

### ISSUE THREAD

**Issue by Ottovsky** [kubermatic/kubermatic#7108]
**User Story**

I tried to create a user cluster in AWS (seed cluster in aws as well)  with expose strategy loadbalancer but the user cluster was never provisioned and seed-controller-manager seemed to be stuck waiting for cluster to enter healthy condition. I am running kubermatic version `quay.io/kubermatic/kubermatic:v2.17.0` . 

After a quick research, the problem seems to be in the way, aws is populating k8s service with the lb details:
```
apiVersion: v1
kind: Service
metadata:
 (...)
  name: front-loadbalancer
 (...)
spec:
  clusterIP: <ip>
  externalTrafficPolicy: Cluster
  ports:
  - name: secure
    nodePort: 32092
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: nodeport-proxy-envoy
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: <aws lb hostname>
```

The hostname from status is not supported by kubernetes controller from seed-controller-manager: ([code](https://github.com/kubermatic/kubermatic/blob/v2.17.0/pkg/resources/address/address.go#L105-L119)) and as consequence seed-controller-manager is silently failing: ([code](https://github.com/kubermatic/kubermatic/blob/v2.17.0/pkg/controller/seed-controller-manager/kubernetes/resources.go#L73-L74))

**Acceptance criteria**

The loadbalancer expose strategy works in AWS
