### ISSUE TITLE
OpenStack cluster stuck in deletion with failed network cleanup

### ISSUE THREAD

**Issue by wozniakjan** [kubermatic/kubermatic#7112]
**User Story**
An OpenStack cluster created through kkp dev has been stuck in terminating for almost 6 days - https://dev.kubermatic.io/projects/7fztn48c97/clusters/lv2jljfmwf. There is a reoccurring error wrt network cleanup.

```
$ k logs -n kubermatic kubermatic-seed-controller-manager-86bf8ddfdb-j87ms | grep lv2jljfmwf | tail -n1
{"level":"error","time":"2021-05-26T12:23:55.849Z","logger":"kubermatic_cloud_controller","caller":"cloud/cloud_controller.go:139","msg":"Reconciling failed","worker-name":"","request":"/lv2jljfmwf","cluster":"lv2jljfmwf","error":"failed cloud provider cleanup: failed to delete network 'kubernetes-lv2jljfmwf': failed to get network 'kubernetes-lv2jljfmwf' by name: no network named 'kubernetes-lv2jljfmwf' with external=false found","errorCauses":[{"error":"failed cloud provider cleanup: failed to delete network 'kubernetes-lv2jljfmwf': failed to get network 'kubernetes-lv2jljfmwf' by name: no network named 'kubernetes-lv2jljfmwf' with external=false found"}]}
```

<details><summary>$ k describe cluster lv2jljfmwf</summary>
<p>

```yaml
Name:         lv2jljfmwf
Namespace:    
Labels:       project-id=7fztn48c97
Annotations:  <none>
Address:
  Admin Token:    *** redacted ***
  External Name:  lv2jljfmwf.europe-west3-c.dev.kubermatic.io
  Internal URL:   apiserver-external.cluster-lv2jljfmwf.svc.cluster.local.
  Ip:             192.168.30.10
  Port:           6443
  URL:            https://lv2jljfmwf.europe-west3-c.dev.kubermatic.io:6443
API Version:      kubermatic.k8s.io/v1
Kind:             Cluster
Metadata:
  Creation Timestamp:             2021-05-20T13:32:15Z
  Deletion Grace Period Seconds:  0
  Deletion Timestamp:             2021-05-20T14:04:46Z
  Finalizers:
    kubermatic.io/cleanup-credentials-secrets
    kubermatic.io/cleanup-openstack-network-v2
    kubermatic.io/cleanup-openstack-router-subnet-link-v2
    kubermatic.io/cleanup-openstack-router-v2
    kubermatic.io/cleanup-openstack-security-group
    kubermatic.io/cleanup-openstack-subnet-v2
  Generation:        2569
  Resource Version:  784062775
  Self Link:         /apis/kubermatic.k8s.io/v1/clusters/lv2jljfmwf
  UID:               b842bd80-73cd-4767-95f6-119254209ed3
Spec:
  Audit Logging:
  Cloud:
    Dc:  syseleven-dbl1
    Openstack:
      Credentials Reference:
        Name:            credential-openstack-lv2jljfmwf
        Namespace:       kubermatic
      Floating Ip Pool:  ext-net
      Network:           kubernetes-lv2jljfmwf
      Router ID:         bd357a8d-99b8-4f7c-abe9-e7b2dc8aacc7
      Security Groups:   kubernetes-lv2jljfmwf
      Subnet ID:         b10711ce-4e0f-4a8b-a4c7-5619c6aa3c2f
  Cluster Network:
    Dns Domain:  cluster.local
    Pods:
      Cidr Blocks:
        172.25.0.0/16
    Proxy Mode:  ipvs
    Services:
      Cidr Blocks:
        10.240.16.0/20
  Components Override:
    Apiserver:
      Endpoint Reconciling Disabled:  false
      Replicas:                       2
    Controller Manager:
      Leader Election:
      Replicas:  1
    Etcd:
      Cluster Size:  3
    Prometheus:
    Scheduler:
      Leader Election:
      Replicas:               1
  Enable User SSH Key Agent:  true
  Expose Strategy:            Tunneling
  Features:
    External Cloud Provider:  true
  Human Readable Name:        priceless-curie
  Oidc:
  Opa Integration:
  Pause:    false
  Version:  1.19.9
Status:
  Cloud Migration Revision:  2
  Conditions:
    kubermatic_version:    0eef31d0eca5bfa4e693aeee7677a080f81e119d
    Last Heartbeat Time:   2021-05-26T09:25:48Z
    Last Transition Time:  2021-05-26T09:25:48Z
    Status:                True
    Type:                  AddonControllerReconciledSuccessfully
    kubermatic_version:    0eef31d0eca5bfa4e693aeee7677a080f81e119d
    Last Heartbeat Time:   2021-05-26T09:25:24Z
    Last Transition Time:  2021-05-26T09:25:24Z
    Status:                True
    Type:                  AddonInstallerControllerReconciledSuccessfully
    kubermatic_version:    0eef31d0eca5bfa4e693aeee7677a080f81e119d
    Last Heartbeat Time:   2021-05-25T20:12:44Z
    Last Transition Time:  <nil>
    Status:                True
    Type:                  BackupControllerReconciledSuccessfully
    kubermatic_version:    0eef31d0eca5bfa4e693aeee7677a080f81e119d
    Last Heartbeat Time:   2021-05-25T20:13:14Z
    Last Transition Time:  <nil>
    Status:                False
    Type:                  CloudControllerReconcilledSuccessfully
    kubermatic_version:    0eef31d0eca5bfa4e693aeee7677a080f81e119d
    Last Heartbeat Time:   2021-05-25T20:13:18Z
    Last Transition Time:  <nil>
    Status:                False
    Type:                  ClusterControllerReconciledSuccessfully
    kubermatic_version:    5a0e6f09ec696e0f49c08103348120c9387b3619
    Last Heartbeat Time:   2021-05-20T13:33:41Z
    Last Transition Time:  <nil>
    Message:               Cluster has been initialized successfully
    Status:                True
    Type:                  ClusterInitialized
    kubermatic_version:    0eef31d0eca5bfa4e693aeee7677a080f81e119d
    Last Heartbeat Time:   2021-05-25T20:12:41Z
    Last Transition Time:  <nil>
    Status:                True
    Type:                  ComponentDefaulterReconciledSuccessfully
    kubermatic_version:    5a0e6f09ec696e0f49c08103348120c9387b3619
    Last Heartbeat Time:   2021-05-20T13:33:06Z
    Last Transition Time:  <nil>
    Message:               Etcd Cluster has been initialized successfully
    Status:                True
    Type:                  EtcdClusterInitialized
    kubermatic_version:    0eef31d0eca5bfa4e693aeee7677a080f81e119d
    Last Heartbeat Time:   2021-05-26T01:19:46Z
    Last Transition Time:  2021-05-26T01:19:46Z
    Status:                True
    Type:                  MLAControllerReconciledSuccessfully
    kubermatic_version:    0eef31d0eca5bfa4e693aeee7677a080f81e119d
    Last Heartbeat Time:   2021-05-25T20:12:38Z
    Last Transition Time:  <nil>
    Status:                True
    Type:                  MachineDeploymentReconciledSuccessfully
    kubermatic_version:    5a0e6f09ec696e0f49c08103348120c9387b3619
    Last Heartbeat Time:   2021-05-20T13:33:22Z
    Last Transition Time:  <nil>
    Status:                True
    Type:                  MonitoringControllerReconciledSuccessfully
    kubermatic_version:    0eef31d0eca5bfa4e693aeee7677a080f81e119d
    Last Heartbeat Time:   2021-05-26T09:25:33Z
    Last Transition Time:  2021-05-26T09:25:33Z
    Message:               All control plane components are up to date
    Reason:                ClusterUpdateSuccessful
    Status:                True
    Type:                  SeedResourcesUpToDate
    kubermatic_version:    0eef31d0eca5bfa4e693aeee7677a080f81e119d
    Last Heartbeat Time:   2021-05-25T20:12:38Z
    Last Transition Time:  <nil>
    Status:                True
    Type:                  UpdateControllerReconciledSuccessfully
  Extended Health:
    Apiserver:                        1
    Cloud Provider Infrastructure:    1
    Controller:                       1
    Etcd:                             1
    Machine Controller:               1
    Openvpn:                          1
    Scheduler:                        1
    User Cluster Controller Manager:  1
  kubermatic_version:                 0eef31d0eca5bfa4e693aeee7677a080f81e119d
  Last Updated:                       <nil>
  Namespace Name:                     cluster-lv2jljfmwf
  User Email:                         jan@loodse.com
Events:
  Type     Reason            Age                  From                         Message
  ----     ------            ----                 ----                         -------
  Warning  ReconcilingError  14m (x28 over 176m)  kubermatic_cloud_controller  failed cloud provider cleanup: failed to delete network 'kubernetes-lv2jljfmwf': failed to get network 'kubernetes-lv2jljfmwf' by name: no network named 'kubernetes-lv2jljfmwf' with external=false found
```

</p>
</details>

**Acceptance criteria**
- the cluster should eventually finish being terminated
