### ISSUE TITLE
KKP API server - Azure VNet / Subnet validation don't respect VNet Resource Group

### ISSUE THREAD

**Issue by toschneck** [kubermatic/kubermatic#7130]
KKP version: `2.17.0`
After Applying the Cluster Spec with a selected VNet Resource Group, the validation of the VNet and Subnet fails, due to the usage of the wrong resource group. As far as I understood the concept, for every query for VNet / Subnet the dedicated VNet resource group needs to be used, otherwise the resource is not visible/usable.
**Error:**
```
Error 400 invalid cluster: invalid cloud spec: network.VirtualNetworksClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ResourceNotFound" Message="The Resource 'Microsoft.Network/virtualNetworks/cldazcsnet001-vnet05' under resource group 'cldazkubermatictest-rg' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix"

Error 400 invalid cluster: invalid cloud spec: network.SubnetsClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ResourceNotFound" Message="The Resource 'Microsoft.Network/virtualNetworks/subnets' under resource group 'cldazkubermatictest-rg' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix"
```
![image](https://user-images.githubusercontent.com/4659261/119797449-88ab2e80-beda-11eb-90a8-661fb4814202.png)

Used `preset` config:
```yaml
apiVersion: kubermatic.k8s.io/v1
kind: Preset
metadata:
  name: cld-dev
spec:
  # spec see https://github.com/kubermatic/kubermatic/blob/8236b27127c8ff87303ff5c4ff898d55ca3113b3/pkg/crd/kubermatic/v1/preset.go#L244
  azure:
    tenantId: xxxxx
    subscriptionId: xxxxx
    clientId: xxx
    clientSecret: xxx
    resourceGroup: "cldazkubermatictest-rg"
    subnet: "cldazcsnet001-vnet05-appl_kubermatic_mgmt"
    routeTable: ""
    securityGroup: "cldazkubermatictest-nsg"
    vnet: "cldazcsnet001-vnet05"
    vnetResourceGroup: "cldazcsnet001-rg"
```
I managed to skip the validation of `vnet` and  `subnet`, by keep it empty and patch the `vnet` `subnet` at the cluster spec by `kubectl edit cluster xxxx` it will come up and work:

```yaml
spec:
  auditLogging: {}
  cloud:
    azure:
      availabilitySet: kubernetes-cqmsvdkk5z
      credentialsReference:
        name: credential-azure-cqmsvdkk5z
        namespace: kubermatic
      resourceGroup: cldazkubermatictest-rg
      routeTable: kubernetes-cqmsvdkk5z
      securityGroup: cldazkubermatictest-nsg
      subnet: cldazcsnet001-vnet05-appl_kubermatic_mgmt #<<<< patched
      vnet: cldazcsnet001-vnet05   #<<<< patched
      vnetResourceGroup: cldazcsnet001-rg
    dc: cld-dev
```
