### ISSUE TITLE
mount own ca-bundle for storeuploader container

### ISSUE THREAD

**Issue by dbagarozza** [kubermatic/kubermatic#7155]
**User Story**

We have set up our own Minio client, which runs with its own self-signed certificates.  We just have the problem that the Storeuploader container from you can not access our Minio, we get an SSL error.

Is it possible to pass or mount our own CA bundle in the Storeuploader container?

We use the Kubermatic operator and configure the Storeuploader container in the values.yaml.

    backupStoreContainer: |-
      name: store-container
      image: quay.io/kubermatic/s3-storer:v0.1.6
      command:
      - /bin/sh
      - -c
      - |
        set -euo pipefail
        s3-storeuploader store --ca-bundle= --endpoint xxx --bucket xxx --create-bucket --prefix $CLUSTER --file /backup/snapshot.db
        s3-storeuploader delete-old-revisions --ca-bundle=xxx --endpoint xxx --bucket xxx --prefix $CLUSTER --file /backup/snapshot.db --max-revisions 20
      image: quay.io/kubermatic/s3-storer:v0.1.6
      name: store-container
      env:
      - name: ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: s3-credentials-customer
            key: ACCESS_KEY_ID
      - name: SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: s3-credentials-customer
            key: SECRET_ACCESS_KEY
      volumeMounts:
      - name: etcd-backup
        mountPath: /backup

There is a flag "--ca-bundle" in the storeuploader container. But how can I pass a custom ca-bundle?

**Acceptance criteria**

Possible to pass a own ca-bundle to storeuploader container.

**Comment by kron4eg** [comment]
`/etc/ca-bundle` is automatically mounted

https://github.com/kubermatic/kubermatic/blob/master/pkg/controller/seed-controller-manager/backup/backup_controller.go#L353-L357

from the configMap
https://github.com/kubermatic/kubermatic/blob/master/pkg/controller/seed-controller-manager/backup/backup_controller.go#L385-L394

**Comment by dbagarozza** [comment]
@kron4eg  ok, we'll take a look. Thank you.

**Comment by dbagarozza** [comment]
@kron4eg we have the problem that the ca-bundle is not mounted automatically. The ca bundle must be directly in the namespace where the Kubermatic Operator Configuration is deployed or?

**Comment by kron4eg** [comment]
please take a look at https://docs.kubermatic.com/kubermatic/v2.17/tutorials_howtos/kkp_configuration/

More specifically:
```
  # CABundle references a ConfigMap in the same namespace as the KubermaticConfiguration.
  # This ConfigMap must contain a ca-bundle.pem with PEM-encoded certificates. This bundle
  # automatically synchronized into each seed and each usercluster. APIGroup and Kind are
  # currently ignored.
  caBundle:
    # APIGroup is the group for the resource being referenced.
    # If APIGroup is not specified, the specified Kind must be in the core API group.
    # For any other third-party types, APIGroup is required.
    apiGroup: null
    # Kind is the type of resource being referenced
    kind: ""
    # Name is the name of resource being referenced
    name: ca-bundle
```
