### ISSUE TITLE
Hetzner  Client Clusters unreachable

### ISSUE THREAD

**Issue by shibumi** [kubermatic/kubermatic#7187]
**User Story**

When creating a new cluster via Kubermatic the cluster's KubeAPI is unreachable:

![https://kurisu.shibumi.dev/share/img-2021-06-05-00-51-53.png](https://kurisu.shibumi.dev/share/img-2021-06-05-00-51-53.png)

The related cluster namespace looks fine:

```
chris motoko /tmp 0:53:34  kubernetes-admin@master kubermatic
❯ kubens cluster-v8z7lwk25p
Context "kubernetes-admin@master" modified.
Active namespace is "cluster-v8z7lwk25p".
chris motoko /tmp 0:53:38  kubernetes-admin@master cluster-v8z7lwk25p
❯ kg po
NAME                                                   READY   STATUS    RESTARTS   AGE
pod/apiserver-74487756f-ghm59                          3/3     Running   0          79m
pod/apiserver-74487756f-qftth                          3/3     Running   0          79m
pod/controller-manager-995c8bbd-c5j4x                  2/2     Running   0          79m
pod/dns-resolver-79f66db94f-7nxtg                      2/2     Running   0          79m
pod/dns-resolver-79f66db94f-q79dw                      2/2     Running   0          79m
pod/etcd-0                                             1/1     Running   0          79m
pod/etcd-1                                             1/1     Running   0          79m
pod/etcd-2                                             1/1     Running   0          79m
pod/hcloud-cloud-controller-manager-564749d7fb-7vlwr   2/2     Running   0          79m
pod/kube-state-metrics-556447988d-fb9g9                1/1     Running   0          77m
pod/kubernetes-dashboard-5555c5488c-rjndp              1/1     Running   2          79m
pod/kubernetes-dashboard-5555c5488c-vnwqz              1/1     Running   2          79m
pod/machine-controller-6f4c869b58-p7d8l                1/1     Running   1          79m
pod/machine-controller-webhook-6ffd4b69bc-hzg95        1/1     Running   0          79m
pod/metrics-server-5ff76484bc-lfktz                    3/3     Running   1          79m
pod/metrics-server-5ff76484bc-zfzf9                    3/3     Running   0          79m
pod/openvpn-server-9598f966f-qhffz                     3/3     Running   0          79m
pod/prometheus-0                                       1/1     Running   0          77m
pod/scheduler-76b9d8f7d4-nmp8g                         2/2     Running   0          79m
pod/usercluster-controller-f8748c5b6-h5hbs             1/1     Running   0          79m
```

The seed cluster configuration looks as follows:
```yaml
---
apiVersion: kubermatic.k8s.io/v1
kind: Seed
metadata:
  name: kubermatic
  namespace: kubermatic
spec:
  # these two fields are only informational
  country: DE
  location: Falkenstein

  # List of datacenters where this seed cluster is allowed to create clusters in
  # In this example, user cluster will be deployed in eu-central-1 on AWS.
  datacenters:
    hetzner-fsn1:
      location: Falkenstein 1 DC 8
      country: DE
      spec:
        hetzner:
          datacenter: fsn1-dc8
          network: "default"
  # reference to the kubeconfig to use when connecting to this seed cluster
  kubeconfig:
    name: kubeconfig-hetzner
    namespace: kubermatic
```

The "default" network is a manually created network `172.16.0.0/16` and VMs got created. The loadbalancer in Hetzner is healthy. The client cluster has  an apiserver-external service:
```
chris motoko ~/kubermatic/examples 0:55:40 a9833cb1 master  kubernetes-admin@master cluster-v8z7lwk25p
❯ kg svc
NAME                                 TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)             AGE
service/apiserver-external           NodePort    10.103.114.112   <none>        443:30931/TCP       81m
service/dns-resolver                 ClusterIP   10.105.81.183    <none>        53/UDP              81m
service/etcd                         ClusterIP   None             <none>        2379/TCP,2380/TCP   81m
service/machine-controller-webhook   ClusterIP   10.101.197.246   <none>        443/TCP             81m
service/metrics-server               ClusterIP   10.101.106.141   <none>        443/TCP             81m
service/openvpn-server               NodePort    10.102.4.183     <none>        1194:32003/TCP      81m
service/prometheus                   ClusterIP   None             <none>        9090/TCP            80m
```

Do I need to expose this NodePort manually? I see two Hetzner LoadBalancers. One for the master-cluster KubeAPI on Port 6443->6443 and one LoadBalancer for the master cluster Ingress on port 80/443.

My guess is that we are missing either an Ingress for the external API Server OR a LoadBalancer service. Am I correct?
Isn't Kubermatic supposed to create this? Or do I need to expose every cluster manually to access it via kubeAPI?

Is there another way to access the cluster from the outside?

**Acceptance criteria**
