### ISSUE TITLE
Kubernetes Dashboard Pods don't use specified ImagePullSecrect for OverwriteRegistry

### ISSUE THREAD

**Issue by toschneck** [kubermatic/kubermatic#7274]
**User Story**
In the `KubermaticConfiguration` the following config have been set:
```yaml
userCluster:
    overwriteRegistry: our-private-registry.de
```
Also the `imagePullSecret` for this registry has been set in the config. When creating a user cluster, all images get pulled from the registry with the secret, it seems only `kubernetes-dashboard` Pods does not have the `imagePullSecret` set, so pulling of the dashboard fails. All other pods have this setting.

**Dashboard Deployment**:
```yaml
apiVersion: apps/v1
kind: Deployment
# ...
spec:
  template:
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: kubernetes-dashboard
                  cluster: ctxlms22tr
              topologyKey: kubernetes.io/hostname
            weight: 100
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: kubernetes-dashboard
              topologyKey: kubernetes.io/hostname
            weight: 10
      containers:
      - args:
        - -endpoint
        - https://apiserver-external.cluster-ctxlms22tr.svc.cluster.local./healthz
        - -insecure
        - -retries
        - "100"
        - -retry-wait
        - "2"
        - -timeout
        - "1"
        - -command
        - '{"command":"/dashboard","args":["--kubeconfig","/etc/kubernetes/kubeconfig/kubeconfig","--namespace","kubernetes-dashboard","--enable-insecure-login"]}'
        command:
        - /http-prober-bin/http-prober
        image: git-images.internal.customer-support.de/7009-03-opti/customer/opti-kubermatic/kubernetesui/dashboard:v2.0.4
        imagePullPolicy: IfNotPresent
        name: kubernetes-dashboard
        ports:
        - containerPort: 9090
          protocol: TCP
        resources:
          limits:
            cpu: 250m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsUser: 1001
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/kubernetes/kubeconfig
          name: kubernetes-dashboard-kubeconfig
          readOnly: true
        - mountPath: /tmp
          name: tmp-volume
        - mountPath: /http-prober-bin
          name: http-prober-bin
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - /bin/cp
        - /usr/local/bin/http-prober
        - /http-prober-bin/http-prober
        image: git-images.internal.customer-support.de/7009-03-opti/customer/opti-kubermatic/kubermatic/http-prober:v0.3.2
        imagePullPolicy: IfNotPresent
        name: copy-http-prober
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /http-prober-bin
          name: http-prober-bin
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: kubernetes-dashboard-kubeconfig
        secret:
          defaultMode: 420
          secretName: kubernetes-dashboard-kubeconfig
      - emptyDir: {}
        name: tmp-volume
      - emptyDir: {}
```
As the yaml shows the pod spec is missing the `imagePullSecrets`config:
```yaml
spec:
  containers:
    #...
  imagePullSecrets:
  - name: xxxx
```

**Acceptance criteria**
- [ ] every kkp managed component is respecting the `imagePullSecrets` configured in `KubermaticConfiguration`

**Temporary workaround for one cluster:**
1. Pause cluster: `kubectl edit cluster xxxxx` => `spec.pause: true`
2. Edit Dashboard Deployment: `kubectl edit -n cluster-xxxx deployment kubernetes-dashboard` => set `imagePullSecret` section at pod
**Attention:** As long the cluster is paused no updates or reconciling get processed! If you want to enable it just set the `spec.pause: false` and the cluster get reconciled to the original setting (e.g. after the bugfix).
