### ISSUE TITLE
User Cluster Backup Naming not S3 compliant 

### ISSUE THREAD

**Issue by toschneck** [kubermatic/kubermatic#7337]
**User Story**
Based on the AWS docu, the current used filenames are not compliant with the S3 standard `Safe characters`: https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-keys.html

This leads to errors at e.g. Netapp S3 storage (potential also some others). Issue needs to get fixed:
- legacy backup controller: https://github.com/kubermatic/kubermatic/blob/master/docs/zz_generated.kubermaticConfiguration.yaml#L193
- new etcd Backup and Restore Controller: https://docs.kubermatic.com/kubermatic/v2.17/cheat_sheets/etcd/backup-and-restore/

**Acceptance criteria**
- Alle created Files of KKP Backup Solution are compliant to S3

**Comment by toschneck** [comment]
@shaase-ctrl please little prio, not highest

**Comment by xrstf** [comment]
@toschneck Can you provide more information, like an example filename that is invalid? The links in your ticket sadly don't help me right now to figure out where to look. Off the top of my head, this is the only place where we construct filenames: https://github.com/kubermatic/kubermatic/blob/master/pkg/storeuploader/storeuploader.go#L95

**Comment by toschneck** [comment]
It was `zbxmw69bfb-storeuploader-2021-12-01T06:26:18-snapshot.db` of the etcd-snapshots, `:`
 are not allowed, but often work. But e.g. the NetApp S3 service won't allow it.
 
 It seams the issue is not present anymore with the backup controller, after we configured it in the seed the backup creates other file names. But it's unclear what is included in the file as it has no file ending.
 ```yaml
 spec:
  # Etcd backup for UserCluster
  # Feature link - https://docs.kubermatic.com/kubermatic/v2.18/tutorials_howtos/etcd_backups/
  backupRestore:
    s3BucketName: kubermatic-etcd-backups
    s3Endpoint: https://minio.minio-backup.svc.cluster.local
 ```
files:
```
[root@docker-desktop /]# mc ls --insecure minio/kubermatic-etcd-backups/lxzqr9t5xw-default-backups-2022-04-06
[2022-04-06 08:31:58 UTC]  48MiB lxzqr9t5xw-default-backups-2022-04-06t08-31-54
[2022-04-06 08:51:58 UTC]  48MiB lxzqr9t5xw-default-backups-2022-04-06t08-51-54
[2022-04-06 09:11:58 UTC]  48MiB lxzqr9t5xw-default-backups-2022-04-06t09-11-54
[2022-04-06 09:31:59 UTC]  48MiB lxzqr9t5xw-default-backups-2022-04-06t09-31-54
[2022-04-06 09:51:58 UTC]  48MiB lxzqr9t5xw-default-backups-2022-04-06t09-51-54
```
