### ISSUE TITLE
Test Alertmanager Configuration Endpoints(#6943)

### ISSUE THREAD

**Issue by vgramer** [kubermatic/kubermatic#7691]
**Acceptance criteria:**
* alertmanager configuration can be manage though v2 API endpoints

for more information, please take look at #6943

**Comment by zreigz** [comment]
Added Alertmanager Config:
```
template_files: {}
alertmanager_config: |
  route:
    receiver: 'gmail-notifications'
  receivers:
  - name: 'gmail-notifications'
    email_configs:
    - to: zreigz@gmail.com
      from: zreigz@gmail.com
      smarthost: smtp.gmail.com:587
      auth_username: zreigz@gmail.com
      auth_identity: zreigz@gmail.com
      auth_password: xxx
      send_resolved: true
```
added Roule Group
```
name: high-throughput-log-streams
rules:
- alert: HighThroughputLogStreams
  expr: sum by(container)(rate({job=~"kube-system/.*"}[1m])) >= 1
  for: 1m
  labels:
    severity: critical
  annotations:
    title: "log stream is high"
    summary: "log stream is high"
```
alert received on email address

Follow the tutorial:
https://grafana.com/blog/2020/02/25/step-by-step-guide-to-setting-up-prometheus-alertmanager-with-slack-pagerduty-and-gmail/
