### ISSUE TITLE
Test Add Logs Type to RuleGroup list option(#7202)

### ISSUE THREAD

**Issue by vgramer** [kubermatic/kubermatic#7697]
**Acceptance criteria:**
* rule group can be filetred with type = logs in API endpoint

for more information, please take look at #7202

**Comment by zreigz** [comment]
added two types:
Metrics
```
name: instance-is-down
rules:
- alert: InstanceDown
  expr: up == 0
  for: 1m
  annotations:
    title: 'Instance {{ $labels.instance }} down'
    summary: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute.'
  labels:
    severity: 'critical'
```
Logs
```
name: high-throughput-log-streams
rules:
- alert: HighThroughputLogStreams
  expr: sum by(container)(rate({job=~"kube-system/.*"}[1m])) >= 50
  for: 1m
  labels:
    severity: critical
  annotations:
    title: "log stream is high"
    summary: "log stream is high
```
