### ISSUE TITLE
Wrong resourceName in nginx-ingress-controller role for leader

### ISSUE THREAD

**Issue by michalvanco** [kubermatic/kubermatic#7941]
**User Story**
If you install new version of nginx-ingress helm chart (delivered with KKP 2.18.1), nginx pods will include following error:

```
Failed to update lock: configmaps "ingress-controller-leader" is forbidden: User "system:serviceaccount:nginx-ingress-controller:nginx-ingress-controller" cannot update resource "configmaps" in API group "" in the namespace "nginx-ingress-controller"
```

This is caused by the invalid role definition:
```
- apiGroups:
  - ""
  resources:
  - configmaps
  resourceNames:
  - ingress-controller-leader-nginx
  verbs:
  - get
  - update
```

Resource name should be `ingress-controller-leader`.

It does not affect pod readiness so unless you take a look at logs, nginx installation seems to be happy.

**Acceptance criteria**
Fix the helm chart (role) not to include the problem with roles and permissions.

Related issue: https://github.com/kubernetes/ingress-nginx/issues/7632
