### ISSUE TITLE
NodePort Proxy Resource Limits are not set by seed controller

### ISSUE THREAD

**Issue by toschneck** [kubermatic/kubermatic#8257]
**User Story**
Currently the deployment of the nodeport proxy is not respecting any resource limits. Even Default or overwriten values of
https://github.com/kubermatic/kubermatic/blob/master/docs/zz_generated.seed.yaml#L328
```

apiVersion: kubermatic.k8s.io/v1
kind: Seed
metadata:
  name: <<exampleseed>>
  namespace: kubermatic
spec:
#......
  nodeport_proxy:
    # Annotations are used to further tweak the LoadBalancer integration with the
    # cloud provider where the seed cluster is running.
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3600"
      service.beta.kubernetes.io/aws-load-balancer-type: nlb
    # Disable will prevent the Kubermatic Operator from creating a nodeport-proxy
    # setup on the seed cluster. This should only be used if a suitable replacement
    # is installed (like the nodeport-proxy Helm chart).
    disable: false
    # Envoy configures the Envoy application itself.
    envoy:
      # DockerRepository is the repository containing the component's image.
      docker_repository: docker.io/envoyproxy/envoy-alpine
      # Resources describes the requested and maximum allowed CPU/memory usage.
      resources:
        # Limits describes the maximum amount of compute resources allowed.
        # More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
        limits:
          cpu: "1"
          memory: 128Mi
        # Requests describes the minimum amount of compute resources required.
        # If Requests is omitted for a container, it defaults to Limits if that is explicitly specified,
        # otherwise to an implementation-defined value.
        # More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
        requests:
          cpu: 50m
          memory: 32Mi
    # EnvoyManager configures the Kubermatic-internal Envoy manager.
    envoy_manager:
      # DockerRepository is the repository containing the component's image.
      docker_repository: quay.io/kubermatic/nodeport-proxy
      # Resources describes the requested and maximum allowed CPU/memory usage.
      resources:
        # Limits describes the maximum amount of compute resources allowed.
        # More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
        limits:
          cpu: 150m
          memory: 48Mi
        # Requests describes the minimum amount of compute resources required.
        # If Requests is omitted for a container, it defaults to Limits if that is explicitly specified,
        # otherwise to an implementation-defined value.
        # More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
        requests:
          cpu: 50m
          memory: 32Mi
```
If we take a look at the deployments at the kubermatic namespace, it don't get set:
```
k get deployments.apps nodeport-proxy-envoy -o yaml | kexp 
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "323"
  labels:
    app.kubernetes.io/managed-by: kubermatic-operator
  name: nodeport-proxy-envoy
  namespace: kubermatic
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: nodeport-proxy-envoy
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        fluentbit.io/parser: json_iso
        prometheus.io/metrics_path: /stats/prometheus
        prometheus.io/port: "8002"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: nodeport-proxy-envoy
    spec:
      containers:
      - args:
        - -listen-address=:8001
        - -envoy-node-name=kube
        - -envoy-admin-port=9001
        - -envoy-stats-port=8002
        command:
        - /envoy-manager
        image: quay.io/kubermatic/nodeport-proxy:v2.18.2
        imagePullPolicy: IfNotPresent
        name: envoy-manager
        ports:
        - containerPort: 8001
          name: grpc
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/envoy
          name: envoy-config
      - args:
        - -c
        - /etc/envoy/envoy.yaml
        - --service-cluster
        - cluster0
        - --service-node
        - kube
        command:
        - /usr/local/bin/envoy
        image: docker.io/envoyproxy/envoy-alpine:v1.17.1
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - wget
              - -qO-
              - http://127.0.0.1:9001/healthcheck/fail
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8002
            scheme: HTTP
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 1
        name: envoy
        ports:
        - containerPort: 8002
          name: stats
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/envoy
          name: envoy-config
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: dockercfg
      initContainers:
      - args:
        - /envoy.yaml
        - /etc/envoy/envoy.yaml
        command:
        - /bin/cp
        image: quay.io/kubermatic/nodeport-proxy:v2.18.2
        imagePullPolicy: IfNotPresent
        name: copy-envoy-config
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/envoy
          name: envoy-config
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccount: nodeport-proxy
      serviceAccountName: nodeport-proxy
      terminationGracePeriodSeconds: 30
      volumes:
      - name: envoy-config
```
```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "277"
  labels:
    app.kubernetes.io/managed-by: kubermatic-operator
  name: nodeport-proxy-updater
  namespace: kubermatic
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: nodeport-proxy-updater
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        fluentbit.io/parser: json_iso
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: nodeport-proxy-updater
    spec:
      containers:
      - args:
        - -lb-namespace=$(NAMESPACE)
        - -lb-name=nodeport-proxy
        command:
        - /lb-updater
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: quay.io/kubermatic/nodeport-proxy:v2.18.2
        imagePullPolicy: IfNotPresent
        name: lb-updater
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: dockercfg
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccount: nodeport-proxy
      serviceAccountName: nodeport-proxy
      terminationGracePeriodSeconds: 30
```
As the nodeport deployment is currently fully managed by the operator, there is no way to overwrite the settings as the seed controller could not paused or scaled down for longer time.

Currently this happens on all versions, so we should backport to all currently maintained versions.

**Acceptance criteria**
- [ ] Seed spec of nodeport resource limit is respected in both deployments
- [ ] Overwrites and default are propagated by the seed controller 
- [ ] Backport fix to current maintained releases
