### ISSUE TITLE
Document KubeVirt configuration required by KKP

### ISSUE THREAD

**Issue by mfranczy** [kubermatic/kubermatic#8493]
Document KubeVirt configuration for infrastructure cluster.
The update should be placed here https://docs.kubermatic.com/kubermatic/v2.18/architecture/requirements/support_policy/provider_support_matrix/kubevirt/kubevirt/.

The configuration we require:

```
apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: kubevirt
spec:
  configuration:
    developerConfiguration:
      featureGates:
      - DataVolumes
      - SRIOV
      - LiveMigration
      - CPUManager
      - CPUNodeDiscovery
      - Sidecar
      - Snapshot
      - HotplugVolumes
```
