### ISSUE TITLE
Test cilium with ipvs proxy mode - Test Release 2.19

### ISSUE THREAD

**Issue by vgramer** [kubermatic/kubermatic#8656]
Create a user-cluster on top cloud providers with iptables proxy mode for every os:

- [x] ubuntu
- [x] centos
- [x] flatcar
- [x] RHEL

and check:
- [x] pod are running
- [x]  pods are accessible through pod ip
- [x]  pods are accessible through service
- [x]  install `Hubble` addon for CNI network observability and check it working

moreover:
- [X] Document cloud-provider / OS compatibility matrix. -> kubermatic/docs#922

Test on top cloud provider:
- [X] AWS [test results](https://github.com/kubermatic/kubermatic/issues/8656#issuecomment-1016496587)
- [x] Azure [test results](https://github.com/kubermatic/kubermatic/issues/8656#issuecomment-1017481460)
- [X] GCP [test results](https://github.com/kubermatic/kubermatic/issues/8656#issuecomment-1017911253)
- [X] OpenStack [test results](https://github.com/kubermatic/kubermatic/issues/8656#issuecomment-1017934589)
- [X] VMware  -> infra not available

YAML  and script used to test. the script don't test the node port problem:
<details >
<summary>yaml manifest</summary>

```yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: whoami

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
  namespace: whoami
spec:
  replicas: 2
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - whoami
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: whoami
          image: traefik/whoami:v1.6.0
          imagePullPolicy: IfNotPresent

---
apiVersion: v1
kind: Service
metadata:
  name: whoami
  namespace: whoami
  labels:
    app: whoami
spec:
  type: ClusterIP
  ports:
    - port: 80
      name: whoami
  selector:
    app: whoami

---
apiVersion: v1
kind: Service
metadata:
  name: whoami-lb
  namespace: whoami
  labels:
    app: whoami
spec:
#  type: NodePort
  type: LoadBalancer
  ports:
    - port: 80
      name: whoami
  selector:
    app: whoami


---
apiVersion: v1
kind: Pod
metadata:
  name: whoami-client
  namespace: whoami
spec:
  containers:
    - name: whoami-client
      image: giantswarm/tiny-tools:3.9
      command:
        - "sleep"
        - "infinity"
``` 
</details>

<details >
<summary>test script</summary>

**REQUIRE BASH >= 4.0**

```bash
#!/usr/bin/env bash
set -e


function error() {
	echo "Error: $@"
	exit 1
}

function print_and_exec(){
	echo "$@"
	eval "$@"
	echo ""
}

function print_info(){
	echo "########### CLUSTER INFO ########### "

	print_and_exec "kubectl get node -o wide"
	print_and_exec "kubectl get po -A -o wide"
	print_and_exec "kubectl -n '${NS}' get svc -o wide"

	echo -e "########### END CLUSTER INFO ###########\n"
}

function test_culr_pod_ip(){
	echo "########### TEST CURL POD IP ########### "
  IFS='
  '
  for pod_ip in ${SERVER_POD_IPS}; do
  	echo "testing pod ${pod_ip}"
  	response="$(kubectl -n "${NS}" exec ${CLIENT_POD} -- curl -s "${pod_ip}")"
  	if ! echo "${response}" | grep -q "${pod_ip}"; then
  		error "invalid response. can not find pod ip '$pod_ip' in response"
  	else
  		echo "=> OK"
  	fi
  done
  echo -e "########### END TEST CURL POD IP ##########\n"
}

function test_curl_clusterIP_service(){
	echo "########### TEST CURL CLUSTER IP SERVICE ###########"
	echo "test all pods behind cluster ip service respond"
  # build map[pod_name]bool
  declare -A servermap
  IFS='
  '
  for pod_name in ${SERVER_POD_NAMES}; do
  	servermap["${pod_name}"]=0
  done

  nb_pod="${#servermap[@]}"
  retries=$(($nb_pod * 5))
  different_response=0
  i=0

  while [[ ($i -le $retries) && ($different_response -ne $nb_pod) ]]; do
  	response_from="$(kubectl -n "${NS}" exec ${CLIENT_POD} -- curl -s -m 3 "${CLUSTER_IP_SERVICE}/api" | jq -r '.hostname')"

  	if [ -z "$response_from" ]; then
  		error "service not respond"
  	fi

  	if [[ "$response_from" == "null" ]]; then
  		error "can not get hostname from response"
  	fi

  	if ! test "${servermap[$response_from]+x}"; then
  		error "the hostname from the response is unknown. May be one pod has been recreated"
  	fi

  	if [ ${servermap[$response_from]} == 0 ]; then
  		echo "pod $response_from  OK"
  		servermap[$response_from]=1
  		different_response=$(($different_response + 1))
  	fi
  	i=$(($i + 1))
  done
	echo -e "########### END TEST CURL CLUSTER IP SERVICE ###########\n"
}

#function test_curl_lb_service_from_pod(){
#	echo "########### TEST CURL LB SERVICE FROM POD ###########"
#	external_ip="$(kubectl -n "$NS" get svc "$LB_SVC" -o custom-columns='HOSTNAME:.status.loadBalancer.ingress[0].hostname' --no-headers)"
#	if [[ "${external_ip}" == "<none>" ]]; then
#		external_ip="$(kubectl -n "$NS" get svc "$LB_SVC" -o custom-columns='HOSTNAME:.status.loadBalancer.ingress[0].ip' --no-headers)"
#	fi
# if [[ "${external_ip}" == "<none>" ]]; then
#		error "can not get loadBalancer external_ip."
#	fi
#	raw_response="$(kubectl -n "${NS}" exec ${CLIENT_POD} -- curl -s -m 3 ${external_ip}/api )"
#	response_from=$(echo "$raw_response" | jq -r '.hostname')
#
#	if [ -z "$response_from" ]; then
#    	error "service not respond"
#  fi
#
#	if [[ "$response_from" == "null" ]]; then
#		error "can not get hostname from response"
#	fi
#	echo "ok pod '$response_from' responded"
#	echo -e "########### ENDTEST CURL LB SERVICE ###########\n"
#}

function test_curl_lb_service_from_host(){
	echo "########### TEST CURL LB SERVICE FROM HOST ###########"
	external_ip="$(kubectl -n "$NS" get svc "$LB_SVC" -o custom-columns='HOSTNAME:.status.loadBalancer.ingress[0].hostname' --no-headers)"
	if [[ "${external_ip}" == "<none>" ]]; then
		external_ip="$(kubectl -n "$NS" get svc "$LB_SVC" -o custom-columns='HOSTNAME:.status.loadBalancer.ingress[0].ip' --no-headers)"
	fi

	if [[ "${external_ip}" == "<none>" ]]; then
		error "can not get loadBalancer external_ip."
	fi
	set +e
	raw_response="$(curl -s -m 3 ${external_ip}/api )"
	response_from=$(echo "$raw_response" | jq -r '.hostname')
  set -e
	if [ -z "$response_from" ]; then
    	error "service did not respond"
  fi

	if [[ "$response_from" == "null" ]]; then
		error "can not get hostname from response"
	fi
	echo "ok pod '$response_from' responded"
	echo -e "########### ENDTEST CURL LB SERVICE ###########\n"
}

NS='whoami'
CLIENT_POD='whoami-client'
SERVER_POD_SELECTOR="app=whoami"
CLUSTER_IP_SERVICE="whoami.whoami.svc.cluster.local"
LB_SVC='whoami-lb'


print_info

SERVER_POD_IPS="$(kubectl -n "${NS}" get po -l "${SERVER_POD_SELECTOR}" -o custom-columns='POD_IP:.status.podIP' --no-headers)"
SERVER_POD_NAMES="$(kubectl -n "${NS}" get po -l "${SERVER_POD_SELECTOR}" -o custom-columns='POD_NAME:.metadata.name' --no-headers)"

test_culr_pod_ip
test_curl_clusterIP_service
test_curl_lb_service_from_host

```
</details>
