### ISSUE TITLE
MLA Logging Health status not updated for `Down Status`

### ISSUE THREAD

**Issue by hdurand0710** [kubermatic/kubermatic#8691]
### What happened?
Refer to #8635 
Scenario:
Cluster healthy created on AWS with Logging. 
Update the ds promtail in user cluster (refer to scenario #8635) to have a non healthy promtail. 

```
Update the ds promtail is the user cluster with an invalid value, like config file
 spec:
      containers:
      - args:
        - -config.file=/etc/promtail/promtail.yaml2
```

```
% k get ds
NAME       DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
promtail   1         1         0       1            0           <none>          3h57m

```
-> Status for Logging should be red, but it remains green.

![Screenshot 2022-01-11 at 22.21.53.png](https://images.zenhubusercontent.com/613f8d176dae552873cbbca8/6dbe08df-fd81-4688-bec0-11839c820eab)
And status in `cluster CR` is also wrong -> issue in the back-end.

### What should happen?
Logging Status should be red.

### Environment

- KKP Version: v2.19.0-alpha.3
- Shared or separate master/seed clusters?: shared
- Master/seed cluster provider: AWS
