### ISSUE TITLE
flatcar update operator is not removed when no flatcar node in the cluster

### ISSUE THREAD

**Issue by hdurand0710** [kubermatic/kubermatic#8708]
https://test-env-kkp.ee.lab.kubermatic.io/
KKP version: v2.19.0-alpha.4
Refer to: #8664

### What happened?

- Cluster creation with flatcar.

- Create a new node deployment with a different OS in the cluster and delete the initial node deployment.

- Check if flatcar update operator does not exist after the procedure.

---------------------
After md with flatcar
```
% k get deploy -n kube-system
NAME                            READY   UP-TO-DATE   AVAILABLE   AGE
calico-kube-controllers         1/1     1            1           9m11s
coredns                         2/2     2            2           9m27s
flatcar-linux-update-operator   1/1     1            1           6m48s
openvpn-client                  1/1     1            1           9m13s
```

- Now add the md with `Ubuntu`
![Screenshot 2022-01-12 at 09.49.54.png](https://images.zenhubusercontent.com/613f8d176dae552873cbbca8/4cccd2cd-b56e-4c6a-8dc9-5b7d7f41ec94)

- Then remove the md Flatcar

** Issue found **
Deployment is still there:
```
% k get deploy
NAME                            READY   UP-TO-DATE   AVAILABLE   AGE
calico-kube-controllers         1/1     1            1           5h1m
coredns                         2/2     2            2           5h1m
flatcar-linux-update-operator   0/1     1            0           4h59m
openvpn-client                  1/1     1            1           5h1m
```
pod is `Pending`
```
% k get pod
NAME                                             READY   STATUS    RESTARTS   AGE
...
flatcar-linux-update-operator-7bcc7dfb69-qmqs8   0/1     Pending   0          166m
```
with status
```
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-01-12T10:54:32Z"
    message: '0/1 nodes are available: 1 node(s) didn''t match Pod''s node affinity/selector.'
    reason: Unschedulable
    status: "False"
    type: PodScheduled
```

### What should happen?
flatcar update operator should be removed.

### Environment

- KKP Version: v2.19.0-alpha.4
- Shared or separate master/seed clusters?: shared
- Master/seed cluster provider: AWS
