### ISSUE TITLE
Split oidc secrets for dashboard authentication and for kubeconfig of user clusters

### ISSUE THREAD

**Issue by michalvanco** [kubermatic/kubermatic#8723]
### What happened?
today I was troubleshooting authentication issue with KKP and Dex and option of OIDC KubeConfig for user clusters...
I have discovered that only option to make this work is to use the same OIDC secret for both dex clients (kubermatic and kubermaticIssuer) which I believe is not optimal because the secret for kubeconfig issuer is then exposed in the dowloaded kubeconfig for user cluster... see the example snippet
```
...
users:
- name: michal@kubermatic.com
  user:
    auth-provider:
      config:
        client-id: kubermaticIssuer
        client-secret: T79tKCSXoNNedNmDxaPyu8JQjOa6pqng    # <-- this one!!!
        id-token: eyJhbGciOiJSUzI1NiIsImtpZCI6ImY5MTc4YzNiNzBlNTM2MGU0ODRmMmU2NzQ4ZWVjOTA4ZDhiNzEwZjcifQ.eyJpc3MiOiJodHRwczovL2trcC1vcy1taWNoYWwubGFiLmt1YmVybWF0aWMuaW8vZGV4Iiwic3ViIjoiQ2lReE1tSTNOREU1WXkwd1lXTmxMVFJsTXpNdFlqWm1aQzB5TURCbU5UZzJaakZpTVdRU0JXeHZZMkZzIiwiYXVkIjoia3ViZXJtYXRpY0lzc3VlciIsImV4cCI6MTY0MjE2MTI4MiwiaWF0IjoxNjQyMDc0ODgyLCJhdF9oYXNoIjoibUgtdFE4ZmhqUzhnempuWWR0TjZrdyIsImNfaGFzaCI6IjRWcXVCdy1TX3l0U0Q4RmVadnhQU0EiLCJlbWFpbCI6Im1pY2hhbEBrdWJlcm1hdGljLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlfQ.stK2xDa6MSxs6CCHGYLVMfr7T3GaLJ2wF9hoJFZXfPtcF41vvA2jg8XJtRR4yoHAOjqWJCqRVZsV2nfFdD2LlwKII6rg08q2Ic0OJrc8CH73Iad5-KCF6SNT4CrNBwCWKaO7pUNQ2Jy9ea8UV6kM1XgZobtcgjvmvKTGVIQ_DPts1HLSFkFGTuRHPlnvsM7TE-fQJoKE_aQnrpi_wRkj7P_bQHO_m151Lf_sCRvKZXbpI-zD18DdwSj3wVCV7O73hqN3DcoxLWC2ptMuCCa-romoxMXwQoL0wz1RyI0qCMKECep25nRKQzxupK5kgoljuhMFpgSm9jR96B7cFRCXng
        idp-issuer-url: https://kkp-os-michal.lab.kubermatic.io/dex
        refresh-token: ChlmYWZmaWZpY2F6dDRpcnQ1Zmw1MmxnZHM3Ehlhbnh0eXYyYW54eXk3ZGRrcTNuNWZyZnNq
      name: oidc
```
here is also related configuration of dex cm:
```
    staticClients:
      - RedirectURIs:
        - https://kkp-os-michal.lab.kubermatic.io
        - https://kkp-os-michal.lab.kubermatic.io/projects
        id: kubermatic
        name: Kubermatic
        secret: T79tKCSXoNNedNmDxaPyu8JQjOa6pqng
      - RedirectURIs:
        - https://kkp-os-michal.lab.kubermatic.io/api/v1/kubeconfig
        id: kubermaticIssuer
        name: Kubermatic OIDC Issuer
        secret: T79tKCSXoNNedNmDxaPyu8JQjOa6pqng # <-- this one should be different!!!
```
and here is the snippet of the kkp config:
```
    auth:
        clientID: kubermatic
        issuerClientID: kubermaticIssuer
        issuerClientSecret: T79tKCSXoNNedNmDxaPyu8JQjOa6pqng # or this one should be used for issuer and dashboard authenticator should use the other value
        skipTokenIssuerTLSVerify: true
        tokenIssuer: https://kkp-os-michal.lab.kubermatic.io/dex
        issuerCookieKey: cW3pv8ULmsRUn99xNoo26JWFRqrfGrKY
        serviceAccountKey: MW7sN5pakF4JXzTE5f7zxDwtpwmUrysF
        issuerRedirectURL: https://kkp-os-michal.lab.kubermatic.io/api/v1/kubeconfig
```
as soon as you will set the different secret for kubermatic issuer - authentication to dashboard will stop working...
I believe the option issuerClientSecret should be only utilized for the issuer purpose and there should be probably separate authenticatorClientSecret for the purpose of the dashboard login ...
if you have a different secret for kubermaticIssuer, than the kubeconfig retrieval does not work
I have also found [documentation](https://docs.kubermatic.com/kubermatic/v2.18/tutorials_howtos/oidc_provider_configuration/share-_clusters_via_delegated_oidc_authentication/) that gives you info like:
```
dex:
  clients:
  - id: kubermaticIssuer
    name: Kubermatic OIDC Issuer
    secret: "" # put the value of issuerClientSecret here
    RedirectURIs:
    - https://example.com/api/v1/kubeconfig # issuerRedirectURL 
```

### What should happen?
Investigate situation deeper and consider usage of separate secrets for both auth clients.

### How to reproduce?
See above

### Environment

- KKP Version: 2.18.*
- Shared or separate master/seed clusters?: shared
- Master/seed cluster provider: does not matter

There was also internal discussion on slack (for reference) - https://kubermatic.slack.com/archives/C01FJ10TBM2/p1642079921012000
