### ISSUE TITLE
KubeVirt: Redundancy across multiple bare metal nodes

### ISSUE THREAD

**Issue by jograb** [kubermatic/kubermatic#8742]
### What would you like to be added? / User Story
Unfortunately, KKP does not currently seem to support affinity rules for KubeVirt. This leads to the problem that if I create a user cluster in KKP with let's say 6 replicas, but only have 4 bare metal nodes, that one bare metal node is running 2 KubeVirt instances. Now it could happen that a k8s deployment with 2 replicas is running on the same bare metal server. This should be avoided.

### Acceptance criteria
The ability to prevent a k8s deployment from running on 2 (or more) KubeVirt instances on the same bare metal node should be provided.

**Comment by jograb** [comment]
Here is a quick sketch that (hopefully) illustrates this problem 
![sketch_8742](https://user-images.githubusercontent.com/1290836/149954904-dee1a40d-483f-4161-83dd-5a55b02761d4.png)

**Comment by tafkam** [comment]
Depending on KVM sizes there should be no problem with multiple user-cluster nodes on one bare-metal node. The main problem here is, that the placement of the KVM pod is not propagated by node-labels into the user cluster. It's not possible to spread user-cluster workloads across different failure domains of the underlying bare-metal hosts.

Then the KVM pods should be scheduled with [Pod Topology Spread Constraints](https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/ ), because it's possible for a 6 node user-cluster, that 3 KVM pods get scheduled on a single baremetal host.

**Comment by shaase-ctrl** [comment]
Hello, what is your main concern? To configure for anti-affinity so that a crashing host does not affect a single user cluster? Or are there other cases that you had in mind?

**Comment by moadqassem** [comment]
Hi, so reading the above comments regarding the node<->machines labels propagation, shouldn't be any issue. We can add some configurations on the machine deployments, which gets carried out to the underlying VM and eventually the underlying VMI to invoke the scheduling process. Adjusting machines and VMs should be a valid approach following this: 

https://kubevirt.io/2020/Advanced-scheduling-with-affinity-rules.html

One thing to note here is, KKP doesn't and shouldn't have access to the bare metal nodes for the under kube(the k8s cluster where KubeVirt is installed). This exceeds the scope of the KubeVirt as a cloud provider integrated with KKP. 

Another thing to note here is, to which degree KKP is able to access the KubeVirt cluster? There should be some security concerns about this and limit KKP to access the KubeVirt cluster to the limit that it needs, and letting KKP operating on the underlying bare metal nodes, wouldn't be the best idea unless there is a platform extension in place. 

So, in general, user should be responsible for labelling the KubeVirt nodes and KKP would only propagate those labels and pass it to the MachineDeployments and eventually to the VMIs.

**Comment by tafkam** [comment]
Having node<->machines labels propagation and configurable anti-affinities would be great. If kubevirt doesn't support pod topology spread this could also be achieved with a cluster-level scheduling profile. 
Having KKP to set any kubevirt-cluster node labels is not a requirement.

**Comment by hdurand0710** [comment]
Hi,

To sum up, the proposition would be:
- the user labels the KubeVirt infra nodes with the labels:
 -topology.kubernetes.io/zone (optional)
 -topology.kubernetes.io/region (optional)
 -kubernetes.io/hostname (mandatory)

- In order to spread VMs among the Kubevirt nodes, the VM are spawned with the following pod a spec including:
```
spec:
      affinity:
               podAntiAffinity:           
                  preferredDuringSchedulingIgnoredDuringExecution:
                        - labelSelector:
                            matchExpressions:
                              - key: <our vm key>
                                operator: In
                                values:
                                  - <our vm value>
                        topologyKey:kubernetes.io/hostname
```

- In order to allow the placement of the user cluster's pod on the user cluster nodes, the following underlying KubeVirt nodes labels are propagated to the MD: 
  -topology.kubernetes.io/zone (optional)
  -topology.kubernetes.io/region (optional)
  -kubernetes.io/hostname (mandatory)
