### ISSUE TITLE
Azure Cleanup hangs when no ResourceGroup is set

### ISSUE THREAD

**Issue by xrstf** [kubermatic/kubermatic#8753]
### What happened?
A usercluster cannot be cleaned up. The seed-ctrl-mgr is logging

> {"level":"error","time":"2022-01-19T10:47:26.259Z","logger":"controller.kubermatic_cloud_controller","caller":"controller/controller.go:317","msg":"Reconciler error","name":"4c5x47hzjh","namespace":"","error":"failed cloud provider cleanup: failed to delete security group \"kubernetes-4c5x47hzjh\": network.SecurityGroupsClient#Delete: Failure sending request: StatusCode=0 -- Original Error: Code=\"InvalidApiVersionParameter\" Message=\"The api-version '2021-03-01' is invalid. The supported versions are '2021-04-01,2021-01-01,2020-10-01,2020-09-01,2020-08-01,2020-07-01,2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'.\"","errorCauses":[{"error":"failed cloud provider cleanup: failed to delete security group \"kubernetes-4c5x47hzjh\": network.SecurityGroupsClient#Delete: Failure sending request: StatusCode=0 -- Original Error: Code=\"InvalidApiVersionParameter\" Message=\"The api-version '2021-03-01' is invalid. The supported versions are '2021-04-01,2021-01-01,2020-10-01,2020-09-01,2020-08-01,2020-07-01,2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'.\""}]}

After googling around for a bit, I found this comment: https://github.com/Azure/azure-sdk-for-go/issues/805#issuecomment-335583486

> Managed to find the issue and it was in my side, my code wasn't populating the vmss name and the resource group correctly and those were being set as empty in the url.

Looking at the cluster in question, the ResourceGroup is indeed empty:

```yaml
spec:
  cloud:
    azure:
      assignAvailabilitySet: true
      availabilitySet: kubernetes-4c5x47hzjh
      credentialsReference:
        name: credential-azure-4c5x47hzjh
        namespace: kubermatic
      loadBalancerSKU: ""
      resourceGroup: ""
      routeTable: kubernetes-4c5x47hzjh
      securityGroup: kubernetes-4c5x47hzjh
      subnet: kubernetes-4c5x47hzjh
      vnet: kubernetes-4c5x47hzjh
      vnetResourceGroup: ""
    dc: azure-eastus
    providerName: azure
```

### What should happen?
The cluster should be cleaned up normally.

### How to reproduce?
- Not sure.

### Environment

- KKP Version: master
- Shared or separate master/seed clusters?: yes
- Master/seed cluster provider: GKE
