### ISSUE TITLE
Incompatibilty between Kubevirt csi driver and Kubevirt ccm  (namespace)

### ISSUE THREAD

**Issue by hdurand0710** [kubermatic/kubermatic#8772]
### What happened?
Create a pod with a persistent volume in a user cluster (provider Kubevirt) with the csi driver.
The pod should start, but it fails with the error:
```Unable to attach or mount volumes: unmounted volumes=[pv0002], unattached volumes=[pv0002 kube-api-access-rmgjq]: timed out waiting for the condition```
Related to: #8643

### What should happen?
The pod should start.

### How to reproduce?
Create a user cluster with Kubevirt provider.
Apply the following manifest in the user cluster:
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ln-kubevirt-disk-default
spec:
  storageClassName: kubevirt
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
```

It creates a pvc and pv in the user cluster (over Kube).

It creates the pvc/pv in the infra cluster (under Kube) in the `default` namespace.
This comes from the `Tenant` CR that is deployed along the csi driver.

```apiVersion: csiprovisioner.kubevirt.io/v1alpha1
kind: Tenant
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"csiprovisioner.kubevirt.io/v1alpha1","kind":"Tenant","metadata":{"annotations":{},"labels":{"kubermatic-addon":"csi"},"name":"tenant"},"spec":{"infraClusterLabels":"cluster-name=6fm9g699fc","infraClusterNamespace":"default"}}
  creationTimestamp: "2022-01-18T13:39:25Z"
  generation: 3
  labels:
    kubermatic-addon: csi
  name: tenant
  resourceVersion: "2337427"
  uid: 17b63c53-588d-481d-875b-a201f0acfb08
spec:
  infraClusterLabels: cluster-name=6fm9g699fc
  infraClusterNamespace: default
```
*infraClusterNamespace: default* -> creates in `default` namespace.

Then create a pod using the pvc:
```
apiVersion: v1 
kind: Pod 
metadata:
  name: testpodwithcsi
spec:
  containers:
  - image: busybox
    name: testpodwithcsi
    command: ["sh", "-c", "while true; do ls -la /opt; echo this file system was made availble using kubevirt-csi-driver; mktmp /opt/test-XXXXXX; sleep 1m; done"]
    imagePullPolicy: Always
    volumeMounts:
    - name: pv0002
      mountPath: "/opt"
  volumes:
  - name: pv0002
    persistentVolumeClaim:
      claimName: ln-kubevirt-disk-default
```

*The pod does not start as it's looking for the `vmi` in the `default` namespace, but the vmi is created by the Kubevirt ccm in `Kubevirt-system` ns.*

*log from csi-controller, container csi-driver*
```
E0124 08:22:47.802339       1 server.go:127] /csi.v1.Controller/ControllerPublishVolume returned with error: Failed to find VM with domain.firmware.uuid 10f41dae-599e-53bc-8d19-636d1bb3b4bd
```

 VM with domain.firmware.uuid 10f41dae-599e-53bc-8d19-636d1bb3b4bd is actually the vmi created in `Kubevirt-system` namespace.

```
k get vmi suspicious-spence-worker-kmwtc4-7586bd8fd7-vjjtp -o go-template={{.spec.domain.firmware}}
map[uuid:10f41dae-599e-53bc-8d19-636d1bb3b4bd
```

### Environment
https://test-env-kkp.ee.lab.kubermatic.io
- KKP Version: v2.19.0-alpha.10
- Shared or separate master/seed clusters?: shared
- Master/seed cluster provider: Kubevirt
