### ISSUE TITLE
kkp 2.19: automatic upgrade of 1.19.x cluster is failing

### ISSUE THREAD

**Issue by toschneck** [kubermatic/kubermatic#8816]
### What happened?
If a cluster is running on 1.19.x the cluster upgrade automation matrix is not working. Unfortunately it seams that this wasn't a testcase and the clusters stucks. 
```
failed to update the controlplane: failed to get automatic update for cluster for version 1.19.15: failed to parse to version 1.20.*: Invalid Semantic Version
```
![image](https://user-images.githubusercontent.com/4659261/151406749-4d7e4865-b356-4db4-b11a-ac40ea1bbc1a.png)

### What should happen?
Upgrade to 1.20.13

### How to reproduce?
- If no KKP upgrade: Somehow disable the automatic update and create a 1.19.x kubernetes cluster.
- Afterwards trigger the automation for upgrades

If the `KubermaticConfiguration` get overwritten with the dedicated version, it works:
```yaml
  versions:
    kubernetes:
      updates:
        - # Automatic controls whether this update is executed automatically
          # for the control plane of all matching user clusters.
          automatic: true
          # Automatic controls whether this update is executed automatically
          # for the worker nodes of all matching user clusters.
          automaticNodeUpdate: false
          # From is the version from which an update is allowed. Wildcards are allowed, e.g. "1.18.*".
          from: 1.19.*
          # From is the version to which an update is allowed. Wildcards are allowed, e.g. "1.18.*".
          to: 1.20.13
        - from: 1.20.*
          to: 1.20.*
        - automatic: true
          from: '>= 1.20.0, < 1.20.13'
          to: 1.20.13
        - from: 1.20.*
          to: 1.21.*
        - from: 1.21.*
          to: 1.21.*
        - automatic: true
          from: '>= 1.21.0, < 1.21.8'
          to: 1.21.8
        - from: 1.21.*
          to: 1.22.*
        - from: 1.22.*
          to: 1.22.*
        - automatic: true
          from: '>= 1.22.0, < 1.22.5'
          to: 1.22.5
`````
### Environment

- KKP Version: 2.19.0
- Shared or separate master/seed clusters?: shared
- Master/seed cluster provider: any

### Note
If possible it would be great to also create an automated test for the matrix and/or do some validation of the inputs.
