### ISSUE TITLE
Upgrade to KKP 2.19 breaks kubevirt cluster template

### ISSUE THREAD

**Issue by toschneck** [kubermatic/kubermatic#8997]
After the upgrade from 2.18 to 2.19 the cluster template of the kubevirt provider broke.
Unfortunately the UI don't show any error and the user is not aware why it's not working.

Taking a look into the logs, shows that somehow the stored credentials having an issue:
```
2022-02-14T15:48:30.088414156Z stderr F {"level":"error","time":"2022-02-14T15:48:30.088Z","logger":"cluster_template_controller","caller":"cluster-template-controller/controller.go:107","msg":"ReconcilingError","worker-name":"","request":"/z6g7fqz5sn-46h278d28x-wbpv9j7htb","error":"failed to get credentials: secret \"kubermatic/credential-kubevirt-46h278d28x\" has no key \"csiKubeConfig\""}
```

![image.png](https://images.zenhubusercontent.com/5b6454d031c5fe7463837d8b/0add0e93-f39c-4194-9fe1-07316f5d4211)

If a new cluster template get created, the issue is not showing up
*new template:*
```
apiVersion: kubermatic.k8s.io/v1
clusterLabels:
  project-id: z6g7fqz5sn
credential: credential-kubevirt-zggw5ncjc7
kind: ClusterTemplate
metadata:
  annotations:
    kubermatic.io/initial-machinedeployment-request: '{"name":"kvirt-new-2-19","creationTimestamp":"0001-01-01T00:00:00Z","spec":{"replicas":1,"template":{"cloud":{"kubevirt":{"cpus":"1","memory":"4Gi","namespace":"kube-system","sourceURL":"http://http-server.kube-system.svc.cluster.local/ubuntu.img","storageClassName":"local-path","pvcSize":"15Gi"}},"operatingSystem":{"ubuntu":{"distUpgradeOnBoot":false}},"versions":{"kubelet":""}}},"status":{}}'
    user: tobias.schneck@kubermatic.com
  labels:
    name: kvirt-new-2-19
    project-id: z6g7fqz5sn
    scope: global
  name: zggw5ncjc7
spec:
  cloud:
    dc: kv-europe-west3-c
    kubevirt:
      credentialsReference:
        name: credential-kubevirt-zggw5ncjc7
        namespace: kubermatic
    providerName: kubevirt
  clusterNetwork:
    dnsDomain: cluster.local
    nodeLocalDNSCacheEnabled: true
    pods:
      cidrBlocks:
      - 172.26.0.0/16
    proxyMode: ipvs
    services:
      cidrBlocks:
      - 10.241.0.0/20
  cniPlugin:
    type: canal
    version: v3.21
  componentsOverride:
    apiserver:
      nodePortRange: 30000-32767
      replicas: 2
    controllerManager:
      replicas: 1
    etcd:
      clusterSize: 3
      diskSize: 5Gi
    scheduler:
      replicas: 1
  containerRuntime: containerd
  enableUserSSHKeyAgent: true
  exposeStrategy: NodePort
  features:
    externalCloudProvider: true
  humanReadableName: kvirt-new-2-19
  pause: false
  version: 1.21.8
userSshKeys: null
```
old template
```
  apiVersion: kubermatic.k8s.io/v1
  clusterLabels:
    project-id: z6g7fqz5sn
  credential: credential-kubevirt-46h278d28x
  kind: ClusterTemplate
  metadata:
    annotations:
      kubermatic.io/initial-machinedeployment-request: '{"name":"kvirt-small-node","creationTimestamp":"0001-01-01T00:00:00Z","spec":{"replicas":1,"template":{"cloud":{"kubevirt":{"cpus":"2","memory":"4Gi","namespace":"default","sourceURL":"http://http-server.kube-system.svc.cluster.local/ubuntu.img","storageClassName":"local-path","pvcSize":"15Gi"}},"operatingSystem":{"ubuntu":{"distUpgradeOnBoot":false}},"versions":{"kubelet":""},"labels":{"type":"kubevirt"}}},"status":{}}'
      user: tobias.schneck@kubermatic.com
    labels:
      name: kubevirt-cluster
      project-id: z6g7fqz5sn
      scope: global
    name: 46h278d28x
  spec:
    cloud:
      dc: kv-europe-west3-c
      kubevirt:
        credentialsReference:
          name: credential-kubevirt-46h278d28x
          namespace: kubermatic
    clusterNetwork:
      dnsDomain: ""
      proxyMode: ipvs
    componentsOverride:
      etcd:
        clusterSize: 3
    containerRuntime: containerd
    enableUserSSHKeyAgent: true
    exposeStrategy: NodePort
    features:
      externalCloudProvider: true
    humanReadableName: kvirt
    opaIntegration:
      enabled: true
    pause: false
    version: 1.21.8
```
The only noticable difference is that the secret contains the key `csiKubeConfig `:
```
apiVersion: v1
data:
  csiKubeConfig: xxx
  kubeConfig: xxxx
kind: Secret
metadata:
  labels:
    name: credential-kubevirt-zggw5ncjc7
    project-id: z6g7fqz5sn
  name: credential-kubevirt-zggw5ncjc7
  namespace: kubermatic
type: Opaque
```

For a seamless user experience the migration of the secret should be added for cluster templates, or some breaking changes notes in the changelog.
