### ISSUE TITLE
Make MLA/OPA settings in KubermaticSettings optional - Test Release 2.20

### ISSUE THREAD

**Issue by mlavacca** [kubermatic/kubermatic#9080]
* Configure KKP without the MLA/OPA part in the KubermaticSettings API
* Check that KKP is correctly configured and working

## References
xref #8869

**Comment by embik** [comment]
Works without any problems on the QA environment. You can switch the setting off an on via the UI and the `KubermaticSetting` resource gets updated. You can also create clusters without any MLA or OPA settings enabled:

```yaml
apiVersion: kubermatic.k8c.io/v1
kind: KubermaticSetting
metadata:
  name: globalsettings
spec:
  cleanupOptions:
    enabled: true
  customLinks: []
  defaultNodeCount: 1
  displayAPIDocs: true
  displayDemoInfo: false
  displayTermsOfService: false
  enableDashboard: true
  enableExternalClusterImport: true
  enableOIDCKubeconfig: false
  machineDeploymentVMResourceQuota:
    enableGPU: false
    maxCPU: 32
    maxRAM: 128
    minCPU: 1
    minRAM: 2
  mlaAlertmanagerPrefix: alertmanager
  mlaGrafanaPrefix: grafana
  mlaOptions: {}
  opaOptions: {}
  restrictProjectCreation: false
  userProjectsLimit: 0
```
