### ISSUE TITLE
Write template tool for ContainerLinux config for k8s clusters

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#918]
We need a tool which generates Container Linux Configs for a Kubernetes Cluster.
This needs to include Master & Worker node configs. The tool needs to parse configuration from a YAML file.

It has 2 prequesits:
- A CA certificate needs to exist before.
- A ServiceAccount key needs to exist before

The config needs to be able to generate a Container Linux Config looking like the one attached.

**Comment by mrIncompetent** [comment]
```yaml
#cloud-config

hostname: gtlocbvh03258.server.arvato-systems.de

coreos:
  update:
    reboot-strategy: "reboot"
  locksmith:
    window-start: Tue 06:00
    window-length: 1h
  units:
    - name: 00-en.network
      runtime: true
      content: |
        [Match]
        Name=en*

        [Network]
        DNS=145.228.121.70
        DNS=145.228.185.60
        DNS=145.228.121.80
        Domains=server.arvato-systems.de bertelsmann.de unix.arvato-systems.de
        Gateway=145.228.6.193
        NTP=145.228.39.153 145.228.183.155 145.228.205.33

        [Address]
        Address=145.228.6.203/27
        Broadcast=145.228.6.197/27

    - name: srv-etcd-data.mount
      command: start
      content: |
        [Unit]
        Description=Mount block device to /srv/etcd/data
        [Mount]
        What=/dev/sdb
        Where=/srv/etcd/data
        Type=ext4
        DirectoryMode=0777

    - name: etcd-member.service
      enable: true
      command: start
      drop-ins:
        - name: 40-mounts.conf
          content: |
            [Unit]
            Requires=srv-etcd-data.mount
            After=srv-etcd-data.mount
        - name: 40-config.conf
          content: |
            [Service]
            Environment="ETCD_IMAGE_TAG=v3.2.6"
            Environment="ETCD_DATA_DIR=/srv/etcd/data"
            Environment="ETCD_ADVERTISE_CLIENT_URLS=http://145.228.6.197:2379"
            Environment="ETCD_INITIAL_ADVERTISE_PEER_URLS=http://127.0.0.1:2380"
            Environment="ETCD_INITIAL_CLUSTER=master1=http://127.0.0.1:2380"
            Environment="ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379"
            Environment="ETCD_LISTEN_PEER_URLS=http://127.0.0.1:2380"
            Environment="ETCD_INITIAL_CLUSTER_STATE=new"
            Environment="ETCD_NAME=master1"

    - name: docker.service
      command: start
      enable: true

    - name: kubelet.service
      command: start
      enable: true
      drop-ins:
        - name: 40-docker.conf
          content: |
            [Unit]
            Requires=docker.service
            After=docker.service
      content: |
        [Unit]
        Description=Kubernetes Kubelet

        [Service]
        Environment=KUBELET_IMAGE_TAG=v1.6.9_coreos.0
        Environment="RKT_RUN_ARGS=--uuid-file-save=/var/run/kubelet-pod.uuid \
          --volume dns,kind=host,source=/etc/resolv.conf \
          --mount volume=dns,target=/etc/resolv.conf \
          --volume cni-conf,kind=host,source=/etc/cni/net.d \
          --mount volume=cni-conf,target=/etc/cni/net.d \
          --volume var-log,kind=host,source=/var/log \
          --mount volume=var-log,target=/var/log"
        ExecStartPre=/usr/bin/mkdir -p /etc/cni/net.d
        ExecStartPre=/usr/bin/mkdir -p /etc/kubernetes/manifests
        ExecStartPre=/usr/bin/mkdir -p /var/log/containers
        ExecStartPre=-/usr/bin/rkt rm --uuid-file=/var/run/kubelet-pod.uuid
        ExecStart=/usr/lib/coreos/kubelet-wrapper \
          --api-servers=http://127.0.0.1:8080 \
          --node-status-update-frequency=4s \
          --register-schedulable=false \
          --container-runtime=docker \
          --allow-privileged=true \
          --cni-conf-dir=/etc/cni/net.d \
          --network-plugin=cni \
          --pod-manifest-path=/etc/kubernetes/manifests \
          --cluster-dns=10.159.0.10 \
          --cluster_domain=cluster.local \
          --v=2
        ExecStop=-/usr/bin/rkt stop --uuid-file=/var/run/kubelet-pod.uuid
        Restart=always
        RestartSec=10

        [Install]
        WantedBy=multi-user.target

    - name: dm_thin_pool.service
      command: start
      enable: true
      content: |
        [Unit]
        Description=Enable kernel module dm_thin_pool for gluster/heketi

        [Service]
        Type=oneshot
        RemainAfterExit=yes
        ExecStart=/usr/sbin/modprobe dm_thin_pool

        [Install]
        WantedBy=multi-user.target

write_files:
  - path: "/etc/kubernetes/manifests/kube-apiserver.yaml"
    content: |
      apiVersion: v1
      kind: Pod
      metadata:
        name: kube-apiserver
        namespace: kube-system
      spec:
        hostNetwork: true
        containers:
        - name: kube-apiserver
          image: quay.io/coreos/hyperkube:v1.6.9_coreos.0
          command:
          - /hyperkube
          - apiserver
          - --bind-address=0.0.0.0
          - --etcd-servers=http://127.0.0.1:2379
          - --allow-privileged=true
          - --service-cluster-ip-range=10.159.0.0/16
          - --secure-port=443
          - --insecure-port=8080
          - --advertise-address=145.228.6.203
          - --admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,ResourceQuota
          - --tls-cert-file=/etc/kubernetes/ssl/apiserver.pem
          - --tls-private-key-file=/etc/kubernetes/ssl/apiserver-key.pem
          - --client-ca-file=/etc/kubernetes/ssl/ca.pem
          - --service-account-key-file=/etc/kubernetes/ssl/apiserver-key.pem
          - --authorization-mode=AlwaysAllow,RBAC
          - --experimental-bootstrap-token-auth=true
          - --token-auth-file=/etc/kubernetes/ssl/token.csv
          - --kubelet-client-certificate=/etc/kubernetes/ssl/apiserver.pem
          - --kubelet-client-key=/etc/kubernetes/ssl/apiserver-key.pem
          - --v=4
          livenessProbe:
            httpGet:
              host: 127.0.0.1
              port: 8080
              path: /healthz
            initialDelaySeconds: 15
            timeoutSeconds: 15
          ports:
          - containerPort: 443
            hostPort: 443
            name: https
          - containerPort: 8080
            hostPort: 8080
            name: local
          volumeMounts:
          - mountPath: /etc/kubernetes/ssl
            name: ssl-certs-kubernetes
            readOnly: true
          - mountPath: /etc/ssl/certs
            name: ssl-certs-host
            readOnly: true
        volumes:
        - hostPath:
            path: /etc/kubernetes/ssl
          name: ssl-certs-kubernetes
        - hostPath:
            path: /usr/share/ca-certificates
          name: ssl-certs-host

  - path: "/etc/kubernetes/manifests/kube-controller-manager.yaml"
    content: |
      apiVersion: v1
      kind: Pod
      metadata:
        name: kube-controller-manager
        namespace: kube-system
      spec:
        hostNetwork: true
        containers:
        - name: kube-controller-manager
          image: quay.io/coreos/hyperkube:v1.6.9_coreos.0
          command:
          - /hyperkube
          - controller-manager
          - --master=http://127.0.0.1:8080
          - --leader-elect=true
          - --service-cluster-ip-range=10.159.0.0/16
          - --service-account-private-key-file=/etc/kubernetes/ssl/apiserver-key.pem
          - --root-ca-file=/etc/kubernetes/ssl/ca.pem
          - --address=127.0.0.1
          - --allocate-node-cidrs=true
          - --cluster-cidr=10.158.0.0/16
          - --insecure-experimental-approve-all-kubelet-csrs-for-group=system:kubelet-bootstrap
          - --cluster-signing-cert-file=/etc/kubernetes/ssl/ca.pem
          - --cluster-signing-key-file=/etc/kubernetes/ssl/ca-key.pem
          - --node-monitor-period=2s
          - --node-monitor-grace-period=16s
          - --pod-eviction-timeout=30s
          - --v=4
          resources:
            requests:
              cpu: 200m
          livenessProbe:
            httpGet:
              host: 127.0.0.1
              path: /healthz
              port: 10252
            initialDelaySeconds: 15
            timeoutSeconds: 15
          volumeMounts:
          - mountPath: /etc/kubernetes/ssl
            name: ssl-certs-kubernetes
            readOnly: true
          - mountPath: /etc/ssl/certs
            name: ssl-certs-host
            readOnly: true
        volumes:
        - hostPath:
            path: /etc/kubernetes/ssl
          name: ssl-certs-kubernetes
        - hostPath:
            path: /usr/share/ca-certificates
          name: ssl-certs-host

  - path: "/etc/kubernetes/manifests/kube-scheduler.yaml"
    content: |
      apiVersion: v1
      kind: Pod
      metadata:
        name: kube-scheduler
        namespace: kube-system
      spec:
        hostNetwork: true
        containers:
        - name: kube-scheduler
          image: quay.io/coreos/hyperkube:v1.6.9_coreos.0
          command:
          - /hyperkube
          - scheduler
          - --master=http://127.0.0.1:8080
          - --leader-elect=true
          - --v=2
          resources:
            requests:
              cpu: 100m
          livenessProbe:
            httpGet:
              host: 127.0.0.1
              path: /healthz
              port: 10251
            initialDelaySeconds: 15
            timeoutSeconds: 15

  - path: "/etc/kubernetes/manifests/kube-proxy.yaml"
    content: |
      apiVersion: v1
      kind: Pod
      metadata:
        name: kube-proxy
        namespace: kube-system
      spec:
        hostNetwork: true
        containers:
        - name: kube-proxy
          image: quay.io/coreos/hyperkube:v1.6.9_coreos.0
          command:
          - /hyperkube
          - proxy
          - --master=http://127.0.0.1:8080
          - --cluster-cidr=10.158.0.0/16
          securityContext:
            privileged: true
          volumeMounts:
          - mountPath: /etc/ssl/certs
            name: ssl-certs-host
            readOnly: true
        volumes:
        - hostPath:
            path: /usr/share/ca-certificates
          name: ssl-certs-host

  - path: "/etc/kubernetes/ssl/ca.pem"
    content: |

  - path: "/etc/kubernetes/ssl/apiserver.pem"
    content: |

  - path: "/etc/kubernetes/ssl/apiserver-key.pem"
    content: |

  - path: "/etc/kubernetes/ssl/ca-key.pem"
    content: |

  - path: "/etc/kubernetes/ssl/token.csv"
    content: |

ssh_authorized_keys:
  - "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAsu1XeN6/FMKNM3tyuimURTOQ9ztcSCZFnfia+x9EjEov2djseSjYdOnEeGXoGWQ0ljvi8lYAYjPSGkmobKaWexsL0AdvzlQvlRhxlaNNYdlx9RPk0qsnCCUuCbWXqrcEonP/7RUOTSJFOtFcO+pkJKO9DujsUFGXGPMgZQaKwmgb2L4HvP1CN2/pZQjs17ofqFsGEYlxY5KUztDb26SeaUujGEiJ0Au1X3rGcBsuQotPvpXX1j7aQWkugJZ03y22J34Ag9xIuVkh/MzoSELaACdVTLDel46Z2p6Agm+D9FcihP0Xv7MhFZy0SzX0InIk60hbjQgSUuj6xqBQ8yvWIQ== kubermatic-master"

```
