### ISSUE TITLE
Test project creation - Test Release 2.20

### ISSUE THREAD

**Issue by ahmedwaleedmalik** [kubermatic/kubermatic#9186]
# Instructions

Following scenarios should be tested:
1. Create multiple projects using the dashboard and ensure that everything works
<img width="1800" alt="Screenshot 2022-03-02 at 3 06 42 PM" src="https://user-images.githubusercontent.com/18264334/156341324-c5339678-ef22-46c3-8aea-4a4cb9c4f55e.png">

2. Create a project using CLI and ensure that `.status.Phase` is set to `inactive`.
```yaml
apiVersion: kubermatic.k8c.io/v1
kind: Project
metadata:
  name: test
spec:
  name: test-readable-name
```
**NOTE: Please cleanup the project created using the CLI as soon as you are done with testing.**

# References

xref https://github.com/kubermatic/kubermatic/pull/9159
