### ISSUE TITLE
Way to specify auth secrets/keys using secret in KubermaticConfiguration

### ISSUE THREAD

**Issue by SnehaMore20** [kubermatic/kubermatic#9204]
### What would you like to be added? / User Story
Currently KubermaticConfiguration  object contains the auth secrets/keys (issuerClientSecret, issuerCookieKey, serviceAccountKey) as plain values.
It will be helpful if we can use secret reference for these values

#### Current CR:
```
apiVersion: operator.kubermatic.io/v1alpha1
kind: KubermaticConfiguration
metadata:
  name: <<mykubermatic>>
  namespace: kubermatic
spec:
  api:
    accessibleAddons:
      - cluster-autoscaler
      - node-exporter
      - kube-state-metrics
      - multus
    debugLog: false
    dockerRepository: quay.io/kubermatic/kubermatic
    pprofEndpoint: :6600
    replicas: 2
    resources:
      limits:
        cpu: 250m
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 512Mi
  # Auth defines keys and URLs for Dex.
  auth:
    clientID: kubermatic
    issuerClientID: kubermaticIssuer
    issuerClientSecret: "xyz"
    issuerCookieKey: "abc"
    issuerRedirectURL: https://example.com/api/v1/kubeconfig
    serviceAccountKey: "pqr"
    skipTokenIssuerTLSVerify: false
    tokenIssuer: https://example.com/dex
```
#### Expected CR:
```
apiVersion: operator.kubermatic.io/v1alpha1
kind: KubermaticConfiguration
metadata:
  name: <<mykubermatic>>
  namespace: kubermatic
spec:
  api:
    accessibleAddons:
      - cluster-autoscaler
      - node-exporter
      - kube-state-metrics
      - multus
    debugLog: false
    dockerRepository: quay.io/kubermatic/kubermatic
    pprofEndpoint: :6600
    replicas: 2
    resources:
      limits:
        cpu: 250m
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 512Mi
  # Auth defines keys and URLs for Dex.
  auth:
    clientID: kubermatic
    issuerClientID: kubermaticIssuer
    issuerClientSecret: 
       secretKeyRef:
          name: kubermatic-auth-secrets
          key: issuerClientSecret
    issuerCookieKey: 
       secretKeyRef:
          name: kubermatic-auth-secrets
          key: issuerCookieKey
    issuerRedirectURL: https://example.com/api/v1/kubeconfig
    serviceAccountKey:
       secretKeyRef:
          name: kubermatic-auth-secrets
          key: serviceAccountKey
    skipTokenIssuerTLSVerify: false
    tokenIssuer: https://example.com/dex
```
