### ISSUE TITLE
Dual-stack support for kubeadm clusters

### ISSUE THREAD

**Issue by rastislavs** [kubermatic/kubermatic#9354]
Add dual-stack support for KKP user-clusters on this provider:

- [x] Investigate dual-stack capabilities of the provider
- [x] Add dual-stack support for KKP-managed cloud-provider configuration
- [ ] Add dual-stack support for the cloud-provider in machine-controller

**Comment by rastislavs** [comment]
- No need for change in KKP code
- IPv4 & IPv6 node-ip flag needs to be provided to kubelet on node join

Example steps to join:

- do `kubeadm token --kubeconfig <your-kubeconfig> create --print-join-command`
- from the output, generate yaml file with `JoinConfiguration` such as:
```
apiVersion: kubeadm.k8s.io/v1beta3
kind: JoinConfiguration
discovery:
  bootstrapToken:
    # change auth info below to match the actual api server endpoint, token and CA certificate hash for your cluster
    apiServerEndpoint: fghk7gd5tx.europe-west3-c.dev.kubermatic.io:30038
    token: "9xwn14.ktdfg3s3fqyj0dr9"
    caCertHashes:
    - "sha256:b36ebfbcf51e019e6c763dd95bbc307ee4e96e9534d3133a65cf185c0dd74551"
nodeRegistration:
  kubeletExtraArgs:
    # change the node-ip below to match your desired IPv4 and IPv6 addresses of the node
    node-ip: 10.0.6.114,2a05:d014:937:4500:a324:767b:38da:2bff
```
- run `kubeadm join --config kubeadm-join-config.yaml`
