### ISSUE TITLE
Seed can't be deleted

### ISSUE THREAD

**Issue by hc2p** [kubermatic/kubermatic#9542]
### What happened?
Sometimes seeds can't be deleted.

```
{"level":"error","ts":1649233019.198488,"logger":"controller.seed-sync-controller","msg":"Reconciler error","name":"eu-central-1","namespace":"kubermatic","error":"failed to cleanup deleted Seed: failed to delete kubermatic/eu-central-1: resource name may not be empty","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tsigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227"}
```

`kubectl delete seed <seed name>` get's stuck. 

`kubectl get seed <seed name> -o yaml` excerpt:
```
apiVersion: kubermatic.k8s.io/v1
kind: Seed
metadata:
  creationTimestamp: '2022-04-05T15:49:47Z'
  deletionGracePeriodSeconds: 0
  deletionTimestamp: '2022-04-05T17:28:25Z'
  finalizers:
    - kubermatic.io/cleanup-seed-sync
 ```

More context in [this Slack thread](https://kubermatic.slack.com/archives/CK503V7QC/p1649170594779219?thread_ts=1649170132.860829&cid=CK503V7QC)

### What should happen?
The seed object should always be cleaned-up and should be, if something fails, manually deletable. 

### How to reproduce?
Given a master-cluster/ remote seed-cluster setup
When master-cluster stops synching e.g. master-cluster got a fresh install
Then the seed-cluster still has that seed object
Then the seed object on the seed-cluster can't be deleted.

Given a master-cluster/ remote seed-cluster setup
When I delete the seed object on the seed-cluster
Then the seed is still on the master-cluster
Then the seed on the master-cluster can't be manually deleted.

### Environment

- KKP Version: 2.19.4
- Shared or separate master/seed clusters?: separate
- Master/seed cluster provider: master: gcp, seed: aws
