### ISSUE TITLE
Add CRDs for IPAMPool and IPAMAllocation

### ISSUE THREAD

**Issue by rastislavs** [kubermatic/kubermatic#9903]
Add CRDs IPAMPool and IPAMAllocation based on the idea of the old proposal for [Multi-Cluster IPAM](https://github.com/kubermatic/kubermatic/blob/master/docs/proposals/multi-cluster-ipam.md).

As an addition to the original proposal, we would add support for subnets (the old proposal CRD would be valid for type: range):

```yaml
apiVersion: kubermatic.k8c.io/v1
kind: IPAMPool
metadata:
  name: metallb
spec:
  type: subnet
  datacenters: 
  - vsphere-hamburg:
    poolCIDR: 192.168.1.0/16
    allocationPrefix: 28
```

```yaml
apiVersion: kubermatic.k8c.io/v1
kind: IPAMAllocation
metadata:
  name: metallb
  namespace: cluster-xyz
spec:
  type: subnet
  cidr: 192.168.1.16/28
```
