### ISSUE TITLE
[kkp 2.19] vsphere-csi-controller crashloopbackoff when using custom caBundle

### ISSUE THREAD

**Issue by dharapvj** [kubermatic/kubermatic#9988]
### What happened?

After migration to v2.19.5 from v2.18.10 - for vsphere seeds, 
User-cluster vsphere-csi-controller pod goes in crashloopbackoff
with below error being thrown in the logs:

```
{"level":"error","time":"2022-06-07T05:49:35.254089169Z","caller":"service/driver.go:157","msg":"failed to run the driver. Err: +Post \"https://XXXXX.com:443/sdk\": x509: certificate signed by unknown authority","TraceId":"9c28f03a-e3fa-41fc-acfb-f51ebc9df6fa","stacktrace":"sigs.k8s.io/vsphere-csi-driver/v2/pkg/csi/service.(*vsphereCSIDriver).Run
	/build/pkg/csi/service/driver.go:157
main.main
	/build/cmd/vsphere-csi/main.go:89
runtime.main
	/usr/local/go/src/runtime/proc.go:225"}
```
This happens when 
1. we use `allow_insecure:false` in seed datacenter defintion 
2. We use a custom caBundle in operator config

I observed that the custom caBundle content is available in user-cluster in configmap `kube-system/ca-bundle` but the vsphere-csi-controller pod makes no reference to it and hence it has no knowledge of this custom CA Bundle

### Expected behavior

vsphere-csi-controller pod should not crashloop

### How to reproduce the issue?

1. Use kkp 2.18.10 and create a usercluster in vsphere based seed
2. Use custom caBundle in kubermatic.operator.yaml
3. set `allow_insecure: false` in vsphere seed datacenter config
4. upgrade to kkp 2.19
5. Observe user-cluster pods

### How is your environment configured?

- KKP version: 2.19.5
- Shared or separate master/seed clusters?: Separate master and seed

### Provide your KKP manifest here (if applicable)

<details>

```yaml
# seed.yaml - datacenter def
    service-dev:
      country: "DE"
      location: "DEV"
      spec:
        vsphere:
          allow_insecure: false
          cluster: "XXXXX vSAN"
          datacenter: "XXXXX"
          datastore: "XXXXX_vSAN-Datastore"
          endpoint: "https://XXXXX"
          root_path: "/XXXXXX"
          templates:
            ubuntu: "/XXXXX/templates/ubuntu-09-2021"

---
# Operator config
apiVersion: operator.kubermatic.io/v1alpha1
kind: KubermaticConfiguration
metadata:
  name: kubermatic
  namespace: kubermatic
spec:
  caBundle:
    # name of the ConfigMap;
    # must be in the same namespace as KKP
    name: custom-ca-bundle
```

</details>

### What cloud provider are you running on?

VMware Vsphere

### What operating system are you running in your user cluster?

Ubuntu 20.04

### Additional information

This issue is not present in vsphere csi driver version present in kkp 2.18.10
